- src/onegov/agency/app.py
- src/onegov/agency/cli.py
- src/onegov/agency/excel_export.py
- src/onegov/agency/layouts/people.py
- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
- src/onegov/agency/templates/extended_people.pt
- src/onegov/agency/theme/styles/agency.scss
- src/onegov/agency/upgrade.py
- src/onegov/agency/views/agencies.py
- src/onegov/agency/views/people.py
- src/onegov/agency/views/settings.py
- tests/onegov/agency/test_excel_export.py
- tests/onegov/agency/test_layouts.py
- tests/onegov/agency/test_views.py
- Adds Excel Export Button to people view and Download link to /people
- Adds cli command to create PDF (has to be fixed later)
- Fixes bug for static assigned page break level in views
> Agency excel export

- src/onegov/election_day/formats/common.py
- src/onegov/election_day/queries/aggregated_list_results.sql
- src/onegov/election_day/utils/election/lists.py
- src/onegov/election_day/views/election/data.py
- tests/onegov/election_day/common.py
- tests/onegov/election_day/formats/election/test_wabstic_majorz.py
- tests/onegov/election_day/formats/election/test_wabstic_proporz.py
- tests/onegov/election_day/queries/aggregated_list_results.sql
- tests/onegov/election_day/views/test_views_api.py
Added endpoint for aggregated lists data. Is avaialable on /election/example/data-aggregated-lists.
> Election day lists api endpoint

- src/onegov/core/layout.py
did it the same way as before and tested if it worked...
> Adds week translations for italian and rumantsch

- src/onegov/election_day/assets/js/charts-init.js
- src/onegov/election_day/assets/js/d3.map.entities.js
- src/onegov/election_day/templates/election/heatmap.pt
Fixes hiding percentages in `candidate-by-entity-chart`
> Hide percentages fix

- src/onegov/election_day/assets/js/charts-init.js
- src/onegov/election_day/assets/js/d3.map.districts.js
- src/onegov/election_day/hidden_by_principal.py
- src/onegov/election_day/views/election/candidate_district.py
- src/onegov/election_day/views/election/candidate_entity.py
Also enables `principal.yml` to hide percentages in `candidate-by-district`
> Adds hiding percentages candidate district map

- src/onegov/agency/forms/agency.py
- src/onegov/agency/pdf.py
- src/onegov/agency/utils.py
- src/onegov/agency/views/agencies.py
> Agency pdf improve

- src/onegov/agency/pdf.py
Fixes two problems of pdf rendering:
- Separation of parent title from following organisation
- Too much space if after portrait a new title follows.
> Agency pdf

- src/onegov/fsi/collections/attendee.py
- src/onegov/fsi/collections/reservation.py
- src/onegov/fsi/cronjobs.py
- src/onegov/fsi/forms/course_attendee.py
- src/onegov/fsi/layouts/course.py
- src/onegov/fsi/layouts/course_attendee.py
- src/onegov/fsi/layouts/course_event.py
- src/onegov/fsi/layouts/reservation.py
- src/onegov/fsi/models/course_event.py
- src/onegov/fsi/path.py
- src/onegov/fsi/request.py
- src/onegov/fsi/security.py
- src/onegov/fsi/templates/macros.pt
- src/onegov/fsi/templates/reservations.pt
- src/onegov/fsi/views/attendee.py
- src/onegov/fsi/views/notifcations.py
- src/onegov/fsi/views/reservation.py
- tests/onegov/fsi/common.py
- tests/onegov/fsi/test_collections.py
- tests/onegov/fsi/test_views_reservation.py
- tests/onegov/fsi/test_views_templates.py
Reflects adaptions for the editor role:
- Hides Links in editbar
- Changes permissions for editor (notification sending, placing subscriptions)
- adapts reservations view to filter with editor permissions
> Fsi editor limitations

- src/onegov/fsi/collections/reservation.py
- src/onegov/fsi/cronjobs.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/models/course_notification_template.py
- src/onegov/fsi/templates/mail_macros.pt
- src/onegov/fsi/templates/notifications.pt
- src/onegov/fsi/upgrade.py
- src/onegov/fsi/views/course.py
- src/onegov/fsi/views/notifcations.py
- src/onegov/fsi/views/reservation.py
- tests/onegov/fsi/test_cronjobs.py
- tests/onegov/fsi/test_models.py
- tests/onegov/fsi/test_views_course.py
- tests/onegov/fsi/test_views_course_event.py
- tests/onegov/org/common.py
> Fsi translations fix

- src/onegov/fsi/forms/notification.py
- src/onegov/fsi/layouts/notification.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/views/notifcations.py
Fixes some issues for the beta testing.
> Fsi minor fixes

- src/onegov/swissvotes/layouts/default.py
- src/onegov/swissvotes/layouts/vote.py
- src/onegov/swissvotes/models/vote.py
- src/onegov/swissvotes/templates/vote.pt
- src/onegov/swissvotes/views/vote.py
- tests/onegov/swissvotes/test_collections.py
- tests/onegov/swissvotes/test_models.py
- tests/onegov/swissvotes/test_views_vote.py
Add static urls for all pdf attachments for all languages available.
> Swissvotes static urls

- src/onegov/swissvotes/layouts/page.py
- src/onegov/swissvotes/models/page.py
- src/onegov/swissvotes/templates/page.pt
- src/onegov/swissvotes/templates/vote.pt
- src/onegov/swissvotes/views/page.py
static url for defined dataset files
> Swissvotes dataset static urls

- src/onegov/fsi/collections/attendee.py
- src/onegov/fsi/collections/reservation.py
- src/onegov/fsi/custom.py
- src/onegov/fsi/forms/reservation.py
- src/onegov/fsi/layouts/course.py
- src/onegov/fsi/layouts/course_attendee.py
- src/onegov/fsi/layouts/course_event.py
- src/onegov/fsi/layouts/reservation.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/models/course.py
- src/onegov/fsi/models/course_attendee.py
- src/onegov/fsi/path.py
- src/onegov/fsi/templates/course.pt
- src/onegov/fsi/templates/course_attendee.pt
- src/onegov/fsi/templates/courses.pt
- src/onegov/fsi/templates/macros.pt
- src/onegov/fsi/templates/reservations.pt
- src/onegov/fsi/theme/styles/fsi.scss
- src/onegov/fsi/views/course.py
- src/onegov/fsi/views/course_event.py
- src/onegov/fsi/views/reservation.py
- tests/onegov/fsi/common.py
- tests/onegov/fsi/conftest.py
- tests/onegov/fsi/test_collections.py
- tests/onegov/fsi/test_views_course_event.py
- tests/onegov/fsi/test_views_reservation.py
- Fixes redicret to course collection after subscription
- Fixes choices translation on None
- Introduces separate form for placeholder subscription
- Hides email and shortcode if viewing own subscriptions
- Ensure editors and admin can add subscriptions
- Fixes editor can see his own subscriptions when seeing all
- other minor issues
> Fsi beta improvements

- src/onegov/fsi/collections/audit.py
- src/onegov/fsi/collections/course.py
- src/onegov/fsi/collections/course_event.py
- src/onegov/fsi/forms/audit.py
- src/onegov/fsi/forms/course.py
- src/onegov/fsi/forms/reservation.py
- src/onegov/fsi/layouts/audit.py
- src/onegov/fsi/layouts/course.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/models/course.py
- src/onegov/fsi/models/course_attendee.py
- src/onegov/fsi/path.py
- src/onegov/fsi/templates/audits.pt
- src/onegov/fsi/templates/course.pt
- src/onegov/fsi/templates/macros.pt
- src/onegov/fsi/templates/mail_macros.pt
- src/onegov/fsi/templates/reservations.pt
- src/onegov/fsi/theme/styles/fsi.scss
- src/onegov/fsi/views/audit.py
- src/onegov/fsi/views/course.py
- src/onegov/server/cli.py
- tests/onegov/fsi/test_collections.py
- tests/onegov/fsi/test_views_course_event.py
- tests/onegov/fsi/test_views_reservation.py
Adds the audit section of the app.
- changes sorting of event in event listing
- removed long course description from emails
- hides hidden course events for editors in `/courses`
> Fsi auditing

- src/onegov/activity/models/occasion_need.py
- src/onegov/activity/models/volunteer.py
- tests/onegov/activity/test_models.py
- fixes ForeignKeyConstraintViolation on voluteer
> Cascade deletion of Volunteer if OccasionNeed is deleted

- src/onegov/event/models/event.py
- src/onegov/form/integration.py
- src/onegov/org/forms/userprofile.py
- tests/onegov/form/test_parser.py
Fixes form input "send daily ticket statistics" and error in template when seeing an event and its virtual occurences.
Type: Bugfix
> Org: Fixes virtual occurence for dates years ahead

- src/onegov/ballot/models/election/candidate.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/proporz_election.py
- tests/onegov/ballot/models/test_candidate.py
- tests/onegov/ballot/models/test_list.py
- tests/onegov/election_day/common.py
- tests/onegov/election_day/views/test_views_election.py
Fixe calculation for candidates-by-entity and by district for proporz and majorz elections
> Wab calc fix

- src/onegov/ballot/models/election/candidate.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/list.py
- src/onegov/ballot/models/election/proporz_election.py
- src/onegov/election_day/static/municipalities/2020/sz.json
- tests/onegov/ballot/models/test_candidate.py
- tests/onegov/ballot/models/test_list.py
- tests/onegov/election_day/views/test_views_election.py
Reverts last made changes to wab percentages calculation for better code. Current code is verified with real election statistics. 
- Adds votes to json for `by-entity` and `by-district` for candidate and list.
> Wab proporz perc calc

- src/onegov/activity/models/period.py
- src/onegov/feriennet/models/volunteer_cart.py
- src/onegov/feriennet/queries/card_items.sql
- src/onegov/feriennet/templates/occasion_attendees.pt
- src/onegov/feriennet/views/activity.py
- tests/onegov/activity/test_models.py
> Feriennet fixes

- src/onegov/election_day/layouts/detail.py
- src/onegov/election_day/layouts/election.py
- src/onegov/election_day/layouts/election_compound.py
- src/onegov/election_day/layouts/vote.py
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/utils/pdf_generator.py
- tests/onegov/election_day/layouts/test_election_layout.py
- tests/onegov/election_day/layouts/test_vote_layout.py
- tests/onegov/election_day/models/test_principal.py
> ElectionDay: Fixes label districts for sz for pre 2020

- src/onegov/org/models/directory.py
- src/onegov/org/path.py
- src/onegov/org/upgrade.py
- tests/onegov/org/test_browser.py
Mainly a migration of  FormFile's to DirectoryFiles if they belong to a DirectoryEntry.
> Org file permissions directory fix

- src/onegov/org/forms/allocation.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/allocation.py
- tests/onegov/org/test_forms.py
Org/Resource/Room: Adds quota to rooms so that the same time slot can be booked multiple times.
> Org resource slots

- src/onegov/wtfs/forms/report.py
- src/onegov/wtfs/layouts/report.py
- src/onegov/wtfs/locale/de_CH/LC_MESSAGES/onegov.wtfs.po
- src/onegov/wtfs/models/report.py
- src/onegov/wtfs/models/scan_job.py
- src/onegov/wtfs/templates/report_boxes.pt
- src/onegov/wtfs/templates/report_boxes_and_forms.pt
- src/onegov/wtfs/templates/report_delivery.pt
- src/onegov/wtfs/templates/report_forms.pt
- src/onegov/wtfs/templates/report_forms_all.pt
- src/onegov/wtfs/views/report.py
- tests/onegov/wtfs/test_models.py
- tests/onegov/wtfs/test_views_report.py
Fixes reports that span over two years and more
> Wtfs reports fix

- src/onegov/fsi/forms/course.py
- src/onegov/fsi/layouts/audit.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/models/course.py
- src/onegov/fsi/templates/audits.pt
- src/onegov/fsi/upgrade.py
- tests/onegov/fsi/common.py
- tests/onegov/fsi/test_collections.py
- tests/onegov/fsi/test_views_audit.py
> Changes refresh_interval to years and fix inconsistencies

- src/onegov/agency/layout.py
- src/onegov/agency/templates/macros.pt
- src/onegov/agency/views/settings.py
- src/onegov/org/models/organisation.py
Enables display of full path of organisation on detail view of person
> Agency settings agency path

- src/onegov/agency/cli.py
Adds consolidation script for double entries based on email or other field.
Type: Feature
> Agency: Adds consolidate routine to clear double entries

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/utils/pdf_generator.py
- tests/onegov/election_day/models/test_principal.py
- tests/onegov/election_day/views/test_views_election_compound.py
Implements creating pdfs for votes that are not yet completed. Configurations for rendering incomplete Elections will cause an app error.
> Election day intermediate result vote pdf

- src/onegov/feriennet/app.py
- src/onegov/feriennet/exports/base.py
- src/onegov/feriennet/forms/activity.py
- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/theme/styles/feriennet.scss
Adds more tags for activities, adds banner info for Sponsors, adds Booking Date to Exports
> Wwf spring 2

- onegov.yml.example
- setup.py
- src/onegov/org/templates/login.pt
- src/onegov/org/views/auth.py
- src/onegov/user/auth/clients/msal.py
- src/onegov/user/auth/core.py
- src/onegov/user/auth/provider.py
- src/onegov/user/integration.py
- src/onegov/user/locale/de_ch/LC_MESSAGES/onegov.user.po
- src/onegov/user/locale/fr_CH/LC_MESSAGES/onegov.user.po
- src/onegov/user/locale/it_CH/LC_MESSAGES/onegov.user.po
- src/onegov/user/locale/rm_CH/LC_MESSAGES/onegov.user.po
- tests/onegov/user/test_oauth_msal.py
Implements separate auth provider msal using the app.browser_session to store identity.
> Msal provider

- src/onegov/directory/collections/directory_entry.py
- src/onegov/org/views/directory.py
- tests/onegov/org/test_views.py
Disables alphabetical sorting of filter and take the ordering of the form structure.
> Directory filter sorting

- src/onegov/directory/archive.py
- src/onegov/org/layout.py
- src/onegov/org/views/directory.py
Adds public export link for directory. Does not include entries, that are not visible for the authenticated/anon user.
> Directory public export

- src/onegov/agency/forms/__init__.py
- src/onegov/agency/forms/mutation.py
- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
- src/onegov/agency/models/__init__.py
- src/onegov/agency/models/message.py
- src/onegov/agency/models/mutation.py
- src/onegov/agency/models/ticket.py
- src/onegov/agency/path.py
- src/onegov/agency/templates/macros.pt
- src/onegov/agency/templates/message_agency_mutation.pt
- src/onegov/agency/templates/message_person_mutation.pt
- src/onegov/agency/views/agencies.py
- src/onegov/agency/views/mutations.py
- src/onegov/agency/views/people.py
- src/onegov/org/templates/form.pt
- tests/onegov/agency/test_forms.py
- tests/onegov/agency/test_models.py
- tests/onegov/agency/test_views.py
Users can directly propose changes to fields of agencies and people. Redactors can select, which changes they want to apply.
TYPE: Feature
LINK: STAKABS-34
> Agency: Improves mutations

- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/election_compound.py
- src/onegov/election_day/forms/election.py
- src/onegov/election_day/forms/election_compound.py
- src/onegov/election_day/layouts/detail.py
- src/onegov/election_day/layouts/election.py
- src/onegov/election_day/layouts/election_compound.py
- src/onegov/election_day/layouts/vote.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/static/municipalities/2020/sz.json
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/utils/pdf_generator.py
- src/onegov/election_day/views/election_compound/candidates.py
- tests/onegov/election_day/forms/test_election_compound_form.py
- tests/onegov/election_day/layouts/test_election_compound_layout.py
- tests/onegov/election_day/models/test_principal.py
- tests/onegov/election_day/test_app.py
This requires to re-upload results from 2020.
TYPE: Bugfix
LINK: OGC-41
> Election Day: Fix static data of canton SZ for 2020.

- src/onegov/org/views/usermanagement.py
- src/onegov/user/collections/user.py
- tests/onegov/user/test_collections.py
> Org: Allow to filter local users.

- src/onegov/agency/app.py
- src/onegov/core/utils.py
- src/onegov/org/app.py
- src/onegov/org/models/extensions.py
- tests/onegov/core/test_utils.py
- tests/onegov/org/test_extensions.py
> Agency: Disable person link extensions.

- src/onegov/core/cli/core.py
> Core: Fixes setting up logging too late.

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/layout.pt
> change logo-alt-description as

- src/onegov/core/mail.py
- src/onegov/election_day/collections/subscribers.py
- src/onegov/election_day/models/notification.py
- src/onegov/org/app.py
- tests/onegov/core/test_mail.py
> Core: Ensures address fields are formatted correctly for Postmark API.

- src/onegov/election_day/screen_widgets/__init__.py
- src/onegov/election_day/screen_widgets/election.py
- tests/onegov/election_day/forms/test_screen_form.py
- tests/onegov/election_day/screen_widgets/test_election_widgets.py
Adjust init, election and test files accordingly
> Make Allocated Total and Mandates Widgets

- src/onegov/org/templates/macros.pt
- src/onegov/org/views/form_collection.py
- tests/onegov/org/test_views_forms.py
Shows date of current registration window and available spots in forms list.
TYPE: Feature
LINK: OGC-381
> Org: Shows registration window info in forms list

- src/onegov/fsi/cli.py
> FSI: Restricts LDAP import to @gibz.ch users.

- onegov.yml.example
- src/onegov/core/cli/commands.py
- src/onegov/core/mail_processor/__init__.py
- src/onegov/core/mail_processor/core.py
- src/onegov/core/mail_processor/postmark.py
- src/onegov/core/mail_processor/smtp.py
- src/onegov/server/config.py
- tests/onegov/core/conftest.py
- tests/onegov/core/test_cli.py
- tests/shared/fixtures.py
> Core: Adds back the ability to send mails through SMTP.

- src/onegov/org/views/page.py
> Org: Fix topic children links.

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/election/candidates.pt
- src/onegov/election_day/templates/election_compound/candidates.pt
- src/onegov/election_day/views/election/candidates.py
- src/onegov/election_day/views/election_compound/candidates.py
> Election Day: Hide empty candidates tables and figures.

- setup.py
> Core: Unpin pytest.

- setup.py
- src/onegov/form/parser/core.py
> Form: Adds compatibility with pyparsing 3.

- src/onegov/org/forms/allocation.py
- src/onegov/org/utils.py
- src/onegov/reservation/models/custom_allocation.py
- tests/onegov/org/test_forms.py
- tests/onegov/org/test_views_resources.py
> Org: Allows setting of access for individual allocations and rules.

- tests/onegov/wtfs/test_security.py
> WTFS: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/winterthur/models/mission_report.py
- tests/onegov/winterthur/test_mission_reports.py
> Winterthur: Improve compatibility with SQLAlchemy 1.4

- src/onegov/event/collections/occurrences.py
> Event: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/ballot/collections/election_compounds.py
- src/onegov/ballot/collections/elections.py
- src/onegov/ballot/collections/votes.py
- tests/onegov/ballot/collections/test_election_compounds.py
- tests/onegov/ballot/collections/test_votes.py
> Ballot: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/election_day/collections/archived_results.py
- src/onegov/election_day/models/notification.py
- src/onegov/election_day/models/subscriber.py
- src/onegov/election_day/upgrade.py
- tests/onegov/election_day/layouts/test_election_layout.py
- tests/onegov/election_day/layouts/test_mail_layout.py
- tests/onegov/election_day/models/test_notification.py
> Election Day: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/core/i18n.py
- src/onegov/election_day/views/locale.py
- src/onegov/org/views/locale.py
- src/onegov/swissvotes/views/locale.py
> Core: Set SameSite to locale cookie.

- src/onegov/core/cache.py
- tests/onegov/core/test_cache.py
> Core: Avoid lua stack overflow when flushing caches.

- src/onegov/user/cli.py
- src/onegov/user/models/user.py
- tests/onegov/user/test_models.py
Also ensure that users are logged out when they are modified via the 
CLI.
TYPE: Feature
LINK: SEA-708
> User: Add logout commands to CLI.

- src/onegov/org/forms/user.py
- tests/onegov/org/test_views_user.py
> Org: Logout users when changing their role or state.

- src/onegov/core/request.py
- src/onegov/user/auth/core.py
- tests/onegov/agency/test_views.py
- tests/onegov/user/test_auth.py
> User: Rotate session ID when logging in.

- src/onegov/org/forms/allocation.py
- src/onegov/org/forms/settings.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/organisation.py
- tests/onegov/org/test_views_resources.py
> Org: Adds school holidays setting so that Allocations may skip them.

- src/onegov/translator_directory/security.py
- tests/onegov/translator_directory/test_security.py
> Translator Directory: Fixes permissions for translators.

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/auth.py
> Org: Add spam folder hint on registration.

- src/onegov/org/views/reservation.py
- tests/onegov/org/test_views_ticket.py
> Org: Remembers previous form submission for reservations.

- src/onegov/fsi/cli.py
- src/onegov/translator_directory/cli.py
- src/onegov/translator_directory/forms/login.py
- src/onegov/translator_directory/views/login.py
- src/onegov/user/sync.py
> Translator Directory: Unentangle from FSI.

- src/onegov/election_day/utils/election_compound/list_groups.py
- tests/onegov/election_day/screen_widgets/test_election_compound_widgets.py
> Election Day: Always sort list gropus by voters count.

- src/onegov/election_day/templates/macros.pt
- tests/onegov/election_day/common.py
- tests/onegov/election_day/views/test_views_election_compound.py
- tests/onegov/election_day/views/test_views_notifications.py
> Election Day: Sort elected candidates in election compound mail by name.

- src/onegov/translator_directory/forms/translator.py
- tests/onegov/translator_directory/test_views.py
> Translator Directory: Fixes language certificates not saved.

- src/onegov/translator_directory/collections/translator.py
- src/onegov/translator_directory/forms/translator.py
> Translator Directory: Fixes professional guilds displayed more than one.

- src/onegov/activity/queries/volunteer-report.sql
- src/onegov/feriennet/templates/volunteers.pt
> Feriennet: Show date of birth in volunteers details.

- src/onegov/directory/collections/directory_entry.py
- src/onegov/directory/models/directory.py
- src/onegov/directory/models/directory_entry.py
- src/onegov/directory/upgrade.py
> Directory: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/org/templates/usermanagement.pt
- src/onegov/org/views/usermanagement.py
> Org: Make user roles filter and management forms overwriteable.

- src/onegov/org/mail.py
> Org: Allow ticket mails to be sent to logged in users.

- src/onegov/org/templates/form.pt
> Org: Allow to define form hints and helptexts in the form class.

- src/onegov/form/core.py
> Form: Allow to define long descriptions.

- .vscode/settings.json
> Core: Enables python linting in VSCode.

- src/onegov/pay/models/payment.py
- src/onegov/pay/models/payment_provider.py
- src/onegov/pay/upgrade.py
> Pay: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/file/collection.py
- src/onegov/file/models/file.py
- src/onegov/file/models/fileset.py
- src/onegov/file/upgrade.py
> File: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/form/collection.py
- src/onegov/form/models/definition.py
- src/onegov/form/upgrade.py
> Form: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/ballot/constants.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/election_compound.py
- src/onegov/ballot/models/election/proporz_election.py
- src/onegov/ballot/models/vote/vote.py
- src/onegov/election_day/views/election/data.py
- src/onegov/election_day/views/election_compound/data.py
- src/onegov/election_day/views/vote/data.py
- tests/onegov/ballot/models/test_election.py
- tests/onegov/ballot/models/test_election_compound.py
- tests/onegov/ballot/models/test_proporz_election.py
- tests/onegov/ballot/models/test_vote.py
- tests/onegov/election_day/formats/election/test_internal_majorz.py
- tests/onegov/election_day/formats/election/test_internal_proporz.py
- tests/onegov/election_day/formats/election/test_roundtrips.py
- tests/onegov/election_day/formats/vote/test_internal.py
> Ballot: Get rid of constants.

- src/onegov/election_day/layouts/election.py
- src/onegov/election_day/layouts/election_compound.py
- src/onegov/election_day/layouts/manage.py
- src/onegov/election_day/utils/filenames.py
- src/onegov/election_day/utils/svg_generator.py
- tests/onegov/election_day/layouts/test_election_compound_layout.py
- tests/onegov/election_day/layouts/test_election_layout.py
- tests/onegov/election_day/layouts/test_manage_layouts.py
- tests/onegov/election_day/utils/test_filenames.py
- tests/onegov/election_day/utils/test_svg_generator.py
> Election Day: Always generate SVGs for all locales.

- src/onegov/org/assets/js/reservationcalendar.jsx
> Org: Activates date navigation and week numbers for room reservations

- src/onegov/reservation/models/resource.py
- src/onegov/reservation/upgrade.py
> Reservation: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/people/models/agency.py
- src/onegov/people/models/membership.py
- src/onegov/people/models/person.py
- src/onegov/people/upgrade.py
> People: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/user/models/group.py
- src/onegov/user/models/role_mapping.py
- src/onegov/user/models/user.py
- src/onegov/user/upgrade.py
> User: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/recipient/model.py
- src/onegov/recipient/upgrade.py
> Recipient: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/activity/models/activity.py
- src/onegov/activity/upgrade.py
> Activity: Improve compatibility with SQLAlchemy 1.4.

- tests/onegov/org/test_cronjobs.py
> Org: Fixes warning in cronjob tests.

- docs/api/election_day/format_election_de.md
- docs/api/election_day/format_election_en.md
- docs/api/election_day/format_election_fr.md
- docs/api/election_day/format_election_it.md
- docs/api/election_day/format_election_rm.md
- docs/api/election_day/open_data_de.md
- docs/api/election_day/open_data_en.md
- docs/api/election_day/open_data_fr.md
- docs/api/election_day/open_data_it.md
- docs/api/election_day/open_data_rm.md
- src/onegov/ballot/models/election/candidate.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/proporz_election.py
- src/onegov/ballot/upgrade.py
- src/onegov/election_day/formats/common.py
- src/onegov/election_day/formats/election/internal_majorz.py
- src/onegov/election_day/formats/election/internal_proporz.py
- tests/onegov/ballot/models/test_election.py
- tests/onegov/ballot/models/test_election_compound.py
- tests/onegov/ballot/models/test_proporz_election.py
- tests/onegov/election_day/formats/election/test_internal_majorz.py
- tests/onegov/election_day/formats/election/test_internal_proporz.py
> Election Day: Add gender to candidates.

- docs/api/election_day/format_election_de.md
- docs/api/election_day/format_election_en.md
- docs/api/election_day/format_election_fr.md
- docs/api/election_day/format_election_it.md
- docs/api/election_day/format_election_rm.md
- docs/api/election_day/open_data_de.md
- docs/api/election_day/open_data_en.md
- docs/api/election_day/open_data_fr.md
- docs/api/election_day/open_data_it.md
- docs/api/election_day/open_data_rm.md
- src/onegov/ballot/models/election/candidate.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/proporz_election.py
- src/onegov/ballot/upgrade.py
- src/onegov/election_day/formats/election/internal_majorz.py
- src/onegov/election_day/formats/election/internal_proporz.py
- tests/onegov/ballot/models/test_election.py
- tests/onegov/ballot/models/test_election_compound.py
- tests/onegov/ballot/models/test_proporz_election.py
- tests/onegov/election_day/formats/election/test_internal_majorz.py
- tests/onegov/election_day/formats/election/test_internal_proporz.py
> Election Day: Add year of birth to candidates.

- src/onegov/agency/forms/user_group.py
- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
- src/onegov/agency/templates/macros.pt
- src/onegov/agency/utils.py
- src/onegov/agency/views/agencies.py
- src/onegov/agency/views/people.py
- tests/onegov/agency/test_forms.py
- tests/onegov/agency/test_utils.py
> Agency: Add optional immediate notification for AGN and PER tickets.

- README.md
- setup.py
- src/onegov/org/views/auth.py
- src/onegov/town6/views/auth.py
- src/onegov/user/auth/clients/saml2.py
- src/onegov/user/auth/provider.py
- src/onegov/user/integration.py
- tests/onegov/user/conftest.py
- tests/onegov/user/fixtures/idp.xml
- tests/onegov/user/test_oauth_saml2.py
> User: Adds SAML2 authentication provider

- src/onegov/ballot/models/election/election_compound.py
- src/onegov/ballot/models/mixins.py
- src/onegov/election_day/forms/election_compound.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/macros.pt
- tests/onegov/ballot/conftest.py
- tests/onegov/ballot/models/test_election_compound.py
- tests/onegov/election_day/conftest.py
- tests/onegov/election_day/forms/test_election_compound_form.py
- tests/onegov/election_day/views/test_views.py
> Election Day: Add apportionment PDFs to election compounds.

- src/onegov/core/orm/abstract/adjacency_list.py
- src/onegov/gazette/upgrade.py
- src/onegov/page/upgrade.py
- tests/onegov/agency/test_cli.py
- tests/onegov/core/test_adjacency_list.py
- tests/onegov/page/test_collection.py
- tests/onegov/page/test_polymorphic.py
> Core: Improve compatibility with SQLAlchemy 1.4.

- src/onegov/election_day/layouts/election.py
- src/onegov/election_day/layouts/election_compound.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/macros.pt
> Election Day: Fixes open data download text for votes.

- src/onegov/translator_directory/forms/accreditation.py
- tests/onegov/translator_directory/test_forms.py
- tests/onegov/translator_directory/test_views.py
> Translator Directory: Provide a selection for marital status.

- docs/api/election_day/format_election_it.md
- docs/api/election_day/format_election_rm.md
- docs/api/election_day/format_vote_it.md
- docs/api/election_day/format_vote_rm.md
- docs/api/election_day/open_data_it.md
- docs/api/election_day/open_data_rm.md
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
> Election Day: Update translations.

- setup.py
- src/onegov/form/widgets.py
- src/onegov/quill/widgets.py
- src/onegov/winterthur/daycare.py
- src/onegov/wtfs/fields/hint.py
- tests/onegov/form/test_fields.py
- tests/onegov/form/test_parser.py
> Form: Remove decpracted HTMLString.

- src/onegov/translator_directory/forms/accreditation.py
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- tests/onegov/translator_directory/test_forms.py
- tests/onegov/translator_directory/test_views.py
> Translator Directory: Add optional compensation office confirmation.

- src/onegov/translator_directory/models/translator.py
> Translator Directory: Fixes translators not being indexed.

- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/it_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/views/invoice.py
- src/onegov/feriennet/views/settings.py
> Feriennet: Clarify payment labels.

- tests/onegov/wtfs/test_views_daily_list.py
- tests/onegov/wtfs/test_views_invoice.py
- tests/onegov/wtfs/test_views_municipality.py
- tests/onegov/wtfs/test_views_notification.py
- tests/onegov/wtfs/test_views_principal.py
- tests/onegov/wtfs/test_views_report.py
- tests/onegov/wtfs/test_views_scan_job.py
- tests/onegov/wtfs/test_views_user.py
> WTFS: Make tests less flaky.

- src/onegov/election_day/forms/subscription.py
- src/onegov/form/fields.py
- src/onegov/user/forms/login.py
> Election Day: Optimize forms for screen readers.

- src/onegov/election_day/app.py
- src/onegov/election_day/layouts/default.py
- src/onegov/election_day/templates/archive.pt
- src/onegov/election_day/templates/layout.pt
- src/onegov/election_day/templates/sitemap.pt
- src/onegov/election_day/templates/sitemap.xml.pt
- src/onegov/election_day/theme/styles/election_day.scss
- src/onegov/election_day/views/archive.py
- src/onegov/election_day/views/sitemap.py
- tests/onegov/election_day/common.py
- tests/onegov/election_day/layouts/test_default_layout.py
- tests/onegov/election_day/views/test_views_archive.py
- tests/onegov/election_day/views/test_views_sitemap.py
> Election Day: Add sitemap.

- src/onegov/org/views/directory.py
- tests/onegov/org/test_views_directory.py
> Feriennet: abort if duplicate directory entries are inserted

- src/onegov/search/integration.py
> Search: Resolve ES deprecation warning.

- src/onegov/activity/collections/activity.py
> Activity: Fixes wrong default polymorphic type of activities.

- src/onegov/activity/matching/score.py
> Activity: Improve compatibility with Postgres 14.

- tests/shared/fixtures.py
> Core: Resolve python 3.10 deprecation warning.

- src/onegov/async_http/fetch.py
> Async HTTP: Improve compatibility with python 3.10.

- src/onegov/activity/models/activity.py
- src/onegov/activity/upgrade.py
The signature of array_cat has changed with Postgres 14 from anyarray to anycompatiblearray.
LINK: OGC-83
> Activity: Cleanup unused aggregate function.

- src/onegov/election_day/forms/archive.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/macros.pt
and remove tooltip for short descriptions (placeholders)
> Add hidden text of tooltip for screenreaders

- src/onegov/core/html.py
> Core: Make HTML sanitizer a little bit more robust.

- src/onegov/org/forms/settings.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/organisation.py
- src/onegov/org/templates/layout.pt
- src/onegov/town6/templates/layout.pt
- tests/onegov/org/test_views_settings.py
- tests/onegov/town6/test_views_settings.py
> Org: Add custom CSS.

- src/onegov/pdf/utils.py
- tests/onegov/pdf/test_pdf.py
> Pdf: Allow to remove additional characters from PDF extracts.

- src/onegov/user/forms/login.py
User: Revert back to using a string field instead of an email field for logins.
TYPE: Bugfix
LINK: OGC-591
> Revert back to using a string field instead of an email field for logins.

- tests/onegov/feriennet/test_views.py
Feriennet: Make test less flaky.
TYPE: Bugfix
LINK: OGC-587
> Feriennet: Make test less flaky.

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/payment_providers.pt
- src/onegov/org/views/payment_provider.py
- src/onegov/pay/integration.py
- src/onegov/pay/models/payment_provider.py
- src/onegov/pay/upgrade.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/payment_providers.pt
- tests/onegov/org/test_views_stripe.py
Pay: Allow disabling payment providers.
TYPE: Feature
LINK: PRO-1026
> Pay: Allow disabling payment providers.

- src/onegov/election_day/theme/styles/election_day.scss
Election Day: Center Skip Links
TYPE: Feature
LINK: 558
> Center skip-links

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/settings.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/views/settings.py
Town6: Fix inconsistencies in setting option names
TYPE: Bugfix
LINK: OGC-504
> Ogc 504 settings

- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/homepage.scss
- tests/onegov/town6/test_homepage_widgets.py
Town6: Add icon widget
Links with icons can now be added to the homepage.
TYPE: Feature
LINK: OGC-579
> Ogc 579 icon widget

- src/onegov/election_day/assets/js/error-focus.js
Election Day: Avoid using an empty selector
TYPE: Bugfix
LINK: OGC-561
> Avoid JS Error

- src/onegov/form/integration.py
Form: Harden formcode-fields.
LINK: OGC-616
> Form: Harden formcode-fields.

- src/onegov/org/templates/resource_recipients.pt
- src/onegov/town6/templates/resource_recipients.pt
- tests/onegov/org/test_views_resources.py
Org: Check if resource exists first
TYPE: Bugfix
LINK: OGC-575
> Ogc 575 fix key error

- src/onegov/org/cronjobs.py
- src/onegov/org/views/reservation.py
Org: Check if notification-type keys exist before checking value
TYPE: Bugfix
LINK: OGC-264
> Ogc 264 reservation accept error

- src/onegov/election_day/forms/subscription.py
Election Day: Disable autocomplete on honeypot fields.
TYPE: Bugfix
LINK: OGC-633
> Election Day: Disable autocomplete on honeypot fields.

- src/onegov/translator_directory/templates/macros.pt
Translator Directory: Fixes display of map.
TYPE: Bugfix
LINK: OGC-630
> Translator Directory: Fixes display of map.

- src/onegov/election_day/collections/archived_results.py
- tests/onegov/election_day/collections/test_archived_result_collection.py
Election Day: Order archive descending.
TYPE: Feature
LINK: OGC-627
> Election Day: Order archive descending.

- src/onegov/election_day/app.py
- src/onegov/election_day/assets/js/doubleclick.js
Election Day: Prevent double clicks on forms.
TYPE: Feature
LINK: OGC-629
> Election Day: Prevent double clicks on forms.

- src/onegov/api/models.py
- src/onegov/api/path.py
- tests/onegov/api/test_views.py
Api: Return 404s.
TYPE: Feature
LINK: OGC-636
> Api: Return 404s.

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/models/notification.py
- src/onegov/election_day/templates/manage/trigger_notification.pt
- src/onegov/election_day/templates/manage/trigger_notifications.pt
- src/onegov/election_day/views/manage/election_compounds.py
- src/onegov/election_day/views/manage/elections.py
- src/onegov/election_day/views/manage/votes.py
- tests/onegov/election_day/models/test_notification.py
Election Day: Improve notification form hints.
TYPE: Feature
LINK: OGC-628
> Election Day: Improve notification form hints.

- src/onegov/feriennet/theme/styles/feriennet.scss
- src/onegov/org/assets/js/many.jsx
- src/onegov/org/forms/settings.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/layout.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/org/views/settings.py
- src/onegov/town6/assets/js/many.jsx
- src/onegov/town6/templates/layout.pt
- src/onegov/town6/theme/styles/header.scss
- src/onegov/town6/theme/styles/org-settings.scss
- tests/onegov/org/test_views.py
- tests/onegov/town6/test_views.py
Org: Added header links option
TYPE: Feature
LINK: OGC-581
> Ogc 581 link subsites

- src/onegov/election_day/assets/js/error-focus.js
- src/onegov/election_day/forms/subscription.py
- src/onegov/election_day/templates/archive.pt
- src/onegov/election_day/templates/archive_search.pt
- src/onegov/election_day/templates/layout.pt
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/templates/sitemap.pt
Election Day: Fix HTML Errors
TYPE: Bugfix
LINK: OGC-562
> Ogc 562 html errors

- src/onegov/election_day/theme/styles/election_day.scss
Election day: Color contrasts
TYPE: Feature
LINK: OGC-556
> Ogc 556 color contrast

- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/theme/styles/election_day.scss
Election Day: Fix broken up definition list
TYPE: Bugfix
LINK: OGC-552
> Fix broken up definition list

- src/onegov/people/models/agency.py
Agency: Delete reference on non-existant address fields
TYPE: Bugfix
LINK: OGC-645
> Remove address columns from model

- src/onegov/town6/templates/topic.pt
Town6: Display contact information correctly
TYPE: Bugfix
LINK: OGC-648
> Display contact information correctly

- src/onegov/election_day/static/images/terms_by.svg
Election Day: Add white background to terms of usage image
TYPE: Feature
LINK: OGC-538
> Add white background to image

- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
- src/onegov/agency/templates/person.pt
- src/onegov/org/theme/styles/org.scss
Agency: Add information for changes form
TYPE: Feature
LINK: OGC-650
> Add information for changes form

- src/onegov/gis/assets/js/geo-admin-aerial.js
- src/onegov/gis/assets/js/geo-admin.js
- src/onegov/gis/integration.py
- src/onegov/org/app.py
- src/onegov/org/forms/settings.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
Org: Add Swisstopo and aerial Map
TYPE: Feature
LINK: OGC-632
> Integrate swisstopo map and aerial map

- src/onegov/core/i18n.py
- src/onegov/election_day/layouts/default.py
- src/onegov/election_day/layouts/mail.py
- src/onegov/election_day/path.py
- src/onegov/org/layout.py
- src/onegov/swissvotes/layouts/default.py
- src/onegov/swissvotes/path.py
- tests/onegov/election_day/common.py
- tests/onegov/swissvotes/test_layouts.py
Core: Use signed redirects for locales.
TYPE: Feature
LINK: OGC-671
> Core: Use signed redirects for locales.

- src/onegov/core/utils.py
- src/onegov/town6/templates/topic.pt
- src/onegov/town6/theme/styles/panels.scss
- tests/onegov/core/test_utils.py
Town 6: Display Contact Info
TYPE: Bugfix
LINK: OGC-648
> Page contact

- src/onegov/gis/assets/js/geo-bs.js
- src/onegov/gis/assets/js/leaflet-integration.js
- tests/onegov/org/test_browser.py
Org: Link for map-bs if map-bs is selected in settings
TYPE: Feature
LINK: OGC-634
> Add option for opening map in new tab

- src/onegov/org/assets/js/redactor.js
Town6: Add an offset for the toolbar
TYPE: Bugfix
LINK: OGC-672
> Ogc 672 redactor toolbar offset

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/org.scss
Town6: Add a cancel link on forms
TYPE: Feature
LINK: OGC-582
> Ogc 582 cancel link

- src/onegov/town6/templates/event.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/reservation_confirmation.pt
- src/onegov/town6/templates/submission.pt
Town6: Remove button class from edit link
TYPE: Feature
LINK: OGC-673
> Ogc 673 buttons

- src/onegov/election_day/assets/js/tablesaw.jquery.js
Accessibility: Labels for the toggle feature for switching table presentation / alignment of the table. 
ogc-545: Increase verbosity in tablesaw columns labels
Accessibility: Labels for the toggle feature for switching table presentation / alignment of the table. 
TYPE: Bugfix
LINK: OGC-545
> Increase verbosity in tablesaw columns labels

- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/election_compound.py
- src/onegov/election_day/forms/election.py
- src/onegov/election_day/forms/election_compound.py
- src/onegov/election_day/layouts/election_compound.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/utils/d3_renderer.py
- src/onegov/election_day/utils/election/__init__.py
- src/onegov/election_day/utils/parties/__init__.py
- src/onegov/election_day/utils/parties/parties.py
- src/onegov/election_day/utils/pdf_generator.py
- src/onegov/election_day/views/election_compound/seat_allocation.py
- tests/onegov/election_day/forms/test_election_compound_form.py
- tests/onegov/election_day/forms/test_election_form.py
- tests/onegov/election_day/layouts/test_election_compound_layout.py
- tests/onegov/election_day/utils/test_election_compound_utils.py
- tests/onegov/election_day/utils/test_election_utils.py
- tests/onegov/election_day/utils/test_svg_generator.py
Election Day: Add an option to shop party strength diagrams horizontally.
TYPE: Feature
LINK: OGC-708
> Ogc 708 horizontal party strength

- src/onegov/form/parser/form.py
- tests/onegov/form/test_parser.py
OGC-730: Fix Formcode for dependent fields with price
TYPE: BugFix
LINK: OGC-730
> Form: Fix Formcode for dependent fields with price

- src/onegov/town6/theme/styles/org.scss
Town6: Align table header to the left
TYPE: Bugfix
LINK: OGC-737
> Make table headers align left

- src/onegov/election_day/cli.py
Election Day: Remove party domain data migration command.
LINK: OGC-709
> Election Day: Remove party domain data migration command.

- src/onegov/election_day/templates/election/candidates.pt
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/utils/election/candidates.py
- src/onegov/election_day/views/election/candidates.py
- tests/onegov/election_day/screen_widgets/test_election_widgets.py
- tests/onegov/election_day/utils/test_election_utils.py
- tests/onegov/election_day/views/test_views_election.py
Election Day: Add entity filter to candidates views.
TYPE: Feature
LINK: OGC-706
> Election Day: Add entity filter to candidates views.

- src/onegov/ballot/models/election/election.py
- src/onegov/election_day/forms/election.py
- src/onegov/election_day/forms/election_compound.py
- src/onegov/election_day/layouts/election.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/utils/pdf_generator.py
- tests/onegov/election_day/common.py
- tests/onegov/election_day/forms/test_election_form.py
- tests/onegov/election_day/layouts/test_election_layout.py
- tests/onegov/election_day/utils/test_pdf_generator.py
Election Day: Add party views configuration options to elections.
TYPE: Feature
LINK: OGC-765
> Election Day: Add party views configuration options to elections.

- src/onegov/directory/types/directory_configuration.py
Directory: Fix directory error
TYPE: Bugfix
LINK: OGC-783
> Ogc 783 add new directory error

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/events.scss
- src/onegov/town6/theme/styles/homepage.scss
Town6: Mobile optimizations
TYPE: Feature
LINK: OGC-756
> Ogc 756 optimizations town6

- src/onegov/town6/templates/topic.pt
- src/onegov/town6/theme/styles/org.scss
Town6: Add lead in lists on page
TYPE: Bugfix
LINK: OGC-801
> Add and style lead

- src/onegov/ballot/models/election/election.py
- src/onegov/election_day/forms/election.py
- src/onegov/election_day/templates/election/party_strengths.pt
- src/onegov/election_day/utils/parties/parties.py
- tests/onegov/election_day/forms/test_election_form.py
- tests/onegov/election_day/views/test_views_election.py
Election Day: Enable voters counts for proporz elections.
TYPE: Feature
LINK: OGC-353
> Election Day: Enable voters counts for proporz elections.

- src/onegov/town6/templates/news.pt
Town6: Fix sidebar news
TYPE: Bugfix
LINK: OGC-811
> Fix sidebar of news overview

- src/onegov/directory/types/directory_configuration.py
Directory: Fix key format problem
TYPE: Bugfix
LINK: OGC-814
> Fix key format problem

- src/onegov/town6/templates/news.pt
Town6: Hashtags filter in sidebar existence check
TYPE: Feature
LINK: OGC-808
> Town6: Show Hashtags and year only if they exist.

- src/onegov/town6/theme/styles/header.scss
Town6: Fix search bar suggestions
TYPE: Bugfix
LINK: OGC-803
> Ogc 803 search bar

- src/onegov/town6/app.py
- src/onegov/town6/assets/js/homepage_video.js
- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
Town6: Random Video
Multiple Videos can now be added and one will randomly be chosen
TYPE: Feature
LINK: OGC-819
> Ogc 819 random video

- src/onegov/core/utils.py
- src/onegov/town6/theme/styles/panels.scss
- tests/onegov/core/test_utils.py
- tests/onegov/org/test_extensions.py
Town6: Fix contact panel html
Use paragraphs and lists instead of only lists.
TYPE: Bugfix
LINK: OGC-815
> Ogc 815 contact box

- src/onegov/pay/models/payment_providers/stripe.py
Town6: Credit card button styling
TYPE: Bugfix
LINK: OGC-835
> Add button class for styling

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/occurrence.pt
- src/onegov/town6/theme/styles/footer.scss
- src/onegov/town6/theme/styles/forms.scss
- src/onegov/town6/theme/styles/homepage.scss
- src/onegov/town6/theme/styles/panels.scss
Town6: Small design adjustments
TYPE: Feature
> Small design adjustments

- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- tests/onegov/town6/test_views_homepage.py
Town6: Rename more news button
TYPE: Feature
LINK: OGC-820
> Ogc 820 more news button

- src/onegov/town6/templates/imagesets.pt
- src/onegov/town6/theme/styles/image-grid.scss
- src/onegov/town6/theme/styles/org.scss
Town6: Style overview of image sets
TYPE: Feature
LINK: OGC-816
> Update imagesets.pt, image-grid.scss, and org.scss

- src/onegov/town6/theme/town_theme.py
Town6: Fix tags field styling
TYPE: Bugfix
LINK: OGC-617
> Load tags.scss

- src/onegov/town6/theme/styles/homepage.scss
Town6: Don't break title beneath icon
TYPE: Bugfix
LINK: OGC-843
> Don't break beneath icon

- src/onegov/town6/theme/styles/upload.scss
Town6: Fix upload image style error
TYPE: Bugfix
LINK: OGC-621
> Fix style error

- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/occurrences.pt
- src/onegov/town6/theme/styles/events.scss
- src/onegov/town6/theme/styles/forms.scss
- src/onegov/town6/theme/styles/homepage.scss
- src/onegov/town6/theme/styles/org.scss
- src/onegov/town6/theme/styles/widgets.scss
Town6: Design Adjustments
TYPE: Feature
> More design adjustments

- src/onegov/user/cli.py
- tests/onegov/user/test_cli.py
User: Add transfer-yubikey CLI command.
TYPE: Feature
LINK: OGC-871
> User: Add transfer-yubikey CLI command.

- .buildkite/test
Core: Add missing dependencies for google-chrome-stable.
TYPE: Bugfix
> Core: Add missing dependencies for google-chrome-stable.

- src/onegov/election_day/static/municipalities/2022/ai.json
- src/onegov/election_day/static/municipalities/2022/ti.json
- src/onegov/election_day/static/municipalities/2023/ag.json
- src/onegov/election_day/static/municipalities/2023/ai.json
- src/onegov/election_day/static/municipalities/2023/be.json
- src/onegov/election_day/static/municipalities/2023/ju.json
- src/onegov/election_day/static/municipalities/2023/sg.json
- src/onegov/election_day/static/municipalities/2023/ti.json
- src/onegov/election_day/static/municipalities/2023/zh.json
Election Day: Add historicized municipality data for 2023.
TYPE: Feature
LINK: OGC-879
> Election Day: Add historicized municipality data for 2023.

- src/onegov/ballot/models/party_result/mixins.py
Election Day: Fix party result export.
TYPE: Bugfix
> Election Day: Fix party result export.

- src/onegov/town6/templates/macros.pt
Town 6: Fix translation
TYPE: Bugfix
LINK: OGC-878
> Fix translation

- src/onegov/org/assets/js/all_blank.js
Town6: Open all files in new tab if set to true
TYPE: Bugfix
> Use function on all pages

- src/onegov/town6/theme/styles/fullcalendar.scss
Town6: Calendar Buttons
TYPE: Bugfix
LINK: OGC-876
> Buttons on calendar

- src/onegov/town6/templates/layout.pt
Town6: Search-Button
TYPE: Bugfix
LINK: OGC-842
> Mobile search-button style

- src/onegov/feriennet/templates/volunteers.pt
Feriennet: Fix order of occasions in volunteer overview
TYPE: Bugfix
LINK: OGC-1044
> Sort occasions in activity

- src/onegov/core/collection.py
Feriennet: Increase amount of activities shown per page
TYPE: Feature
LINK: PRO-1013
> Increase amount of activities shown per page

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
Town6: Fixes translations not being applied
TYPE: Bugfix
LINK: OGC-926
swissvotes)
> Town6: Fixes translations not being applied.

- src/onegov/feriennet/sponsors/sponsors.yml
Feriennet: Text for Banners
TYPE: Feature
LINK: PRO-880
> Add text to sponsors

- src/onegov/feriennet/sponsors/sponsors.yml
Feriennet: Remove CS Logo
TYPE: Feature
LINK: PRO-1131
> Remove CS Logo

- src/onegov/org/views/editor.py
Org: Display edit bar with delete function for links.
This makes deleting links more accessible, which
was in fact already possible.
TYPE: Feature
LINK: OGC-739
> Org: Display edit bar with delete function for links.

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/org.scss
Org: Fixes rendering of external links in search results
TYPE: Bugfix
LINK: OGC-959
> Org: Fixes rendering of external links in search results

- src/onegov/election_day/utils/parties/parties.py
Election Day: Hide empty party strength lines.
TYPE: Bugfix
LINK: OGC-941
> Election Day: Hide empty party strength lines.

- src/onegov/election_day/formats/common.py
- tests/onegov/election_day/formats/election/test_internal_compound.py
- tests/onegov/election_day/formats/election/test_internal_proporz.py
- tests/onegov/election_day/formats/election/test_parties.py
- tests/onegov/election_day/formats/election/test_wabsti_proporz.py
Election Day: Allow alphanumeric list and party IDs.
TYPE: Feature
LINK: OGC-936
> Election Day: Allow alphanumeric list and party IDs.

- src/onegov/ballot/models/party_result/mixins.py
- src/onegov/election_day/utils/parties/parties.py
- tests/onegov/ballot/models/test_election_compound.py
- tests/onegov/ballot/models/test_election_compound_part.py
- tests/onegov/ballot/models/test_proporz_election.py
Election Day: Add historical colors for party results.
TYPE: Feature
LINK: OGC-931
> Election Day: Add historical colors for party results.

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/utils/parties/parties.py
- tests/onegov/election_day/utils/test_election_compound_utils.py
- tests/onegov/election_day/utils/test_election_utils.py
- tests/onegov/election_day/views/test_views_election.py
- tests/onegov/election_day/views/test_views_election_compound.py
Election Day: Standardize panachage diagrams.
TYPE: Bugfix
LINK: OGC-906
> Election Day: Standardize panachage diagrams.

- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- tests/onegov/feriennet/test_views.py
Feriennet: Text Adjustments
TYPE: Bugfix
LINK: PRO-1046
> Pro 1046 text adjustments

- src/onegov/feriennet/forms/activity.py
- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/it_CH/LC_MESSAGES/onegov.feriennet.po
Feriennet: Add new category
TYPE: Feature
LINK: PRO-1150
> Pro 1150 new categories

- src/onegov/town6/templates/occurrences.pt
- src/onegov/town6/theme/styles/print.scss
Town6: Rename Side Panel
TYPE: Bugfix
> Rename side panel

- setup.cfg
- src/onegov/core/orm/sql.py
Core: Add compatibility with pglast 5.
TYPE: Feature
LINK: OGC-992
> Core: Add compatibility with pglast 5.

- src/onegov/websockets/assets/js/websockets.js
- src/onegov/websockets/cli.py
- src/onegov/websockets/client.py
- src/onegov/websockets/integration.py
- src/onegov/websockets/server.py
- tests/onegov/websockets/test_browser.py
- tests/onegov/websockets/test_cli.py
- tests/onegov/websockets/test_client_server.py
- tests/onegov/websockets/test_integration.py
Websockets: Add channels.
TYPE: Feature
LINK: OGC-935
> Websockets: Add channels.

- src/onegov/core/utils.py
- src/onegov/feriennet/theme/styles/feriennet.scss
- src/onegov/org/models/extensions.py
- src/onegov/org/theme/styles/org.scss
- tests/onegov/org/test_extensions.py
Org: Side panel with title
TYPE: Bugfix
LINK: PRO-1142
> Pro 1142 side panel

- src/onegov/feriennet/templates/macros.pt
Feriennet: New Google Analytics Code
TYPE: Feature
LINK: PRO-1071
> Replace google analytics code

- src/onegov/feriennet/templates/bookings.pt
- src/onegov/feriennet/views/booking.py
Feriennet: Show names of other children in bookings
TYPE: Feature
LINK: PRO-1090
> Pro 1090 show children names

- src/onegov/election_day/app.py
- src/onegov/election_day/assets/js/notifications.js
- src/onegov/election_day/layouts/detail.py
- src/onegov/election_day/templates/layout.pt
- src/onegov/websockets/assets/js/websockets.js
- tests/onegov/websockets/test_browser.py
Election Day: Avoid opening unneccessary websockets.
TYPE: Bugfix
LINK: OGC-991
> Election Day: Avoid opening unneccessary websockets.

- src/onegov/election_day/layouts/manage.py
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/templates/upload_election.pt
- src/onegov/election_day/templates/upload_vote.pt
- tests/onegov/election_day/layouts/test_manage_layouts.py
- tests/onegov/election_day/models/test_principal.py
- tests/onegov/election_day/views/test_views_notifications.py
- tests/onegov/election_day/views/test_views_upload_vote.py
Election Day: Always enable notifications menu.
TYPE: Bugfix
LINK: OGC-991
> Election Day: Always enable notifications menu.

- src/onegov/core/utils.py
- src/onegov/town6/theme/styles/panels.scss
Town6: Fix styling problem in town6
TYPE: Bugfix
LINK: OGC-1001
> Fix styling problem in town6

- src/onegov/feriennet/boardlets.py
- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/it_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/org/models/dashboard.py
- src/onegov/org/templates/dashboard.pt
- src/onegov/org/theme/styles/org.scss
Feriennet: Dashboard improvements
TYPE: Feature
LINK: OGC-1119
> Pro 1118 dashboard

- src/onegov/feriennet/views/notification_template.py
- tests/onegov/feriennet/test_views.py
Feriennet: Send mail to user if not in recipient list
TYPE: Bugfix
LINK: PRO-1021
> Send mail to user if not in recipient list

- src/onegov/org/models/organisation.py
- src/onegov/town6/templates/macros.pt
Town6: Reduce events to 3 columns
TYPE: Feature
LINK: OGC-989
> Reduce to 3 columns

- src/onegov/onboarding/forms/town.py
- src/onegov/onboarding/locale/de_CH/LC_MESSAGES/onegov.onboarding.po
- src/onegov/onboarding/models/town_assistant.py
- src/onegov/onboarding/theme/styles/onboarding.scss
- tests/onegov/onboarding/test_views.py
Onboarding: Extend form with more fields.
TYPE: Feature
LINK: OGC-601
> Onboarding: Extend form with more fields.

- src/onegov/feriennet/exports/const.py
- tests/onegov/feriennet/test_browser.py
feriennet: Add missing volunteer state 'contacted' to make exportable
TYPE: Bugfix
LINK: pro-1158
> Adding state 'contacted' as it is used in the volunteer class

- setup.cfg
Core: Pin Watchdog
TYPE: Bugfix
> Pin watchdog

- src/onegov/feriennet/templates/macros.pt
Feriennet: New Google Analytics Code
TYPE: Feature
LINK: PRO-1155
> New google tag manager code

- setup.cfg
- src/onegov/core/templates.py
Core: Adds compatibility with latest chameleon release.
TYPE: Feature
> Core: Adds compatibility with latest chameleon release.

- tests/onegov/websockets/test_browser.py
- tests/shared/browser.py
Websockets: Fix flaky test.
TYPE: Bugfix
> Websockets: Fix flaky test.

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/extensions.py
- tests/onegov/org/test_views_forms.py
Org: Add default function for editor
TYPE: Feature
LINK:  ogc-985
> Org: Add default function for editor.

- src/onegov/election_day/templates/layout.pt
- src/onegov/election_day/templates/macros.pt
- src/onegov/election_day/theme/styles/election_day.scss
Election Day: Improve accessability.
TYPE: Feature
LINK: OGC-1022
> Election Day: Improve accessability.

- src/onegov/feriennet/exports/base.py
- src/onegov/feriennet/forms/billing.py
- src/onegov/feriennet/layout.py
- src/onegov/feriennet/locale/de_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/fr_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/locale/it_CH/LC_MESSAGES/onegov.feriennet.po
- src/onegov/feriennet/theme/styles/feriennet.scss
- src/onegov/feriennet/views/billing.py
- tests/onegov/feriennet/test_export.py
- tests/onegov/feriennet/test_views.py
Feriennet: Add option to mark invoice as paid with specific date
TYPE: Feature
LINK: PRO-1115
> Pro 1115 mark paid with date

- src/onegov/org/templates/directory.pt
- src/onegov/town6/templates/directory_entry.pt
- tests/onegov/org/test_views_directory.py
Town6: Only show "submit changes" if activated
TYPE: Bugfix
LINK: OGC-955
> Only show "submit changes" if activated

- src/onegov/election_day/formats/election/internal_proporz.py
Ballot: Speed up import of proporz elections.
TYPE: Bugfix
> Ballot: Speed up import of proporz elections.

- setup.cfg
- tests/shared/fixtures.py
Core: Unpin pytest localserver.
TYPE: Feature
LINK: OGC-444
> Ogc 444 pytest localserver

- src/onegov/town6/templates/directory.pt
- src/onegov/town6/theme/styles/directories.scss
Town6: Map view
Reposition map on directory overview.
TYPE: Feature
LINK: OGC-996
> Change map position

- setup.cfg
- src/onegov/org/forms/resource.py
- src/onegov/org/views/resource.py
- tests/onegov/org/test_views_resources.py
Org: Extends allocation cleanup view with a weekday filter
TYPE: Feature
LINK: OGC-1032
> Org: Extends allocation cleanup view with a weekday filter

- src/onegov/feriennet/templates/bookings.pt
- src/onegov/feriennet/views/booking.py
Feriennet: Only show attendees with booking for occasion
TYPE: Bugfix
LINK: PRO-1159
> Only show attendees with booking for occasion

- src/onegov/org/models/search.py
- src/onegov/org/templates/search.pt
- src/onegov/town6/templates/search.pt
- tests/onegov/org/test_views_search.py
Org: Prioritize Events in search and sort chronologically.
TYPE: Feature
LINK: OGC-908
> Org: Prioritize Events in search, and sort chronologically.

- src/onegov/town6/templates/occurrences.pt
- src/onegov/town6/theme/styles/forms.scss
Town6: Small Fixes
TYPE: Bugfix
> Ogc small fixes

- src/onegov/org/forms/directory.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/directory.py
- src/onegov/town6/templates/directory.pt
- src/onegov/town6/theme/styles/directories.scss
Org: Add more options to "further information" on directories
TYPE: Feature
LINK: OGC-928
> Ogc 928 more info

- src/onegov/event/models/event.py
- src/onegov/org/forms/event.py
- src/onegov/org/templates/occurrence.pt
- src/onegov/org/views/occurrence.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/occurrence.pt
Town6: External event url
TYPE: Feature
LINK: OGC-746
> Ogc 746 external event url

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/mail_daily_resource_usage_overview.pt
- src/onegov/org/templates/mail_daily_ticket_statistics.pt
- src/onegov/org/templates/mail_macros.pt
- src/onegov/org/templates/mail_monthly_ticket_statistics.pt
- src/onegov/org/templates/mail_new_reservation_notification.pt
- src/onegov/org/templates/mail_weekly_ticket_statistics.pt
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/mail_daily_ticket_statistics.pt
- src/onegov/town6/templates/mail_macros.pt
- src/onegov/town6/templates/mail_new_reservation_notification.pt
- tests/onegov/org/test_cronjobs.py
Town6: Remove "Onegov Cloud Team" in mail-footer
TYPE: Feature
LINK: OGC-1167
> Ogc1067 onegov cloud team

- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/homepage.scss
- tests/onegov/town6/test_homepage_widgets.py
Town6: Add option for a testimonial slider
TYPE: Feature
LINK: OGC-761
> Testimonial Slider

- src/onegov/form/parser/core.py
> Form: Add security hint for yaml loading.

- src/onegov/core/utils.py
> Core: Validate URL used in PostThread.

- src/onegov/election_day/utils/d3_renderer.py
- src/onegov/event/cli.py
- src/onegov/gazette/utils/sogc_importer.py
- src/onegov/gis/utils.py
- src/onegov/org/cli.py
- src/onegov/pay/models/payment_providers/stripe.py
- src/onegov/pdf/signature.py
- src/onegov/swissvotes/external_resources/posters.py
- tests/onegov/gazette/test_utils.py
> Core: Add requests timeouts.

- src/onegov/people/models/person.py
Org: Minor code improvement
TYPE: Improvement
LINK: OGC-1076
> Remove param for split

- src/onegov/swissvotes/views/page.py
> Swissvotes: Fixes button text for adding pages.

- src/onegov/election_day/views/subscription.py
- src/onegov/org/upgrade.py
- src/onegov/pdf/__init__.py
- src/onegov/pdf/utils.py
- src/onegov/server/__init__.py
- src/onegov/server/cli.py
- src/onegov/websockets/server.py
> Core: Log execeptions instead of silenty ignoring them.

- src/onegov/activity/utils.py
- src/onegov/core/crypto/random.py
- src/onegov/core/framework.py
- src/onegov/org/elements.py
- src/onegov/quill/widgets.py
- src/onegov/ticket/collection.py
> Core: Use either secrets for random or indicate non-cryptographic usage.

- src/onegov/core/framework.py
- src/onegov/feriennet/models/notification_template.py
- src/onegov/file/integration.py
- src/onegov/org/forms/settings.py
- src/onegov/user/upgrade.py
- src/onegov/websockets/integration.py
- src/onegov/websockets/server.py
> Core: Indicate safe hardcoded password values.

- src/onegov/org/templates/macros.pt
- src/onegov/translator_directory/templates/translators.pt
- src/onegov/translator_directory/theme/styles/translator_directory.scss
Translator directory: Display the forms in a two-column layout
TYPE: Feature
LINK: OGC-1000
> Translator directory: Display the forms in a two-column layout

- .pre-commit-config.yaml
- src/onegov/winterthur/app.py
Winterthur: Include events in iframe resizing
TYPE: Feature
LINK: OGC-1047
> Activate iframe-resizer for events

- src/onegov/feriennet/boardlets.py
Feriennet: Fix number of unlucky atteendees on dashboard
TYPE: Bugfix
LINK: PRO-1118
> Fix number of unlucky atteendees

- src/onegov/feriennet/exports/booking.py
- src/onegov/feriennet/layout.py
- src/onegov/feriennet/views/billing.py
- tests/onegov/feriennet/test_export.py
Feriennet: Add political municipality fields to wishlist bookings export
TYPE: Feature
LINK: PRO-1181
> Pro 1181 export

- src/onegov/org/views/directory.py
Org: Fix exception in hidden directory entries for logged out users.
This fixes ONEGOV-CLOUD-48W
TYPE: Bugfix
LINK: OGC-1124
> Org: Fix exception in hidden directory entries for logged out users.

- pyproject.toml
- setup.cfg
- src/onegov/core/orm/__init__.py
- src/onegov/core/orm/abstract/adjacency_list.py
- src/onegov/core/orm/abstract/associable.py
- src/onegov/core/orm/cache.py
- src/onegov/core/orm/debug.py
- src/onegov/core/orm/func.py
- src/onegov/core/orm/mixins/content.py
- src/onegov/core/orm/mixins/publication.py
- src/onegov/core/orm/mixins/timestamp.py
- src/onegov/core/orm/session_manager.py
- src/onegov/core/orm/sql.py
- src/onegov/core/orm/types/json_type.py
- src/onegov/core/orm/types/lowercase_text_type.py
- src/onegov/core/orm/types/utcdatetime_type.py
- src/onegov/core/orm/types/uuid_type.py
- src/onegov/core/orm/utils.py
mypy: Adds stubs for onegov.core.orm
> mypy: Adds stubs for onegov.core.orm

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
org: Adding missing translations
TYPE: Bugfix
LINK: ogc-1112
> Adding missing translations for org

- pyproject.toml
- src/onegov/core/crypto/password.py
- src/onegov/core/crypto/random.py
- src/onegov/core/crypto/token.py
- src/onegov/core/security/identity_policy.py
- src/onegov/core/security/permissions.py
- src/onegov/core/security/roles.py
- src/onegov/core/security/rules.py
mypy: Adds type annotations to onegov.core.crypto/onegov.core.security
> mypy: Adds type annotations to onegov.core.crypto/onegov.core.security

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/directory.py
- tests/onegov/org/test_views_directory.py
- tests/shared/utils.py
Org: Set the .zip extension for directory export.
TYPE: Bugfix
LINK: OGC-1087
> Org: Set the .zip extension for directory export.

- pyproject.toml
- setup.cfg
- src/onegov/core/cache.py
mypy: Adds type annotations for onegov.core.cache
> mypy: Adds type annotations for onegov.core.cache

- src/onegov/landsgemeinde/layouts/assembly.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/templates/states.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- src/onegov/landsgemeinde/utils.py
- src/onegov/landsgemeinde/views/agenda.py
- src/onegov/landsgemeinde/views/assembly.py
- src/onegov/landsgemeinde/views/votum.py
- tests/onegov/landsgemeinde/test_utils.py
Landsgemeinde: 
Landsgemeinde: Improve state management.
TYPE: Feature
LINK: OGC-638
> Ogc 638 landsgemeinde

- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- src/onegov/town6/assets/js/common.js
> Landsgemeinde: Add reveal to vota.

- src/onegov/fsi/collections/audit.py
- src/onegov/fsi/layouts/audit.py
- src/onegov/fsi/pdf.py
- src/onegov/fsi/views/audit.py
FSI: Change column in audit pdf
TYPE: Feature
LINK: OGC-1036
> Ogc 1036 pdf changes

- pyproject.toml
- src/onegov/core/browser_session.py
- src/onegov/core/cache.py
mypy: Adds type annotations for onegov.core.browser_session
> mypy: Adds type annotations for onegov.core.browser_session

- pyproject.toml
- src/onegov/activity/models/invoice_reference.py
- src/onegov/core/crypto/random.py
- src/onegov/core/datamanager.py
- src/onegov/core/i18n.py
- src/onegov/core/layout.py
- src/onegov/core/request.py
- src/onegov/core/utils.py
- src/onegov/directory/archive.py
- src/onegov/feriennet/templates/macros.pt
- src/onegov/user/auth/provider.py
- tests/onegov/core/test_layout.py
- tests/onegov/core/test_utils.py
- tests/onegov/org/test_initial_content.py
- tests/onegov/org/test_models.py
mypy: Adds type annotations for onegov.core.utils/datamanager
> mypy: Adds type annotations for onegov.core.utils/datamanager

- src/onegov/feriennet/exports/base.py
Feriennet: Fix booking time in export
TYPE: Bugfix
LINK: PRO-1189
> Fix booking time before export

- src/onegov/feriennet/views/booking.py
- src/onegov/feriennet/views/occasion.py
Feriennet: Only send mails if booking start date is in the past or today
TYPE: Bugfix
LINK: PRO-1188
> Only send mails if booking start date is in the past or today

- src/onegov/election_day/app.py
- src/onegov/election_day/assets/js/screen.js
- src/onegov/election_day/templates/screen.pt
- src/onegov/election_day/views/screen.py
Election Day: Use an asset for screens.
TYPE: Feature
LINK: OGC-867
> Election Day: Use an asset for screens.

- src/onegov/swissvotes/app.py
> Swissvotes: Tighten CSP.

- src/onegov/gazette/app.py
- src/onegov/gazette/assets/js/common.js
- src/onegov/gazette/templates/preview.pt
> Gazette: Move preview code to assets and tighten CSP.

- src/onegov/feriennet/templates/mail_booking_accepted.pt
- src/onegov/feriennet/templates/mail_booking_canceled.pt
- src/onegov/feriennet/views/booking.py
- src/onegov/feriennet/views/occasion.py
Feriennet: Show all occasion dates in info-mails
TYPE: Bugfix
LINK: PRO-1183
> Display all dates on E-Mail

- src/onegov/election_day/utils/d3_renderer.py
> Election Day: Avoid sending single quotation marks to the d3-renderer.

- src/onegov/ballot/models/vote/ballot.py
- src/onegov/ballot/upgrade.py
- src/onegov/election_day/forms/vote.py
- tests/onegov/election_day/forms/test_vote_form.py
> Election Day: Add external IDs to ballots.

- src/onegov/fsi/theme/styles/fsi.scss
- src/onegov/org/templates/login.pt
FSI: Hide OGC login form
TYPE: Feature
LINK: ogc-1111
> Hide ogc-login on fsi-page

- src/onegov/election_day/app.py
- src/onegov/election_day/views/screen.py
- tests/onegov/election_day/views/test_views.py
> Election Day: Cache HEAD requests.

- src/onegov/org/templates/macros.pt
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/macros.pt
Org/Town6: Improve file download design.
TYPE: Feature
LINK: OGC-1122
button + icons.
> Org/Town6: Improve file download design.

- pyproject.toml
- src/onegov/core/cli/commands.py
- src/onegov/core/cli/core.py
- src/onegov/core/converters.py
- src/onegov/core/cronjobs.py
- src/onegov/core/csv.py
- src/onegov/core/custom/custom_json.py
- src/onegov/core/elements.py
- src/onegov/core/errors.py
- src/onegov/core/filestorage.py
- src/onegov/core/filters.py
- src/onegov/core/html.py
- src/onegov/core/html_diff.py
- src/onegov/core/i18n.py
- src/onegov/core/layout.py
- src/onegov/core/mail_processor/core.py
- src/onegov/core/mail_processor/postmark.py
- src/onegov/core/mail_processor/smtp.py
- src/onegov/core/markdown.py
- src/onegov/core/metadata.py
- src/onegov/core/redirect.py
- src/onegov/core/security/rules.py
- src/onegov/core/static.py
- src/onegov/core/templates.py
- src/onegov/core/theme.py
- src/onegov/core/types.py
- src/onegov/core/upgrade.py
- src/onegov/core/upgrades.py
- src/onegov/core/widgets.py
mypy: Adds type annotations for the rest of onegov.core
> mypy: Adds type annotations for the rest of onegov.core

- src/onegov/landsgemeinde/app.py
- src/onegov/landsgemeinde/utils.py
- tests/onegov/landsgemeinde/test_views.py
> Landsgemeinde: Add cache for ticker.

- src/onegov/landsgemeinde/forms/agenda.py
- src/onegov/landsgemeinde/forms/votum.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/models/agenda.py
- src/onegov/landsgemeinde/models/votum.py
- src/onegov/landsgemeinde/templates/agenda_item.pt
- src/onegov/landsgemeinde/templates/macros.pt
> Landsgemeinde: Add video timestamps.

- src/onegov/election_day/app.py
- tests/onegov/election_day/views/test_views.py
> Election Day: Remove cache busting by cache control header.

- src/onegov/landsgemeinde/layouts/assembly.py
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
> Landsgemeinde: Add link to ticker.

- pyproject.toml
- src/onegov/core/cli/core.py
- src/onegov/core/utils.py
- src/onegov/user/__init__.py
- src/onegov/user/auth/clients/__init__.py
- src/onegov/user/auth/clients/kerberos.py
- src/onegov/user/auth/clients/ldap.py
- src/onegov/user/auth/clients/msal.py
- src/onegov/user/auth/clients/saml2.py
- src/onegov/user/auth/core.py
- src/onegov/user/auth/provider.py
- src/onegov/user/auth/second_factor.py
- src/onegov/user/cli.py
- src/onegov/user/collections/group.py
- src/onegov/user/collections/user.py
- src/onegov/user/errors.py
- src/onegov/user/forms/group.py
- src/onegov/user/forms/login.py
- src/onegov/user/forms/reset_password.py
- src/onegov/user/forms/signup_link.py
- src/onegov/user/integration.py
- src/onegov/user/models/group.py
- src/onegov/user/models/role_mapping.py
- src/onegov/user/models/user.py
- src/onegov/user/sync.py
- src/onegov/user/upgrade.py
- src/onegov/user/utils.py
mypy: Adds type annotations for onegov.user
Fixes uncovered typing issues
> mypy: Adds type annotations for onegov.user

- src/onegov/feriennet/templates/macros.pt
- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/wtfs/templates/layout.pt
Org: Replace onegov footer links with admin.digital
TYPE: Feature
> Replace links

- src/onegov/feriennet/theme/styles/feriennet.scss
- src/onegov/org/theme/styles/org.scss
- src/onegov/winterthur/theme/styles/winterthur.scss
Org: Fix side panel
TYPE: Bugfix
> Ogc 1103 side panel

- src/onegov/core/framework.py
- src/onegov/core/sentry.py
- src/onegov/server/cli.py
- tests/onegov/core/test_sentry.py
Starts using `SentryWsgiMiddleware`, since this performs all the necessary book keeping for traces and profiles
Core: Adds a proper Sentry Integration
Starts using `SentryWsgiMiddleware`, since this performs all the necessary book keeping for traces and profiles
TYPE: Feature
LINK: OGC-1178
> Core: Adds a proper Sentry Integration

- src/onegov/org/forms/event.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
org: Improved error message for event import in case of header line
TYPE: Feature
LINK: None
> Extend error message for event import in case of header line

- src/onegov/event/collections/events.py
- tests/onegov/event/test_collections.py
event: prevent malicious code injection while importing ical
TYPE: Feature
LINK: ogc-1192
> Escape ical content

- pyproject.toml
- src/onegov/core/collection.py
- src/onegov/pay/__init__.py
- src/onegov/pay/collections/payable.py
- src/onegov/pay/collections/payment.py
- src/onegov/pay/collections/payment_provider.py
- src/onegov/pay/integration.py
- src/onegov/pay/models/payable.py
- src/onegov/pay/models/payment.py
- src/onegov/pay/models/payment_provider.py
- src/onegov/pay/models/payment_providers/stripe.py
- src/onegov/pay/types.py
- src/onegov/pay/upgrade.py
- src/onegov/pay/utils.py
- src/onegov/reservation/collection.py
- src/onegov/reservation/core.py
- src/onegov/reservation/models/custom_allocation.py
- src/onegov/reservation/models/custom_reservation.py
- src/onegov/reservation/models/resource.py
- src/onegov/reservation/upgrade.py
mypy: Adds type annotations for onegov.reservation and onegov.pay
> mypy: Adds type annotations for onegov.reservation and onegov.pay

- pyproject.toml
- setup.cfg
- src/onegov/file/__init__.py
- src/onegov/file/attachments.py
- src/onegov/file/collection.py
- src/onegov/file/errors.py
- src/onegov/file/filters.py
- src/onegov/file/integration.py
- src/onegov/file/models/file.py
- src/onegov/file/models/file_message.py
- src/onegov/file/models/fileset.py
- src/onegov/file/models/named_file.py
- src/onegov/file/sign/generic.py
- src/onegov/file/sign/swisscom_ais.py
- src/onegov/file/types.py
- src/onegov/file/upgrade.py
- src/onegov/file/utils.py
- tests/onegov/file/test_models.py
- tests/shared/fixtures.py
mypy: Adds annotations for onegov.file
> mypy: Adds annotations for onegov.file

- pyproject.toml
- src/onegov/chat/collections/message.py
- src/onegov/chat/collections/text_module.py
- src/onegov/chat/models/message.py
- src/onegov/chat/models/text_module.py
- tests/onegov/chat/test_collection.py
- tests/onegov/chat/test_model.py
mypy: Adds type annotations for onegov.chat
> mypy: Adds type annotations for onegov.chat

- src/onegov/file/filters.py
- src/onegov/file/upgrade.py
TYPE: Bugfix
LINK: OGC-1190
File: Optimizes thumbnail generation and potentially fixes issue
TYPE: Bugfix
LINK: OGC-1190
> File: Optimizes thumbnail generation and potentially fixes issue

- tests/onegov/quill/test_browser.py
- tests/shared/fixtures.py
> Reenables browser tests

- src/onegov/core/orm/mixins/content.py
- tests/onegov/core/test_orm.py
Core: Makes dict_property behave like a hybrid_property
TYPE: Feature
> Core: Makes dict_property behave like a hybrid_property

- setup.cfg
- src/onegov/org/forms/extensions.py
Org: Fixes publication form extension
TYPE: Bugfix
> Org: Fixes publication form extension

- pyproject.toml
- setup.cfg
- src/onegov/gever/encrypt.py
- src/onegov/gever/gever_client.py
- src/onegov/newsletter/__init__.py
- src/onegov/newsletter/collection.py
- src/onegov/newsletter/models.py
- src/onegov/newsletter/upgrade.py
- src/onegov/notice/collections.py
- src/onegov/notice/models.py
- src/onegov/notice/upgrade.py
- src/onegov/org/models/page.py
- src/onegov/page/__init__.py
- src/onegov/page/collection.py
- src/onegov/page/model.py
- src/onegov/page/upgrade.py
- src/onegov/qrcode/__init__.py
- src/onegov/qrcode/model.py
- src/onegov/ticket/__init__.py
- src/onegov/ticket/collection.py
- src/onegov/ticket/handler.py
- src/onegov/ticket/model.py
- src/onegov/ticket/upgrade.py
mypy: Adds type annotations for some smaller modules
> mypy: Adds type annotations for some smaller modules

- tests/onegov/form/test_display.py
<Module>: <Message>
TYPE: <Feature|Bugfix>
LINK: <Ticket-Number>
HINT: <Optional upgrade hint>
> Adds escape test for text fields

- setup.cfg
Core: Pin validators
TYPE: Bugfix
LINK: OGC-1224
> Pin validators<0.21

- src/onegov/swissvotes/templates/vote.pt
> Swissvotes: Move position of the federal council to voting campaign.

- src/onegov/swissvotes/models/vote.py
- src/onegov/swissvotes/templates/vote.pt
- tests/onegov/swissvotes/conftest.py
Swissvotes: Enable french brief descriptions and result files.
TYPE: Feature
LINK: SWI-33
> Swissvotes: Enable french brief descriptions and result files.

- pyproject.toml
- setup.cfg
- src/onegov/agency/views/settings.py
- src/onegov/form/core.py
- src/onegov/form/fields.py
- src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/fr_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/it_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/rm_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/parser/form.py
- src/onegov/form/types.py
- src/onegov/form/validators.py
- src/onegov/onboarding/forms/town.py
- src/onegov/org/forms/directory.py
- src/onegov/org/forms/settings.py
- src/onegov/town6/forms/settings.py
- src/onegov/wtfs/forms/scan_job.py
- tests/onegov/form/test_core.py
- tests/onegov/form/test_parser.py
- tests/onegov/onboarding/test_views.py
Form: Remove wtforms-components dependency
TYPE: Bugfix
LINK: OGC-1226
> Form: Remove wtforms-components dependency

- pyproject.toml
- src/onegov/websockets/cli.py
- src/onegov/websockets/client.py
- src/onegov/websockets/integration.py
- src/onegov/websockets/server.py
mypy: Adds type annotations for onegov.websockets
> mypy: Adds type annotations for onegov.websockets

- src/onegov/event/collections/occurrences.py
- src/onegov/org/views/occurrence.py
- src/onegov/winterthur/views/occurrence.py
Events: Winterthur adding xml view for anthrazit format
TYPE: Feature
LINK: ogc-1048
> Adding xml view for Winterthur with anthrazit xml format

- setup.cfg
- src/onegov/core/markdown.py
- tests/onegov/core/test_markdown.py
> Core: Add compatibility with mistletoe 1.2.

- src/onegov/swissvotes/collections/votes.py
- src/onegov/swissvotes/models/column_mapper.py
- src/onegov/swissvotes/models/vote.py
- src/onegov/swissvotes/upgrade.py
- tests/onegov/swissvotes/conftest.py
- tests/onegov/swissvotes/test_collections.py
- tests/onegov/swissvotes/test_fields.py
- tests/onegov/swissvotes/test_forms.py
- tests/onegov/swissvotes/test_models.py
- tests/onegov/swissvotes/test_views_votes.py
Swissvotes: Add English short title.
TYPE: Feature
LINK: SWI-38
> Swissvotes: Add English short title.

- src/onegov/core/request.py
- src/onegov/core/sentry.py
- tests/onegov/core/test_request.py
Core: Fixes `request.application_url`/`request.path_url`
Also fixes incorrect url in sentry events
TYPE: Bugfix
> Core: Fixes `request.application_url`/`request.path_url`

- src/onegov/winterthur/event_search_widgets.py
Winterthur: Inline search lower search text
TYPE: Bugfix
LINK: ogc-1201
> Ensure searching lowercase

- src/onegov/landsgemeinde/forms/agenda.py
- src/onegov/landsgemeinde/forms/votum.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/models/agenda.py
- src/onegov/landsgemeinde/models/votum.py
- src/onegov/landsgemeinde/templates/agenda_item.pt
- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/upgrade.py
> Landsgemeinde: Remove start time from agenda items and vota.

- src/onegov/landsgemeinde/layouts/votum.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/templates/ticker.pt
- src/onegov/landsgemeinde/utils.py
- src/onegov/landsgemeinde/views/agenda.py
- src/onegov/landsgemeinde/views/assembly.py
- src/onegov/landsgemeinde/views/votum.py
- tests/onegov/landsgemeinde/test_utils.py
Landsgmeinde: Improve tracking of ticker changes and add a hint for completed assemblies.
TYPE: Feature
LINK: OGC-1238
> Landsgmeinde: Improve tracking of ticker changes

- src/onegov/core/orm/abstract/adjacency_list.py
- src/onegov/org/app.py
- src/onegov/page/model.py
Org: Optimizes page navigation by avoiding recursive database queries
TYPE: Bugfix
LINK: OGC-1228
> Org: Optimizes page navigation by avoiding recursive database queries

- src/onegov/town6/theme/styles/fullcalendar.scss
Town6: Fix overlapping elements.
TYPE: Bugfix
LINK: OGC-1252
> Town6: Fix overlapping elements.

- .github/workflows/tests.yml
Build: Extend build workflow into 7 groups
TYPE: Feature
> Adjust workflow to split into 7 groups

- .github/workflows/tests.yml
- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/layout.py
- src/onegov/town6/templates/macros.pt
- tests/onegov/town6/test_homepage_widgets.py
Town6: Adds job widget based on RSS feed.
TYPE: Feature
LINK: OGC-1255
See ticket for example widget structure.
> Town6: Adds job widget based on RSS feed.

- src/onegov/election_day/assets/js/foundation.js
- src/onegov/election_day/assets/js/jquery.js
- src/onegov/gazette/assets/js/foundation.js
- src/onegov/gazette/assets/js/jquery.js
- src/onegov/onboarding/assets/js/foundation.js
- src/onegov/onboarding/assets/js/jquery.js
- src/onegov/swissvotes/assets/js/foundation.js
- src/onegov/swissvotes/assets/js/jquery.js
- src/onegov/wtfs/assets/js/foundation.js
- src/onegov/wtfs/assets/js/jquery.js
> Multiple: Update jQuery.

- src/onegov/org/views/people.py
- tests/onegov/org/test_views_people.py
Town6: Sort by pages in person card.
TYPE: Bugfix
LINK: OGC-1257
> Town6: Sort by pages in person card.

- src/onegov/winterthur/event_search_widgets.py
Events: Makes inline search work with event json data
TYPE: Bugfix
LINK: ogc-1219
> Make inline search work with json data of events

- src/onegov/core/cli/commands.py
Core: Speed up file transfer by only copying files which differ from remote.
TYPE: Feature
LINK: OGC-1267
> Core: Speed up file transfer.

- src/onegov/winterthur/cronjobs.py
Winterthur: DWS Event import set default fitler keywords instead of default categories
TYPE: Feature
LINK: ogc-1225
> Remove 'Sport'tag and add 'veranstaltungstyp' as filter

- src/onegov/town6/assets/js/animate.js
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/header.scss
Town6: Mark current navigation element
TYPE: Feature
LINK: OGC-1259
> Ogc 1259 nav current

- src/onegov/org/app.py
Org: Fixes regression in `OrgApp.root_pages`
TYPE: Bugfix
LINK: OGC-1276
> Org: Fixes regression in `OrgApp.root_pages`

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
Events: Fix how filters are displayed in ticket summary
TYPE: Bugfix
LINK: ogc-1219
> Fix how filters are displayed in ticket summary

- src/onegov/org/layout.py
- src/onegov/town6/layout.py
- src/onegov/translator_directory/assets/js/translator_directory.js
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- src/onegov/translator_directory/models/ticket.py
- src/onegov/translator_directory/views/translator.py
- tests/onegov/translator_directory/test_views.py
Adds mail templates link in edit bar.
TYPE: Feature
LINK: OGC-1261
> Translator directory: Adds mail templates link in edit bar.

- src/onegov/org/templates/macros.pt
- src/onegov/org/views/occurrence.py
- src/onegov/town6/templates/macros.pt
Events: Fix link for 'past events' in case of no events found.
TYPE: Bugfix
LINK: ogc-1281
> Fix lost url params for past events link

- src/onegov/town6/templates/macros.pt
Town6: Fix Current Page Highlighting
TYPE: Bugfix
> Fix highlighting of current page

- src/onegov/town6/theme/styles/forms.scss
Town6: Input Button Styling
TYPE: Feature>
LINK: ORG-682
> input with button adjust corners

- src/onegov/ballot/models/election/candidate.py
- src/onegov/ballot/models/election/election.py
- src/onegov/ballot/models/election/list.py
- src/onegov/ballot/models/election/list_connection.py
- src/onegov/ballot/models/election/mixins.py
- src/onegov/ballot/models/vote/ballot.py
- src/onegov/ballot/models/vote/mixins.py
- src/onegov/ballot/models/vote/vote.py
- tests/onegov/ballot/models/test_candidate.py
- tests/onegov/ballot/models/test_election.py
- tests/onegov/ballot/models/test_list.py
- tests/onegov/ballot/models/test_vote.py
> Ballot: Fixes various hybrid properties.

- src/onegov/directory/archive.py
Org: Fixes the directory import for edge case.
TYPE:  Bugfix
LINK: OGC-338
> Org: Fixes the directory import for edge case.

- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- src/onegov/town6/theme/styles/forms.scss
- src/onegov/town6/theme/styles/org.scss
Landsgemeinde: Minor Adjusment
TYPE: Feature
LINK: OGC-1286
> Ogc 1286 line height

- src/onegov/winterthur/app.py
Winterthur: Enable resizer for Single Events
TYPE: Bugfix
LINK: OGC-1047
> Enable resizer for single events

- src/onegov/org/views/event.py
Org: Displays filters in event form regardless of user privileges
TYPE: Bugfix
LINK: OGC-1308
> Org: Displays filters in event form regardless of user privileges

- pyproject.toml
- src/onegov/ballot/models/vote/complex_vote.py
- src/onegov/election_day/cli.py
- src/onegov/election_day/formats/exports/__init__.py
- src/onegov/election_day/pdf.py
- src/onegov/election_day/utils/__init__.py
- src/onegov/election_day/utils/archive_generator.py
- src/onegov/election_day/utils/common.py
- src/onegov/election_day/utils/d3_renderer.py
- src/onegov/election_day/utils/election/__init__.py
- src/onegov/election_day/utils/election/candidates.py
- src/onegov/election_day/utils/election/connections.py
- src/onegov/election_day/utils/election/lists.py
- src/onegov/election_day/utils/election_compound/__init__.py
- src/onegov/election_day/utils/election_compound/candidates.py
- src/onegov/election_day/utils/election_compound/districts.py
- src/onegov/election_day/utils/election_compound/list_groups.py
- src/onegov/election_day/utils/election_compound/superregions.py
- src/onegov/election_day/utils/filenames.py
- src/onegov/election_day/utils/parties/__init__.py
- src/onegov/election_day/utils/parties/parties.py
- src/onegov/election_day/utils/pdf_generator.py
- src/onegov/election_day/utils/summaries.py
- src/onegov/election_day/utils/svg_generator.py
- src/onegov/election_day/utils/vote/__init__.py
- src/onegov/election_day/utils/vote/ballot.py
- tests/onegov/election_day/utils/test_d3_renderer.py
mypy: Adds type hints for onegov.election_day.utils
> mypy: Adds type hints for onegov.election_day.utils

- src/onegov/core/request.py
- src/onegov/file/integration.py
- src/onegov/org/app.py
- src/onegov/org/layout.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/extensions.py
- src/onegov/org/templates/macros.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/hints.scss
- tests/onegov/org/test_extensions.py
- tests/onegov/org/test_views_auth.py
Org: Adds a secret variant of mTAN access (i.e. not listed)
TYPE: Feature
LINK: OGC-1327
> Org: Adds a secret variant of mTAN access (i.e. not listed)

- src/onegov/event/collections/events.py
Events: Anthrazit xml export: Fix missing event if series started in the past 
TYPE: Bugfix
LINK: ogc-1320
> Fix missing event in xml if serie has started in the past

- tests/onegov/feriennet/test_browser.py
- tests/onegov/org/test_browser.py
Test: Mark occasionally failing web test as 'flaky'
TYPE: Bugfix
LINK: None
> Mark webtest flaky

- src/onegov/town6/assets/js/animate.js
- src/onegov/town6/templates/layout.pt
- src/onegov/town6/theme/styles/header.scss
Town6: Remove Gray line at top of page
TYPE: Bugfix
LINK: OGC-1268
> No gray line on top of page

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/ticket.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/org/views/ticket.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/ticket.pt
- src/onegov/town6/theme/styles/tickets.scss
- tests/onegov/org/test_views_ticket.py
Org: Send assign ticket email regardless of its notification settings
TYPE: Feature
LINK: OGC-1138
> Org: Send assign ticket email regardless of its notification settings

- src/onegov/org/layout.py
- src/onegov/town6/layout.py
Org: Show QrCode in directories.
TYPE: Feature
LINK:  OGC-1333
> Org: Show QRCode in directories

- src/onegov/org/assets/js/redactor.js
Town6: Editor-Toolbar Position
TYPE: Bugfix
LINK: OGC-1315
> Adjust offset to exact header height

- src/onegov/town6/assets/js/sidebar_fixed.js
- src/onegov/town6/templates/macros.pt
Town6: Sidebar overlapping footer fix
Fixes sidebar overlapping footer if it is bigger than the content.
TYPE: Bugfix
> Ogc 1341 sidebar

- .pre-commit-config.yaml
- pyproject.toml
- src/onegov/directory/archive.py
- src/onegov/directory/collections/__init__.py
- src/onegov/directory/collections/directory.py
- src/onegov/directory/collections/directory_entry.py
- src/onegov/directory/errors.py
- src/onegov/directory/migration.py
- src/onegov/directory/models/directory.py
- src/onegov/directory/models/directory_entry.py
- src/onegov/directory/types/directory_configuration.py
- src/onegov/directory/upgrade.py
- src/onegov/form/parser/core.py
- src/onegov/org/models/directory.py
- src/onegov/org/views/directory.py
- tests/onegov/directory/test_orm.py
mypy: Adds type hints for onegov.directory
> mypy: Adds type hints for onegov.directory

- src/onegov/town6/app.py
- src/onegov/town6/assets/js/animate.js
- src/onegov/town6/assets/js/homepage_video_or_slider.js
Town6: Resizing of video and slider according to navigation height
TYPE: Bugfix
> fix video height

- src/onegov/core/cronjobs.py
- src/onegov/landsgemeinde/templates/layout.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
Landsgemeinde: Logo and search placement
Place search in navigation and move logo to the right
TYPE: Feature
LINK: OGC-1288
> Ogc 1288 logo landsgemeinde

- pyproject.toml
- src/onegov/directory/collections/directory_entry.py
- src/onegov/event/__init__.py
- src/onegov/event/cli.py
- src/onegov/event/collections/events.py
- src/onegov/event/collections/occurrences.py
- src/onegov/event/models/event.py
- src/onegov/event/models/mixins.py
- src/onegov/event/models/occurrence.py
- src/onegov/event/upgrade.py
- src/onegov/event/utils/guidle.py
- src/onegov/event/utils/utils.py
mypy: Adds type hints for onegov.event
> mypy: Adds type hints for onegov.event

- src/onegov/town6/layout.py
> Directory: Avoids AttributeError on entry with multiple files.

- pyproject.toml
- src/onegov/people/cli.py
- src/onegov/people/collections/agencies.py
- src/onegov/people/collections/memberships.py
- src/onegov/people/collections/people.py
- src/onegov/people/models/agency.py
- src/onegov/people/models/membership.py
- src/onegov/people/models/person.py
- src/onegov/people/upgrade.py
mypy: Adds type hints for onegov.people
> mypy: Adds type hints for onegov.people

- src/onegov/org/layout.py
- src/onegov/town6/layout.py
Org: Show QRCode in directory entries
TYPE: Feature
LINK: OGC-1333
> Org: Show QRCode in directory entries

- src/onegov/form/validators.py
- src/onegov/org/forms/mtan.py
- tests/onegov/form/test_validators.py
Org: Restrict mTAN access to numbers from CH, AT, DE, FR, IT, LI
TYPE: Feature
LINK: OGC-1391
> Org: Restrict mTAN access to numbers from CH, AT, DE, FR, IT, LI

- src/onegov/org/cronjobs.py
- src/onegov/org/models/tan.py
- tests/onegov/org/test_cronjobs.py
Org: Adds minimal mTAN reporting for billing purposes
This also increases the data retention period on TAN objects
TYPE: Feature
LINK: OGC-1340
> Org: Adds minimal mTAN reporting for billing purposes

- src/onegov/form/display.py
- tests/onegov/form/test_display.py
Form: Sorts files by name when displaying a `MultipleUploadField`
TYPE: Feature
LINK: OGC-1392
> Form: Sorts files by name when displaying a `MultipleUploadField`

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
Org, Town6: Avoid fake favicon requests
TYPE: Feature
LINK: ogc-1003
> Avoid fake favicon requests

- src/onegov/org/auth.py
- src/onegov/org/views/auth.py
- tests/onegov/org/test_views_auth.py
Org: Shortens URL used in mTAN SMS
TYPE: Bugfix
LINK: OGC-1401
> Org: Shortens URL used in mTAN SMS.

- pyproject.toml
- src/onegov/org/models/__init__.py
- src/onegov/org/models/atoz.py
- src/onegov/org/models/clipboard.py
- src/onegov/org/models/dashboard.py
- src/onegov/org/models/directory.py
- src/onegov/org/models/editor.py
- src/onegov/org/models/export.py
- src/onegov/org/models/extensions.py
- src/onegov/org/models/external_link.py
- src/onegov/org/models/file.py
- src/onegov/org/models/form.py
- src/onegov/org/models/legacy_file.py
- src/onegov/org/models/message.py
- src/onegov/org/models/organisation.py
- src/onegov/org/models/page.py
- src/onegov/org/models/page_move.py
- src/onegov/org/models/person_move.py
- src/onegov/org/models/publication.py
- src/onegov/org/models/recipient.py
- src/onegov/org/models/resource.py
- src/onegov/org/models/search.py
- src/onegov/org/models/sitecollection.py
- src/onegov/org/models/swiss_holidays.py
- src/onegov/org/models/ticket.py
- src/onegov/org/models/traitinfo.py
- src/onegov/org/views/form_registration_window.py
- src/onegov/org/views/ticket.py
- src/onegov/page/model.py
- src/onegov/ticket/handler.py
mypy: Adds type hints for `onegov.org.models`
> mypy: Adds type hints for `onegov.org.models`

- src/onegov/org/forms/extensions.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/directory.py
- src/onegov/org/templates/directory_entry.pt
- src/onegov/org/views/directory.py
- src/onegov/town6/templates/directory_entry.pt
Org: Adds an internal notes field to directory entries
TYPE: Feature
LINK: OGC-1403
> Org: Adds an internal notes field to directory entries

- src/onegov/chat/collections/chat.py
- src/onegov/chat/models/chat.py
- src/onegov/org/__init__.py
- src/onegov/org/app.py
- src/onegov/org/cli.py
- src/onegov/org/converters.py
- src/onegov/org/cronjobs.py
- src/onegov/org/custom.py
- src/onegov/org/directives.py
- src/onegov/org/elements.py
- src/onegov/org/formats/digirez.py
- src/onegov/org/homepage_widgets.py
- src/onegov/org/initial_content.py
- src/onegov/org/layout.py
- src/onegov/org/models/traitinfo.py
- src/onegov/org/request.py
- src/onegov/pay/models/payment_provider.py
- src/onegov/pay/models/payment_providers/stripe.py
- src/onegov/ticket/collection.py
- src/onegov/websockets/server.py
mypy: Adds some type hints for `onegov.org`
> mypy: Adds some type hints for `onegov.org`

- src/onegov/town6/templates/directory.pt
- src/onegov/town6/theme/styles/directories.scss
Town 6:  Adjust width of left column for more map space 
TYPE: Feature
LINK:  OGC-1414
> Adjust width of left column for more map space

- src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
Town6: Editor Form Translation
TYPE: Feature
LINK: OGC-1402
> Ogc editor form translation

- pyproject.toml
- src/onegov/agency/layout.py
- src/onegov/async_http/fetch.py
- src/onegov/core/elements.py
- src/onegov/fsi/layout.py
- src/onegov/fsi/layouts/course.py
- src/onegov/fsi/layouts/course_event.py
- src/onegov/fsi/layouts/notification.py
- src/onegov/org/elements.py
- src/onegov/org/homepage_widgets.py
- src/onegov/org/layout.py
- src/onegov/org/mail.py
- src/onegov/org/management.py
- src/onegov/org/models/directory.py
- src/onegov/org/models/organisation.py
- src/onegov/org/models/ticket.py
- src/onegov/org/open_graph.py
- src/onegov/org/utils.py
- src/onegov/org/views/form_registration_window.py
- src/onegov/town6/layout.py
- tests/onegov/org/test_macros.py
mypy: Adds type hints for `onegov.org.layout`
> mypy: Adds type hints for `onegov.org.layout`

- setup.cfg
- src/onegov/core/elements.py
- src/onegov/core/layout.py
- src/onegov/election_day/layouts/mail.py
- src/onegov/gazette/layout.py
- src/onegov/onboarding/layout.py
- src/onegov/org/layout.py
- src/onegov/wtfs/layouts/mail.py
mypy: Removes chameleon pin and fixes uncovered typing errors
> mypy: Removes chameleon pin and fixes uncovered typing errors

- src/onegov/org/models/search.py
Org: Don't assume occurrence.start exists always
TYPE: Bugfix
> Resolves `FIXME`

- pyproject.toml
- src/onegov/org/forms/user.py
- src/onegov/org/models/directory.py
- src/onegov/org/security.py
- src/onegov/org/upgrade.py
- src/onegov/org/utils.py
mypy: Adds additional type hints for `onegov.org`
> mypy: Adds additional type hints for `onegov.org`

- src/onegov/town6/assets/js/sidebar_mobile.js
Town6: Fix hidden sidebar-toggler
TYPE: Bugfix
LINK: OGC-1422
> Fix hidden sidebar-toggler

- src/onegov/translator_directory/collections/translator.py
Translator Directory: Fixes page search results resetting query
Switching to a new page in search reset the search filter.
TYPE: Bugfix
LINK: OGC-1425
> Translator Directory: Fixes page search results resetting query

- tests/onegov/org/test_notifications.py
- tests/onegov/town6/test_notifications.py
Use freezegun for dates in test
> Use freezegun for dates in test

- src/onegov/org/templates/ticket.pt
- src/onegov/town6/templates/ticket.pt
Reservation: Reservation ticket now have a link to the resource
TYPE: Feature
> Reservation ticket: Adds link to resource

- src/onegov/core/widgets.py
- src/onegov/event/collections/occurrences.py
- src/onegov/org/forms/generic.py
- src/onegov/org/forms/newsletter.py
- src/onegov/org/models/organisation.py
- src/onegov/org/models/page.py
- src/onegov/org/pdf/ticket.py
- src/onegov/org/views/form_definition.py
- src/onegov/org/views/form_export.py
- src/onegov/org/views/form_registration_window.py
- src/onegov/org/views/form_submission.py
- src/onegov/org/views/homepage.py
- src/onegov/org/views/imagesets.py
- src/onegov/org/views/locale.py
- src/onegov/org/views/message.py
- src/onegov/org/views/newsletter.py
- src/onegov/org/views/occurrence.py
- src/onegov/org/views/page.py
- src/onegov/org/views/page_move.py
- src/onegov/town6/views/newsletter.py
- tests/onegov/event/test_collections.py
mypy: Adds additional type hints for `onegov.org.views`
> mypy: Adds additional type hints for `onegov.org.views`

- src/onegov/event/collections/occurrences.py
> Event: Load event content before ical export. 

- src/onegov/org/app.py
- tests/onegov/org/test_views_auth.py
Org: Don't redirect to the mTAN view if the view cannot be accessed
E.g. in the case of a view with a publication the mTAN check would happen even when the object isn't published, so you would do the authentication only to be greeted with a 403 error.
TYPE: Bugfix
LINK: OGC-1451
> Org: Don't redirect to the mTAN view if the view cannot be accessed

- src/onegov/election_day/formats/exports/election/internal_majorz.py
- src/onegov/election_day/formats/exports/election/internal_proporz.py
- src/onegov/election_day/formats/exports/election_compound/internal.py
- src/onegov/election_day/formats/exports/vote/internal.py
- src/onegov/election_day/static/docs/api/open_data_de.md
- src/onegov/election_day/static/docs/api/open_data_en.md
- src/onegov/election_day/static/docs/api/open_data_fr.md
- src/onegov/election_day/static/docs/api/open_data_it.md
- src/onegov/election_day/static/docs/api/open_data_rm.md
- tests/onegov/election_day/formats/exports/test_export_election_compound_internal.py
- tests/onegov/election_day/formats/exports/test_export_election_internal_majorz.py
- tests/onegov/election_day/formats/exports/test_export_election_internal_proporz.py
- tests/onegov/election_day/formats/exports/test_export_vote_internal.py
> Election Day: Add ID to internal exports.

- src/onegov/election_day/forms/subscription.py
- tests/onegov/election_day/forms/test_subscriber_form.py
> Election Day: Add country validator to SMS subscriber form.

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/static/docs/api/format_election_it.md
- src/onegov/election_day/static/docs/api/format_election_rm.md
- src/onegov/election_day/static/docs/api/open_data_it.md
- src/onegov/election_day/static/docs/api/open_data_rm.md
> Election Day: Update translations

- src/onegov/election_day/formats/exports/vote/internal.py
- src/onegov/election_day/static/docs/api/open_data_de.md
- src/onegov/election_day/static/docs/api/open_data_en.md
- src/onegov/election_day/static/docs/api/open_data_fr.md
- src/onegov/election_day/static/docs/api/open_data_it.md
- src/onegov/election_day/static/docs/api/open_data_rm.md
- tests/onegov/election_day/formats/exports/test_export_vote_internal.py
> Election Day: Add answer to internal export.

- src/onegov/election_day/utils/archive_generator.py
- tests/onegov/election_day/utils/test_archive_generator.py
> Election Day: Add party results to archive.

- src/onegov/landsgemeinde/forms/agenda.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/models/agenda.py
- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/templates/states.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- src/onegov/landsgemeinde/upgrade.py
- src/onegov/landsgemeinde/utils.py
- tests/onegov/landsgemeinde/test_utils.py
> Landsgemeinde: Add agenda item start time.

- src/onegov/landsgemeinde/templates/assembly.pt
- src/onegov/landsgemeinde/templates/ticker.pt
> Landsgemeinde: Only preload metadata of mp3.

- src/onegov/feriennet/forms/period.py
Feriennet: Fix error when deleting prebookingdate
TYPE: Bugfix
LINK: PRO-1244
> Overwrite confirmable field before validation

- src/onegov/ballot/models/vote/vote.py
- src/onegov/election_day/models/archived_result.py
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/views/election/main.py
- src/onegov/election_day/views/vote/main.py
- tests/onegov/election_day/views/test_views_vote.py
> Election Day: Fix JSON views.

- src/onegov/election_day/screen_widgets/vote.py
- src/onegov/election_day/templates/macros.pt
- tests/onegov/election_day/screen_widgets/test_vote_widgets.py
> Election Day: Sort entities tables widgets by names.

- src/onegov/election_day/models/principal.py
- tests/onegov/election_day/models/test_principal.py
> Election Day: Fixes eCH-0252 domain identification for cantons.

- src/onegov/election_day/assets/js/screen.js
> Election Day: Avoid loading browser-cached group screens.

- pyproject.toml
- src/onegov/core/cache.py
- src/onegov/core/templates.py
- src/onegov/election_day/upgrade.py
- src/onegov/org/models/directory.py
- src/onegov/org/upgrade.py
- src/onegov/org/views/imagesets.py
- src/onegov/server/cli.py
- src/onegov/ticket/collection.py
- src/onegov/user/auth/clients/ldap.py
- src/onegov/user/auth/provider.py
mypy: Enables additional checks for strict config
> mypy: Enables additional checks for strict config

- src/onegov/core/cli/commands.py
Core: Adds horizontal movement and history to the shell.
TYPE: Feature
> Core: Adds horizontal movement and history to the shell.

- tests/onegov/activity/test_models.py
- tests/onegov/event/test_collections.py
Org: Fixes tests with leap year issue
TYPE: Bugfix
LINK: None
> Uses freeze_time to fix leap year issue

- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
Use closure to capture free variables
TYPE: Bugfix
LINK: OGC-1255
Tested and works. See linear for xml if needed.
> Use closure to capture free variables

- src/onegov/form/fields.py
- tests/onegov/form/test_fields.py
> Form: Add a select field which translates the choice labels.

- src/onegov/town6/theme/styles/alert.scss
- src/onegov/town6/theme/styles/forms.scss
> Org: Improve styling of alerts and errors.

- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
Agency: Add back translation that was removed. 
TYPE: Bugfix
LINK: OGC-1508
> Agency: Add back translation that was removed.

- src/onegov/activity/matching/score.py
- tests/onegov/activity/test_matching_db.py
Feriennet: Remove offset which ignored preferred bookings if attendee is also in a group
TYPE: Bugfix
LINK: PRO-1262
> Pro 1262 matching algorithm

- src/onegov/town6/theme/styles/alert.scss
- src/onegov/town6/theme/styles/header.scss
Town6: Remove gap above homepage video
TYPE: Bugfix
LINK:  OGC-1522
> Ogc 1522 gap above homepage video

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/search.pt
- src/onegov/town6/theme/styles/header.scss
Town6: Styling of search results
TYPE: Bugfix
LINK: OGC-1125
> Restyle search results

- src/onegov/landsgemeinde/content/initial.py
- src/onegov/landsgemeinde/layouts/default.py
- src/onegov/landsgemeinde/models/agenda.py
- src/onegov/landsgemeinde/models/assembly.py
- src/onegov/landsgemeinde/models/votum.py
- src/onegov/landsgemeinde/templates/macros.pt
- tests/onegov/landsgemeinde/test_layouts.py
- tests/onegov/landsgemeinde/test_utils.py
- tests/onegov/landsgemeinde/test_views.py
> Landsgemeinde: Resolve various fixmes

- src/onegov/swissvotes/templates/vote.pt
> Add information button.

- src/onegov/swissvotes/forms/attachments.py
- src/onegov/swissvotes/locale/de_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/en_US/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/fr_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/models/column_mapper.py
- src/onegov/swissvotes/models/vote.py
- src/onegov/swissvotes/templates/vote.pt
- src/onegov/swissvotes/theme/styles/swissvotes.scss
- src/onegov/swissvotes/upgrade.py
- tests/onegov/swissvotes/conftest.py
- tests/onegov/swissvotes/test_collections.py
- tests/onegov/swissvotes/test_models.py
> Swissvotes: Add campaign finances.

- src/onegov/swissvotes/locale/de_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/en_US/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/fr_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/templates/vote.pt
> Swissvotes: Add link to BFS map.

- src/onegov/town6/theme/styles/town6.scss
- src/onegov/town6/theme/town_theme.py
Town6: Rename org.scss to town6.scss
> Rename org.scss in town 6 to town6.scss

- src/onegov/ballot/models/election/list.py
- src/onegov/ballot/models/election/proporz_election.py
- src/onegov/election_day/app.py
- src/onegov/election_day/cli.py
- src/onegov/election_day/collections/data_sources.py
- src/onegov/election_day/collections/screens.py
- src/onegov/election_day/directives.py
- src/onegov/election_day/formats/imports/common.py
- src/onegov/election_day/forms/notification.py
- src/onegov/election_day/layouts/archive.py
- src/onegov/election_day/layouts/detail.py
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/views/upload/__init__.py
- tests/onegov/ballot/models/test_election.py
- tests/onegov/ballot/models/test_proporz_election.py
- tests/onegov/election_day/common.py
- tests/onegov/election_day/test_cli.py
- tests/onegov/election_day/views/test_views.py
- tests/onegov/election_day/views/test_views_archive.py
- tests/onegov/election_day/views/test_views_election.py
- tests/onegov/election_day/views/test_views_election_compound.py
- tests/onegov/election_day/views/test_views_election_compound_part.py
- tests/onegov/election_day/views/test_views_manage.py
- tests/onegov/election_day/views/test_views_sitemap.py
- tests/onegov/election_day/views/test_views_vote.py
> Election Day: Cleanup unused code and increase test coverate. 

- src/onegov/swissvotes/collections/votes.py
- src/onegov/swissvotes/fields/dataset.py
- src/onegov/swissvotes/fields/metadata.py
- src/onegov/swissvotes/layouts/default.py
- src/onegov/swissvotes/layouts/page.py
- src/onegov/swissvotes/models/actor.py
- src/onegov/swissvotes/models/policy_area.py
- src/onegov/swissvotes/models/region.py
- src/onegov/swissvotes/models/vote.py
- src/onegov/swissvotes/upgrade.py
- src/onegov/swissvotes/views/votes.py
- tests/onegov/swissvotes/test_layouts.py
- tests/onegov/swissvotes/test_models.py
> Swissvotes: Adds missing upgrade step and resolves fixmes.

- .buildkite/docs
- .buildkite/lint
- .buildkite/test
- .github/workflows/measure-and-store-test-durations.yml
- .github/workflows/stubtest.yml
- .github/workflows/tests.yml
- makefile
Switches to using `uv` from `pip`
> Switches to using `uv` from `pip`

- src/onegov/core/cli/commands.py
Core: Add realname to default local admin user. 
Required if testing the feature
onegov.translator_directory.views.translator.view_mail_templates
TYPE: Other
LINK: OGC-1558
> Core: Add realname to default local admin user. 

- src/onegov/org/cronjobs.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/directory.py
- src/onegov/org/models/extensions.py
- tests/onegov/org/test_cronjobs.py
Directories: Delete expired directory entries automatically if marked 'deletable'
TYPE: Feature
LINK: ogc-1541
> Add model extension for deletable content and cronjob

- src/onegov/org/forms/allocation.py
Form: Adds missing `None` check.
TYPE: Bugfix
LINK: OGC-1561
> Add missing None check

- src/onegov/translator_directory/cli.py
- src/onegov/translator_directory/constants.py
- src/onegov/translator_directory/forms/accreditation.py
- src/onegov/translator_directory/forms/mutation.py
- src/onegov/translator_directory/forms/translator.py
- src/onegov/translator_directory/generate_docx.py
- src/onegov/translator_directory/models/translator.py
- src/onegov/translator_directory/templates/macros.pt
- src/onegov/translator_directory/templates/translator.pt
- src/onegov/translator_directory/upgrade.py
- src/onegov/translator_directory/views/translator.py
- tests/onegov/translator_directory/conftest.py
- tests/onegov/translator_directory/test_cli.py
- tests/onegov/translator_directory/test_forms.py
- tests/onegov/translator_directory/test_models.py
- tests/onegov/translator_directory/test_views.py
Translator Directory: Allow editing of hometown field
TYPE: Feature
LINK: OGC-1510
HINT: `onegov-translator --select /translator_directory/APP migrate-hometown`
> Migrate `hometown` to model

- .pre-commit-config.yaml
- src/onegov/town6/templates/occurrences.pt
Town 6: Add second pagination above events
TYPE: Feature
LINK: 1545
> Add second pagination above events

- src/onegov/ballot/collections/election_compounds.py
- src/onegov/ballot/collections/elections.py
- src/onegov/core/collection.py
- src/onegov/election_day/collections/data_sources.py
- src/onegov/election_day/collections/screens.py
- src/onegov/election_day/collections/subscribers.py
- src/onegov/event/collections/events.py
- src/onegov/event/collections/occurrences.py
- src/onegov/notice/collections.py
- src/onegov/org/models/search.py
- src/onegov/pay/collections/payment.py
- src/onegov/swissvotes/collections/votes.py
- src/onegov/swissvotes/path.py
- src/onegov/ticket/collection.py
- src/onegov/wtfs/collections/scan_jobs.py
- src/onegov/wtfs/path.py
- tests/onegov/ballot/collections/test_election_compounds.py
- tests/onegov/ballot/collections/test_elections.py
- tests/onegov/core/test_collection.py
- tests/onegov/election_day/collections/test_data_source_collection.py
- tests/onegov/election_day/collections/test_data_source_item_collection.py
- tests/onegov/election_day/collections/test_screen_collection.py
- tests/onegov/election_day/collections/test_subscriber_collection.py
- tests/onegov/event/test_collections.py
- tests/onegov/notice/test_collections.py
- tests/onegov/pay/test_collections.py
- tests/onegov/swissvotes/test_collections.py
- tests/onegov/ticket/test_collection.py
- tests/onegov/wtfs/test_collections.py
Org: Prevent negative page indexes, force to zero if necessary
TYPE: Bugfix
LINK: ogc-1573
> Adds test for negative page index

- src/onegov/org/forms/form_registration.py
- tests/onegov/org/test_views_forms.py
Org: Fix adjusting registration window (end date) after first attendee confirmed
TYPE: Bugfix
LINK: ogc-1557
> Adds test reproducing issue

- src/onegov/org/utils.py
> Org: Fix lxml usage in html annotation.

- src/onegov/org/custom.py
- src/onegov/org/layout.py
- src/onegov/org/path.py
- src/onegov/org/views/ticket.py
- src/onegov/ticket/collection.py
- src/onegov/town6/views/ticket.py
- tests/onegov/ticket/test_collection.py
Ticket: Align naming of Archived Ticket Collection
> Align naming for collection ArchivedTicketCollection

- src/onegov/search/cli.py
Search: Rework colors and error levels for search cli index-status command
TYPE: Feature
LINK: ogc-508
> Rework colors and error levels for search cli index-status command

- src/onegov/user/cli.py
- tests/onegov/user/test_cli.py
User: Extend cli for 'exists' with recursive flag in order to loop over schemas
TYPE: Feature
LINK: None
> Feature/user cli exists not limited to single context, adding recursive option

- src/onegov/gis/utils.py
- src/onegov/translator_directory/utils.py
> Translator directory: Fix bulk geocoding.

- src/onegov/translator_directory/theme/styles/translator_directory.scss
Hiding drive distance can be done using custom css on the instance.
LINK: OGC-999
> Translator Directory: Show drive distance again.

- src/onegov/event/models/mixins.py
- tests/onegov/event/test_models.py
Event: Fix filter values may be displayed as single characters 
TYPE: Bugfix
LINK: ogc-1578
> Adds test reproducing the issue

- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- tests/onegov/landsgemeinde/test_views.py
Landsgemeinde: Assembly Item displaced lines
TYPE: Bugfix
LINK: OGC-1566
> Ogc 1566 assembly item lines

- src/onegov/org/cronjobs.py
- src/onegov/org/models/page.py
News: News are now deletable when end date passed
TYPE: Bugfix
LINK: ogc-1560
> News are now deletable when expired

- src/onegov/org/models/extensions.py
Bugfix: Missing translation
ogc-1541
> Change field set text to enable translations

- src/onegov/election_day/views/screen.py
- tests/onegov/election_day/views/test_views.py
> Election Day: Add JSON for screens.

- src/onegov/core/cli/commands.py
- src/onegov/core/datamanager.py
- src/onegov/core/framework.py
- src/onegov/core/sms_processor.py
- src/onegov/core/utils.py
Core: Avoids writing `.tmp` files to the SMS queue altogether
TYPE: Bugfix
> Core: Avoids writing `.tmp` files to the SMS queue altogether

- .github/workflows/measure-and-store-test-durations.yml
- .github/workflows/stubtest.yml
- .github/workflows/tests.yml
- pyproject.toml
- src/onegov/fsi/app.py
- src/onegov/org/cronjobs.py
- src/onegov/search/cli.py
- src/onegov/search/dsl.py
- src/onegov/search/indexer.py
- src/onegov/search/integration.py
- src/onegov/search/mixins.py
- src/onegov/search/upgrade.py
- src/onegov/search/utils.py
- src/onegov/translator_directory/app.py
- tests/onegov/search/test_indexer.py
mypy: Adds type hints for `onegov.search`
> mypy: Adds type hints for `onegov.search`

- pyproject.toml
- setup.cfg
- src/onegov/event/collections/events.py
- src/onegov/event/collections/occurrences.py
- src/onegov/event/models/event.py
- src/onegov/event/models/occurrence.py
- src/onegov/fsi/models/course_event.py
- src/onegov/winterthur/cronjobs.py
mypy: installs iCalendar stubs and fixes uncovered issues
> mypy: installs iCalendar stubs and fixes uncovered issues

- src/onegov/landsgemeinde/app.py
- src/onegov/landsgemeinde/assets/js/start_time.js
- src/onegov/landsgemeinde/forms/agenda.py
- src/onegov/landsgemeinde/forms/assembly.py
- src/onegov/landsgemeinde/forms/votum.py
Landsgemeinde: Automaticaly fill in start time when "ongoing" is clicked in the form
TYPE: Feature
LINK: OGC-1626
> Automaticaly fill in start time when "ongoing" is clicked in the form

- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
Landsgemdeine: Display Timestamp for votum in ticker
TYPE: Feature
LINK: OGC-1624
> Ogc 1624 votum time in ticker

- src/onegov/landsgemeinde/app.py
- src/onegov/landsgemeinde/layouts/assembly.py
- src/onegov/landsgemeinde/layouts/default.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/templates/layout.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- tests/onegov/landsgemeinde/test_views.py
Landsgemeinde: Link to Liveticker during assembly
TYPE: Feature
LINK: OGC-1636
> Ogc 1636 liveticker link

- src/onegov/form/collection.py
- src/onegov/form/models/submission.py
- tests/onegov/form/test_collection.py
Submission: Update submission title after editing
TYPE: Bugfix
LINK: ogc-1576
> Update submmission title

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/org/forms/generic.py
Export: Implement a generic xml export
TYPE: Bugfix
LINK: None | Fixme
> Fixme Makes the xml export generic

- src/onegov/landsgemeinde/views/assembly.py
Landsgemeinde: Redirect to ticker if assembly is active
TYPE: Feature
LINK: OGC-1622
> Ogc 1622 redirect to ticker

- src/onegov/landsgemeinde/views/homepage.py
- tests/onegov/landsgemeinde/test_views.py
Landsgemeinde: Overwrite homepage rewrite if there is an ongoing assembly
TYPE: Feature
LINK: OGC-1621
> Overwrite homepage rewrite if therer is an ongoing assembly

- src/onegov/landsgemeinde/templates/assembly.pt
- src/onegov/town6/assets/js/sidebar_mobile.js
Landsgemeinde: Sidebar content in every window size
TYPE: Bugfix
LINK: OGC-1629
> Ogc 1629 sidebar

- src/onegov/org/layout.py
Newsletter: Fix wrong breadcrumb link in newsletter import / export view
TYPE: Bugfix
LINK: ogc-1649
> Fix wrong breadcrump link

- codecov.yml
- pyproject.toml
- setup.cfg
- src/onegov/agency/pdf.py
- src/onegov/fsi/pdf.py
- src/onegov/org/pdf/ticket.py
- src/onegov/pdf/page_functions.py
- src/onegov/pdf/pdf.py
- src/onegov/pdf/templates.py
mypy: Adds `types-reportlab` and fixes uncovered issues
> mypy: Adds `types-reportlab` and fixes uncovered issues

- src/onegov/town6/assets/js/sidebar_mobile.js
Town6: Fix sidebar problem in navigation
TYPE: Bugfix
LINK: OGC-1664
> Specify click event more

- src/onegov/election_day/models/election_compound/part.py
- src/onegov/election_day/static/docs/api/open_data_de.md
- src/onegov/election_day/static/docs/api/open_data_en.md
- src/onegov/election_day/static/docs/api/open_data_fr.md
- src/onegov/election_day/static/docs/api/open_data_it.md
- src/onegov/election_day/static/docs/api/open_data_rm.md
- src/onegov/election_day/utils/summaries.py
- tests/onegov/election_day/models/test_election_compound_part.py
- tests/onegov/election_day/models/test_notification.py
- tests/onegov/election_day/utils/test_summaries.py
- tests/onegov/election_day/views/test_views_election_compound.py
- tests/onegov/election_day/views/test_views_election_compound_part.py
> Election Day: Update open data documentation and add missing field.

- src/onegov/event/utils/guidle.py
- src/onegov/gis/forms/fields.py
- src/onegov/gis/models/coordinates.py
- src/onegov/gis/utils.py
- src/onegov/translator_directory/app.py
- src/onegov/translator_directory/forms/mixins.py
- src/onegov/translator_directory/utils.py
mypy: Cleans up the `Coordinates` situation with a tagged union
> mypy: Cleans up the `Coordinates` situation with a tagged union

- src/onegov/core/mail_processor/smtp.py
Core: Fixes parsing of JSON attachments in `SMTPMailQueueProcessor`
TYPE: Bugfix
LINK: OGC-1667
> Core: Fixes parsing of JSON attachments in `SMTPMailQueueProcessor`

- src/onegov/election_day/views/opendata_swiss.py
> Election Day: Add compatibility with DCAT-AP CH Version 2.

- src/onegov/org/views/auth.py
- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/layout.py
- src/onegov/town6/views/auth.py
- src/onegov/town6/views/chat.py
- src/onegov/translator_directory/models/language.py
- src/onegov/translator_directory/models/translator.py
- src/onegov/translator_directory/utils.py
- src/onegov/user/auth/clients/saml2.py
- src/onegov/user/auth/second_factor.py
- src/onegov/winterthur/cronjobs.py
- src/onegov/winterthur/roadwork.py
- tests/onegov/town6/test_homepage_widgets.py
Addresses/cleans up various FIXME comments
> Addresses/cleans up various FIXME comments

- src/onegov/election_day/formats/imports/election/ech.py
- src/onegov/election_day/formats/imports/vote/ech.py
> Election Day: Fix eCH enum imports.

- .buildkite/test
- .github/workflows/measure-and-store-test-durations.yml
- .github/workflows/tests.yml
- codecov.yml
- src/onegov/core/orm/observer.py
- tests/onegov/agency/conftest.py
- tests/onegov/election_day/conftest.py
- tests/onegov/feriennet/conftest.py
- tests/onegov/fsi/conftest.py
- tests/onegov/gazette/conftest.py
- tests/onegov/landsgemeinde/conftest.py
- tests/onegov/org/conftest.py
- tests/onegov/org/test_browser.py
- tests/onegov/pas/conftest.py
- tests/onegov/swissvotes/conftest.py
- tests/onegov/swissvotes/test_cli.py
- tests/onegov/town6/conftest.py
- tests/onegov/translator_directory/conftest.py
- tests/onegov/websockets/conftest.py
- tests/onegov/winterthur/conftest.py
- tests/onegov/wtfs/conftest.py
- tests/shared/fixtures.py
Since #1366 should have potentially fixed the deadlocks caused by forks, this might work now
> Improves CI performance by using pytest-xdist

- src/onegov/feriennet/forms/notification_template.py
- src/onegov/feriennet/layout.py
- src/onegov/feriennet/models/notification_template.py
- src/onegov/feriennet/templates/notification_template_send_form.pt
- src/onegov/feriennet/upgrade.py
- src/onegov/feriennet/views/notification_template.py
Feriennet: Switch to html for notification templates
TYPE: Bugfix
LINK: pro-1289
> Bugfix/pro 1289 html field for  notification template

- src/onegov/agency/layout.py
- src/onegov/agency/models/move.py
- src/onegov/event/collections/occurrences.py
- src/onegov/gazette/layout.py
- src/onegov/gazette/models/organization.py
- src/onegov/org/layout.py
- src/onegov/org/models/extensions.py
- src/onegov/org/models/page_move.py
- src/onegov/org/models/person_move.py
- src/onegov/org/path.py
- src/onegov/town6/layout.py
- tests/onegov/agency/test_layouts.py
- tests/onegov/agency/test_models.py
- tests/onegov/gazette/test_layout.py
- tests/onegov/gazette/test_models.py
- tests/onegov/org/test_extensions.py
Addresses FIXMEs about `MoveDirection` and `for_url_template`
> Addresses FIXMEs about `MoveDirection` and `for_url_template`

- src/onegov/org/forms/event.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
Org: New event tag "nature"
TYPE: Feature
LINK: OGC-1699
> New tag "nature"

- src/onegov/town6/templates/directory_entry_submission_form.pt
- src/onegov/town6/templates/directory_form.pt
- src/onegov/town6/templates/directory_import.pt
- src/onegov/town6/templates/export.pt
- src/onegov/town6/templates/login.pt
Town6: Fix save-button bug
TYPE: Bugfix
LINK: OGC-1682
> Add form id

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/file.py
- src/onegov/org/views/files.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/files.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/files.scss
- tests/onegov/org/test_models.py
Files: Adds 'published until' column to file view
TYPE: Feature
LINK: ogc-1696
> Adds 'published by' column to file view

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/news.scss
Newsletter: Improve separation line between news
TYPE: Feature
> Improve newsletter separation line

- .github/workflows/tests.yml
- makefile
- setup.cfg
Tries to run CI tests in docker container to reduce install overhead
> Runs tests in our docker container on CI

- .pre-commit-config.yaml
- src/onegov/election_day/models/principal.py
- src/onegov/election_day/templates/layout.pt
- src/onegov/election_day/templates/macros.pt
ElectionDay: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1713
> ElectionDay: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/wtfs/templates/layout.pt
- src/onegov/wtfs/templates/login.pt
- src/onegov/wtfs/templates/macros.pt
- src/onegov/wtfs/views/auth.py
Wtfs: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1708
> Wtfs: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/core/orm/mixins/__init__.py
- src/onegov/core/orm/mixins/content.py
- src/onegov/form/fields.py
- src/onegov/org/forms/fields.py
- src/onegov/org/models/organisation.py
- src/onegov/pas/forms/commission.py
- src/onegov/pas/forms/parliamentary_group.py
- src/onegov/pas/forms/party.py
- src/onegov/pas/models/commission.py
- src/onegov/pas/models/parliamentary_group.py
- src/onegov/pas/models/party.py
- src/onegov/pas/templates/commission.pt
- src/onegov/pas/templates/layout.pt
- src/onegov/pas/templates/parliamentarian.pt
- src/onegov/pas/templates/parliamentary_group.pt
- src/onegov/pas/templates/party.pt
- tests/onegov/core/test_orm.py
Pas: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1716
> Pas: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/core/orm/mixins/content.py
- src/onegov/landsgemeinde/forms/agenda.py
- src/onegov/landsgemeinde/forms/assembly.py
- src/onegov/landsgemeinde/forms/votum.py
- src/onegov/landsgemeinde/models/agenda.py
- src/onegov/landsgemeinde/models/assembly.py
- src/onegov/landsgemeinde/models/votum.py
- src/onegov/landsgemeinde/templates/agenda_item.pt
- src/onegov/landsgemeinde/templates/assembly.pt
- src/onegov/landsgemeinde/templates/layout.pt
- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/templates/ticker.pt
Landsgemeinde: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1717
> Landsgemeinde: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/form/fields.py
- src/onegov/fsi/forms/course.py
- src/onegov/fsi/ims_import.py
- src/onegov/fsi/models/course.py
- src/onegov/fsi/models/course_event.py
- src/onegov/fsi/models/course_notification_template.py
- src/onegov/fsi/templates/macros.pt
- src/onegov/fsi/templates/mail_layout.pt
- src/onegov/fsi/templates/mail_notification.pt
- src/onegov/org/layout.py
Fsi: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1718
> Fsi: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/translator_directory/layout.py
- src/onegov/translator_directory/models/ticket.py
- src/onegov/translator_directory/templates/macros.pt
- src/onegov/translator_directory/templates/translator.pt
- src/onegov/translator_directory/templates/translators.pt
TranslatorDirectory: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1720
> TranslatorDirectory: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/agency/data_import.py
- src/onegov/agency/forms/agency.py
- src/onegov/agency/models/agency.py
- src/onegov/agency/models/ticket.py
- src/onegov/agency/pdf.py
- src/onegov/agency/templates/macros.pt
- src/onegov/agency/upgrade.py
- src/onegov/agency/utils.py
- src/onegov/people/models/agency.py
- tests/onegov/org/test_management.py
Agency: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1721
> Agency: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/core/sentry.py
- src/onegov/winterthur/app.py
- src/onegov/winterthur/daycare.py
- src/onegov/winterthur/templates/daycare.pt
- src/onegov/winterthur/templates/mission_reports.pt
- src/onegov/winterthur/views/settings.py
Winterthur: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1724
> Winterthur: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/feriennet/app.py
- src/onegov/feriennet/layout.py
- src/onegov/feriennet/templates/activities-for-volunteers.pt
- src/onegov/feriennet/templates/activities.pt
- src/onegov/feriennet/templates/bookings.pt
- src/onegov/feriennet/templates/donation.pt
- src/onegov/feriennet/templates/invite.pt
- src/onegov/feriennet/templates/invoices.pt
- src/onegov/feriennet/templates/macros.pt
- src/onegov/feriennet/templates/mail_activity_accepted.pt
- src/onegov/feriennet/templates/mail_activity_archived.pt
- src/onegov/feriennet/templates/mail_booking_accepted.pt
- src/onegov/feriennet/templates/mail_booking_canceled.pt
- src/onegov/feriennet/templates/mail_notification.pt
- src/onegov/feriennet/templates/notification_template_send_form.pt
- src/onegov/feriennet/templates/notification_templates.pt
- src/onegov/feriennet/templates/occasion_attendees.pt
- src/onegov/feriennet/templates/periods.pt
- src/onegov/feriennet/views/booking.py
- src/onegov/feriennet/views/invoice.py
- src/onegov/feriennet/views/notification_template.py
- src/onegov/feriennet/views/occasion.py
- src/onegov/feriennet/views/settings.py
- src/onegov/org/elements.py
- src/onegov/org/models/organisation.py
- src/onegov/org/utils.py
- tests/onegov/org/test_views_pages.py
Feriennet: Removes uses of structure keyword in templates
TYPE: Bugfix
LINK: OGC-1723
> Feriennet: Removes uses of structure keyword in templates

- .pre-commit-config.yaml
- src/onegov/org/layout.py
- src/onegov/org/views/editor.py
Town6: Save and cancel buttons only in edit-bar
TYPE: Bugfix
> Buttons in editmode

- src/onegov/town6/templates/reservation_confirmation.pt
- src/onegov/town6/templates/submission.pt
- src/onegov/town6/theme/styles/town6.scss
Forms, Reservations: Adjust edit button padding
TYPE: Bugfix
LINK: None
> Adjust edit button padding for forms and reservations

- src/onegov/town6/templates/macros.pt
Submission: Change button label to 'Complete'
TYPE: Feature
LINK: ogc-1698
> Form adjust button label

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/mail_new_directory_entry.pt
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/mail_new_directory_entry.pt
Org: Translate mail content
TYPE: Bugfix
LINK: OGC-1595
> Translations

- src/onegov/org/path.py
- tests/onegov/org/test_views_user.py
User Admin: Show 'active' users by default
TYPE: Feature
LINK: ogc-1710
> User admin: Enable 'active' filter by default

- src/onegov/activity/collections/activity.py
- src/onegov/activity/models/activity.py
- src/onegov/org/models/organisation.py
- src/onegov/org/models/resource.py
- src/onegov/org/templates/macros.pt
- src/onegov/org/templates/resource.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/resource.pt
- tests/onegov/activity/test_models.py
Org: Fixes some broken Markup rendering
TYPE: Bugfix
> Org: Fixes some broken Markup rendering

- setup.cfg
- src/onegov/org/views/form_collection.py
- src/onegov/town6/templates/directories.pt
- src/onegov/town6/templates/forms.pt
> More broken markup fixes

- src/onegov/town6/templates/layout.pt
Town6: Move tracking code into header
TYPE: Feature
LINK: OGC-1700
> Move tracking code into head

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/header.scss
- src/onegov/town6/theme/styles/town6.scss
Town6: Allow scrolling in side-navigation
TYPE: Feature
LINK: OGC-1703
> Allow scrolling in side-navigation.

- src/onegov/org/views/people.py
Town6: Editmode People
Add "save" and "cancel" to Edit-bar when editing people.
TYPE: Feature
> Editmode for people editing

- src/onegov/landsgemeinde/views/agenda.py
Landsgemeinde: Remove YouTube recommendations
TYPE: Feature
LINK: OGC-1651
> Hide video suggestions from youtube

- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/news.pt
Town6: Rename Buttons
TYPE: Feature
LINK: OGC-1697
> Rename buttons and translate

- src/onegov/org/views/form_definition.py
- src/onegov/town6/templates/directory.pt
Form: Fix broken rendering
TYPE: Bugfix
LINK: ogc-1738
> Use markup property directly to fix rendering

- src/onegov/org/theme/styles/org.scss
- src/onegov/org/views/settings.py
Org: Show event settings
TYPE: Bugfix
LINK: None
> Org: Show event settings

- src/onegov/org/forms/form_definition.py
Form: Adds email as default mandatory field for new forms
TYPE: Feature
LINK: ogc-1594
> Adds email as default mandatory field for new forms

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/core/sentry.py
Core: Updates Sentry integration for v2.10+
TYPE: Bugfix
LINK: OGC-1745
> Core: Updates Sentry integration for v2.10+

- setup.cfg
- src/onegov/town6/templates/news.pt
News: Swap interchanged links for RSS feed and newsletter subscription
TYPE: Bugfix
LINK: ogc-1763
> Fixes swapped links

- setup.cfg
- src/onegov/core/framework.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/auth.py
- src/onegov/town6/views/auth.py
- src/onegov/user/auth/second_factor.py
- src/onegov/user/cli.py
- src/onegov/user/forms/__init__.py
- src/onegov/user/forms/totp.py
- tests/onegov/core/test_sentry.py
- tests/onegov/org/test_views_auth.py
- tests/onegov/user/test_cli.py
Org: Adds TOTP as a second factor option
TYPE: Feature
LINK: SEA-1413
> Org: Adds TOTP as a second factor option

- src/onegov/translator_directory/forms/translator.py
Translator: Make agency references field optional
TYPE: Feature
LINK: ogc-1753
> Make field optional

- src/onegov/translator_directory/forms/accreditation.py
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- src/onegov/translator_directory/templates/macros.pt
Translator: Adjust admission course text
TYPE: Feature
LINK: ogc-1760
> Adjust admission course text

- src/onegov/org/views/auth.py
Org: Avoids emitting a misleading warning for logged in users
TYPE: Bugfix
> Org: Avoids emitting a misleading warning for logged in users

- pyproject.toml
- src/onegov/agency/excel_export.py
- src/onegov/core/csv.py
- src/onegov/gazette/views/categories.py
- src/onegov/gazette/views/issues.py
- src/onegov/gazette/views/notices.py
- src/onegov/gazette/views/organizations.py
- src/onegov/gazette/views/users.py
- src/onegov/swissvotes/collections/votes.py
- src/onegov/translator_directory/views/translator.py
Makes decision on xlxswriter FIXME
> Makes decision on xlxswriter FIXME

- src/onegov/org/app.py
- src/onegov/translator_directory/forms/accreditation.py
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- src/onegov/translator_directory/views/accreditation.py
- tests/onegov/translator_directory/test_forms.py
Translator Directory: Custom texts for accreditation request
TYPE: Feature
LINK: ogc-1747
Related puppet commit: https://gitea.seantis.ch/operations/puppet/commit/74b04989d84f81640b0a34facd2760d53151db52
> Custom texts for accrediations request

- src/onegov/translator_directory/models/translator.py
- src/onegov/translator_directory/templates/translators.pt
- tests/onegov/translator_directory/test_views.py
Translator Directory: Translators view show last names in uppercase
TYPE: Feature
LINK: ogc-1757
> Show translator lastname in uppercase in translators view

- .pre-commit-config.yaml
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/directory.py
Org: Move and change description of field "delete_when_expired"
TYPE: Feature
LINK: OGC-1764
> Org: Move and change description of field "delete_when_expired"

- src/onegov/landsgemeinde/templates/layout.pt
Landsgemeinde: Add missing closing tag
TYPE: Bugfix
LINK: OGC-1680
> Ogc 1680 notification position

- docs/api/agency/README.md
- src/onegov/agency/api.py
- src/onegov/agency/forms/mutation.py
- src/onegov/agency/views/people.py
- src/onegov/api/models.py
- src/onegov/api/token.py
- src/onegov/api/utils.py
- src/onegov/api/views.py
- src/onegov/core/request.py
- src/onegov/core/utils.py
- src/onegov/org/forms/settings.py
- src/onegov/org/views/settings.py
- tests/onegov/agency/test_api.py
- tests/onegov/api/test_auth.py
Agency: Allows person mutations to be supplied via the API
TYPE: Feature
LINK: OGC-1773
> Agency: Allows person mutations to be supplied via the API

- src/onegov/gazette/locale/de_CH/LC_MESSAGES/onegov.gazette.po
- src/onegov/gazette/views/auth.py
- tests/onegov/gazette/test_views_auth.py
Gazette: Adds Auth view for TOTP second factor (SEA-1413)
TYPE: Feature
LINK: SEA-1413
> Gazette: Adds Auth view for TOTP second factor (SEA-1413)

- src/onegov/wtfs/locale/de_CH/LC_MESSAGES/onegov.wtfs.po
- src/onegov/wtfs/views/auth.py
- tests/onegov/wtfs/test_views_auth.py
Wtfs: Adds Auth view for TOTP second factor
TYPE: Feature
LINK: OGC-1413
> Wtfs: Adds Auth view for TOTP second factor

- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/views/auth.py
- tests/onegov/election_day/views/test_views.py
ElectionDay: Adds Auth view for TOTP second factor
TYPE: Feature
LINK: SEA-1413
> ElectionDay: Adds Auth view for TOTP second factor

- src/onegov/swissvotes/locale/de_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/en_US/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/locale/fr_CH/LC_MESSAGES/onegov.swissvotes.po
- src/onegov/swissvotes/views/auth.py
- tests/onegov/swissvotes/test_views_auth.py
Swissvotes: Adds Auth view for TOTP second factor
TYPE: Feature
LINK: SEA-1413
> Swissvotes: Adds Auth view for TOTP second factor

- src/onegov/translator_directory/templates/translator.pt
- src/onegov/translator_directory/theme/styles/translator_directory.scss
Translator: Translator details in three columns
TYPE: Feature
LINK: OGC-1758
> Three Columns

- src/onegov/form/models/definition.py
FSI: Fix result display of radio buttons
TYPE: Bugfix
LINK: OGC-1612
> Radio buttons only have one choice

- src/onegov/intranet/app.py
- src/onegov/intranet/views/exceptionviews.py
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/header.scss
Intranet: UI Update to foundation 6
TYPE: Feature
LINK: OGC-1772
> Ogc 1772 intranet foundation6

- src/onegov/town6/views/occurrence.py
Event: Re-add lost view `handle_edit_event_filters`
TYPE: Bugfix
LINK: ogc-1784
> Re-add lost view town_handle_edit_event_filters

- .pre-commit-config.yaml
- src/onegov/form/collection.py
- src/onegov/form/models/survey_window.py
- src/onegov/form/upgrade.py
- src/onegov/org/forms/survey_submission.py
- src/onegov/org/layout.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/form.pt
- src/onegov/org/templates/submission_window.pt
- src/onegov/org/templates/survey_results.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/org/views/survey_definition.py
- src/onegov/org/views/survey_submission_window.py
- src/onegov/town6/layout.py
- src/onegov/town6/templates/form.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/submission_window.pt
- src/onegov/town6/templates/survey_results.pt
- src/onegov/town6/theme/styles/town6.scss
- src/onegov/town6/views/survey_submission_window.py
- tests/onegov/org/test_views_forms.py
Org: Allow operlapping submission windows
Aloow overlapping of submission windows as long as they have a title.
TYPE: Feature
LINK: OGC-1785
> Ogc 1785 submission windows

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/extensions.py
- src/onegov/org/models/page.py
- src/onegov/org/templates/mail_confirm.pt
- src/onegov/org/templates/news.pt
- src/onegov/org/templates/topic.pt
- src/onegov/town6/layout.py
- src/onegov/town6/templates/mail_confirm.pt
TYPE: Feature
LINK: OGC-1798
Org: Allows pages to inherit the contact from another topic
TYPE: Feature
LINK: OGC-1798
> Org: Allows pages to inherit the contact from another topic

- src/onegov/winterthur/app.py
Winterthur: Force landscape mode for shift schedule image
TYPE: Bugfix
LINK: ogc-1809
> Force landscape mode for shift schedule image

- setup.cfg
Pin webtests, released a few hours ago
> Pin webtest

- src/onegov/winterthur/templates/roadwork.pt
- src/onegov/winterthur/theme/styles/winterthur.scss
Winterthur: Roadwork show title
TYPE: Bugfix
LINK: ogc-1706
> Winterthur roadwork show title

- src/onegov/org/forms/settings.py
Town6: Field Display
Remove field if there are no TicketPermissions
TYPE: Bugfix
LINK: OGC-1766
> Remove field if there are no TicketPermissions

- src/onegov/user/auth/clients/saml2.py
User: Makes SLO with SAML2 optional
TYPE: Feature
LINK: OGC-1751
> User: Makes SLO with SAML2 optional

- src/onegov/translator_directory/generate_docx.py
Translator: Adjust template variable name for multiple nationalities
TYPE: Bugfix
LINK: ogc-1805
> Adjust template variable name

- src/onegov/org/views/directory.py
Org: Only sends directory entry notifications for public entries
TYPE: Bugfix
LINK: OGC-1806
> Org: Only sends directory entry notifications for public entries

- src/onegov/org/views/directory.py
Org: Also avoids sending a notification for unpublished entries
TYPE: Bugfix
LINK: OGC-1806
> Org: Also avoids sending a notification for unpublished entries

- src/onegov/api/models.py
Api: Only log unexpected exceptions in `ApiException`
TYPE: Bugfix
> Api: Only log unexpected exceptions in `ApiException`

- src/onegov/org/assets/js/common.js
- src/onegov/org/utils.py
- src/onegov/search/utils.py
- src/onegov/town6/assets/js/common.js
- tests/onegov/org/test_browser.py
Org: Make sure anchors in URLs are not viewed as hashtags
TYPE: Bugfix
LINK: OGC-1816
> Ogc 1816 linkify hashtags

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/mail_newsletter.pt
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/mail_newsletter.pt
- tests/onegov/org/test_views_newsletter.py
- tests/onegov/town6/test_views_newsletter.py
Org: Newsletter Text
Add "You no longer wish to receive the newsletter?" to the newsletter footer.
TYPE: Feature
LINK: OGC-1817
> Ogc 1817 newsletter unsubscribe text

- src/onegov/org/request.py
Org: Fixes incorrect news link in navigation
TYPE: Bugfix
LINK: OGC-1843
> Org: Fixes incorrect news link in navigation

- .pre-commit-config.yaml
- src/onegov/user/integration.py
- tests/onegov/user/test_oauth_saml2.py
User: Allows configuring more than one instance of the same provider
TYPE: Feature
LINK: OGC-1856
> User: Allows configuring more than one instance of the same provider

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- setup.cfg
- src/onegov/core/i18n/translation_string.py
- src/onegov/event/collections/events.py
> Removes iCalendar version pins

- src/onegov/org/views/auth.py
- src/onegov/user/auth/core.py
- src/onegov/user/auth/provider.py
- src/onegov/user/integration.py
- src/onegov/wtfs/templates/login.pt
- tests/onegov/user/test_generic_ldap.py
- tests/onegov/user/test_oauth_msal.py
- tests/onegov/user/test_oauth_saml2.py
User: Actually allows multiple providers of the same type to coexist
TYPE: Bugfix
LINK: OGC-1750
> User: Actually allows multiple providers of the same type to coexist

- src/onegov/org/models/extensions.py
Org: Pins ancestor choices in contact inheritance select
TYPE: Feature
LINK: OGC-1853
> Org: Pins ancestor choices in contact inheritance select

- src/onegov/core/cache.py
- src/onegov/core/cli/commands.py
- src/onegov/election_day/views/opendata_swiss.py
- src/onegov/landsgemeinde/views/opendata_swiss.py
- src/onegov/org/models/ticket.py
ElectionDay: Fixes license portion of catalog.rdf for Open Data Swiss
This also fixes the same bug for Landsgemeinde
TYPE: Bugfix
LINK: OGC-1729
> ElectionDay: Fixes license portion of catalog.rdf for Open Data Swiss

- src/onegov/landsgemeinde/templates/macros.pt
Landsgemeinde: Remove Label "Antrag"
TYPE: Feature
LINK: OGC-1846
> Ogc 1846 hide label

- src/onegov/org/models/extensions.py
- tests/onegov/org/test_extensions.py
Org: Fixes removing linked people from an unordered list
TYPE: Bugfix
LINK: OGC-1883
> Org: Fixes removing linked people from an unordered list

- src/onegov/org/layout.py
- src/onegov/org/views/newsletter.py
- src/onegov/town6/views/newsletter.py
- tests/onegov/org/test_views_newsletter.py
- tests/onegov/town6/test_views_newsletter.py
Org: Only managers can add newsletters and see subscribers
TYPE: Bugfix
LINK: ogc-1890
> Only managers can add newsletters and see subscribers

- pyproject.toml
- src/onegov/core/cache.py
- src/onegov/core/cli/commands.py
- src/onegov/core/crypto/token.py
- src/onegov/core/utils.py
- src/onegov/file/filters.py
- src/onegov/file/integration.py
- src/onegov/foundation6/cli.py
- src/onegov/org/formats/digirez.py
- src/onegov/server/cli.py
- src/onegov/swissvotes/external_resources/posters.py
- src/onegov/winterthur/app.py
- tests/onegov/swissvotes/test_external_resources.py
Core: Reviews silenced bandit errors and increases robustness
LINK: SEA-1010
TYPE: Bugfix
> Core: Reviews silenced bandit errors and increases robustness

- src/onegov/org/templates/directory.pt
- src/onegov/town6/templates/directory.pt
Directory: Ensure all values can be displayed in accordion layout
TYPE: Bugfix
LINK: ogc-1895
> Ensure values are type string

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/news.scss
Town6: Remove equalizer from cards
TYPE: Feature
> Remove equalizer and stretch cards per row instead

- src/onegov/org/views/form_submission.py
- src/onegov/town6/views/form_submission.py
FSI: Make Survey Submission Public
The SurveySubmission is finished, but it can still be edited.
TYPE: Bugfix
LINK: OGC-1850
> Ogc surveys

- src/onegov/agency/models/agency.py
- src/onegov/agency/templates/agency.pt
- src/onegov/core/widgets.py
- src/onegov/pdf/pdf.py
- src/onegov/people/models/agency.py
Agency: Ensure a failing pdf file access does not crash application
TYPE: Bugfix
LINK: ogc-1906
> Ensure a failing pdf file access does not crash the page

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
Files: Fix ajax request removing to many elements for action delete
TYPE: Bugfix
LINK: ogc-1851
> Prevent deleting next file info

- src/onegov/winterthur/collections/mission_report.py
- src/onegov/winterthur/views/mission_report.py
- tests/onegov/winterthur/test_mission_reports.py
Winterthur: Adds json and csv view to mission reports
`/mission-reports/json` resp. `/mission-reports/csv`
TYPE: Feature
LINK: ogc-1907
> Mission Reports: Adds json view

- src/onegov/winterthur/static/docs/api/open_data_de.md
- src/onegov/winterthur/templates/mission_reports.pt
- src/onegov/winterthur/theme/styles/winterthur.scss
Winterthur: Adds open data description for mission reports
TYPE: Feature
LINK: ogc-1908
> Extend mission reports with open data description

- src/onegov/fsi/views/audit.py
FSI: Condition for mail reminders
TYPE: Bugfix
LINK: OGC-1898
> Adjust condition for mails

- src/onegov/org/views/external_link.py
Org: External link form editbar buttons
Make sure all relevant buttons are in the edit bar.
TYPE: Bugfix
LINK: OGC-1917
> Ogc 1917 external form

- src/onegov/agency/data_import.py
Agency: Staka LU Do not import person's notes
TYPE: Feature
LINK: ogc-1919
> Staka LU: Do not import people's notes

- src/onegov/winterthur/static/docs/api/open_data_de.md
- src/onegov/winterthur/views/mission_report.py
- tests/onegov/winterthur/test_mission_reports.py
Winterthur: Firefigher mission exports: date in iso format
TYPE: Bugfix
LINK: ogc-1932
> Export mission date in iso format

- .pre-commit-config.yaml
- src/onegov/core/widgets.py
- src/onegov/fsi/forms/subscription.py
- src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
- src/onegov/fsi/models/course_attendee.py
- tests/onegov/fsi/test_views_subscription.py
FSI: Course Subscribtions
Ensure selected course is at least 6 years in the future from the last course the attendee subscribed to
TYPE: Feature
LINK: OGC-1912
> Ogc 1912 course subscriptions

- src/onegov/town6/templates/macros.pt
Town6: Change order in sidebar to contact, persons, docs, links, others
TYPE: Feature
LINK: ogc-1945
> Sidebar order: contact, persons, docs, links, other

- pyproject.toml
- setup.cfg
- src/onegov/user/auth/clients/oidc.py
- src/onegov/user/auth/provider.py
- tests/onegov/user/conftest.py
- tests/onegov/user/test_oauth_oidc.py
- tests/onegov/user/test_oauth_saml2.py
User: Adds OpenID Connect login provider
TYPE: Feature
LINK: OGC-1767
> User: Adds OpenID Connect login provider

- .pre-commit-config.yaml
- src/onegov/org/assets/js/editor.js
- src/onegov/org/assets/js/redactor.de.js
- src/onegov/org/assets/js/redactor.fr.js
- src/onegov/org/assets/js/redactor.it.js
- src/onegov/town6/assets/css/redactor.css
- src/onegov/town6/assets/js/common.js
Town6: Add Sub sub title (h4) to redactor formatting menu
TYPE: Feature
LINK: ogc-1946
> Adds sub-subtitle to redactor including translations

- src/onegov/town6/templates/directory.pt
Town6: Adjust condition for actions view
Create variable for enable_update_notifications and use it for the condition.
TYPE: Bugfix
LINK: OGC-1929
> Create variable for enable_update_notifications

- .pre-commit-config.yaml
- pyproject.toml
- src/onegov/core/collection.py
- src/onegov/election_day/utils/parties/parties.py
- src/onegov/org/utils.py
- src/onegov/user/auth/provider.py
User: Fixes SAML2 not always skipping SLO, despite being disabled
TYPE: Bugfix
> User: Fixes SAML2 not always skipping SLO, despite being disabled

- src/onegov/town6/theme/styles/homepage.scss
Town6: Icon Links
Correct margin and padding if there is no text
TYPE: Feature
LINK: OGC-1943
> Correct margin and padding if there is no text

- src/onegov/agency/utils.py
- tests/onegov/agency/test_utils.py
Agency: Allows ticket notifications to target parent organisations
TYPE: Feature
LINK: OGC-1658
> Agency: Allows ticket notifications to target parent organisations

- src/onegov/election_day/collections/subscribers.py
- src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
- src/onegov/election_day/models/subscriber.py
- src/onegov/election_day/templates/manage/subscribers.pt
- src/onegov/election_day/upgrade.py
- tests/onegov/election_day/collections/test_subscriber_collection.py
ElectionDay: Adds additional data metadata to subscribers
TYPE: Feature
LINK: OGC-1882
> ElectionDay: Adds additional data metadata to subscribers

- src/onegov/org/templates/directory.pt
- src/onegov/org/templates/macros.pt
- src/onegov/org/templates/occurrences.pt
- src/onegov/town6/templates/directory.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/occurrences.pt
Files: Sort sidebar documents alphabetically (org and town6)
TYPE: Feature
LINK: ogc-1797
> Org/Town6: Sort sidebar documents alphabetically

- src/onegov/org/views/directory.py
Org: Re-add submit-button for directory entry suggestion button
TYPE: Bugfix  
LINK: OGC-1986
> Deactivate editmode for entry suggestion

- src/onegov/api/models.py
- src/onegov/api/utils.py
- src/onegov/api/views.py
- tests/onegov/api/conftest.py
- tests/onegov/api/test_models.py
- tests/onegov/api/test_views.py
Api: Makes sure invisible endpoint items are inaccessible
TYPE: Bugfix
LINK:  OGC-1992
> Api: Makes sure invisible endpoint items are inaccessible

- src/onegov/file/attachments.py
- src/onegov/file/filters.py
File: Apply EXIF orientation before stripping EXIF metadata
TYPE: Bugfix
LINK: OGC-1993
> File: Apply EXIF orientation before stripping EXIF metadata

- .pre-commit-config.yaml
- src/onegov/core/csv.py
- src/onegov/election_day/path.py
- src/onegov/landsgemeinde/path.py
- src/onegov/org/cronjobs.py
- src/onegov/pay/models/payment_providers/stripe.py
- src/onegov/user/auth/clients/oidc.py
- src/onegov/user/auth/provider.py
User: Fixes various issues in OIDC authentication provider
TYPE: Bugfix
LINK: OGC-1767
> User: Fixes various issues in OIDC authentication provider

- src/onegov/landsgemeinde/templates/macros.pt
Landsgemeinde: Remove "Auskunft" from Footer
TYPE: Feature
LINK: OGC-1991
> Remove title

- src/onegov/search/indexer.py
- tests/onegov/fsi/test_models.py
Landsgemeinde: Prevent crash on file replacement
TYPE: Bugfix
LINK: ogc-1999
> Prevent application from crashing

- src/onegov/landsgemeinde/custom.py
- src/onegov/landsgemeinde/layouts/assembly.py
- tests/onegov/landsgemeinde/test_views.py
Landsgemeinde: Rename Archive
TYPE: Feature
LINK: OGC-1990
> Ogc 1990 name archive

- src/onegov/form/widgets.py
- src/onegov/town6/theme/styles/forms.scss
Landsgemeinde: File Upload View
TYPE: Bugfix
LINK: OGC-1998
> Ogc 1998 landsgemeinde file upload

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/search.scss
Town 6: Search View
TYPE: Feature
LINK: OGC-1966
> Unify search view for all search results

- src/onegov/form/parser/core.py
Core: Add descriptions in formcode docs
TYPE: Feature
LINK: OGC-1942
> Update formcode documentation

- src/onegov/org/forms/imageset.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/file.py
- src/onegov/org/templates/imageset.pt
- src/onegov/town6/templates/imageset.pt
- src/onegov/town6/templates/imagesets.pt
- src/onegov/town6/templates/macros.pt
Org: Adds optional ordering by filename or caption to image sets
TYPE: Feature
LINK: OGC-2000
> Org: Adds optional ordering by filename or caption to image sets

- src/onegov/feriennet/templates/notification_template_form.pt
Feriennet: Fix save button
TYPE: Bugfix
LINK: OGC-1348
> Add id to form so save-button works

- src/onegov/org/templates/macros.pt
- src/onegov/town6/templates/macros.pt
Org: Sort side panel links alphabetically
TYPE: Feature
LINK: OGC-2008
> Org: Sort side panel links alphabetically

- src/onegov/landsgemeinde/redirects.py
Landsgemeinde: Adds redirect from `/film` to `/topics/film`
TYPE: Feature
LINK: ogc-2039
> Adds redirect from /film to /topics/film

- .pre-commit-config.yaml
- src/onegov/core/converters.py
- src/onegov/org/path.py
- tests/onegov/org/test_views.py
- tests/onegov/org/test_views_news.py
Org: Avoid emitting an exception for invalid years
LINK: SEA-1666
TYPE: Bugfix
> Org: Avoid emitting an exception for invalid years

- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/homepage.scss
Town 6: Homepage video Link
Add option for text-link
TYPE: Feature
LINK: OGC-2040
> Add option for text-link

- src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/fr_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/it_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/rm_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/parser/snippets.py
- src/onegov/org/forms/form_definition.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- tests/onegov/form/test_browser.py
Form: Add formcode definitions
Add more possible definitions in the form editor to choose from.
TYPE: Feature
LINK: OGC-1942
> Ogc 1942 formcode definitions

- homepage_widget_options.md
Town6: Add text_link in homepage widget markdown file
TYPE: Feature
> Add text_link in markdown file

- src/onegov/feriennet/templates/macros.pt
Feriennet: Google Tag Manager
Replace script
TYPE: Feature
LINK: OGC-1353
> Replace src

- homepage_widget_options.md
- src/onegov/town6/homepage_widgets.py
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/homepage.scss
Town6: Add option for label text
TYPE: Feature
LINK: OGC-2040
> Add option for label text

- src/onegov/org/elements.py
- src/onegov/org/views/editor.py
- tests/onegov/town6/test_views.py
> Town6: Make deleting a link more accessible.

- .pre-commit-config.yaml
- src/onegov/gis/assets/js/leaflet-integration.js
> Ogc 1944 versehentliches verstellen des zooms karte

- src/onegov/core/request.py
- tests/onegov/core/test_framework.py
Core: Slightly hardens session_nonce implementation
TYPE: Feature
> Core: Slightly hardens session_nonce implementation

- .pre-commit-config.yaml
- src/onegov/org/models/page.py
- src/onegov/town6/api.py
Org: Api Access
TYPE: Bugfix
LINK: OGC-2075
> Only display public items

- src/onegov/agency/data_import.py
Agency: Staka LU Adds function and academic title fields to pdf export
TYPE: Feature
LINK: ogc-2071
> Staka LU: Adds function and academic title fields to pdf export

- src/onegov/agency/app.py
- src/onegov/agency/pdf.py
- src/onegov/agency/views/settings.py
- src/onegov/pdf/pdf.py
- tests/onegov/pdf/test_pdf.py
Agency: Staka LU No hierarchical numbering in pdf
TYPE: Feature
LINK: ogc-2071
> Adds pdf layout for staka lu with no hierarchical numbering

- src/onegov/agency/pdf.py
Agency: Staka LU Add logo to pdf
TYPE: Feature
LINK: ogc-2071
> Staka LU Adds logo to pdf

- src/onegov/agency/data_import.py
- tests/onegov/agency/test_import.py
Agency: Staka LU Support alliance names in import
TYPE: Feature
LINK: ogc-2071
> Support alliance names

- src/onegov/agency/data_import.py
Agency: Staka LU Use alternative dienststelle name over dienstelle
TYPE: Feature
LINK: ogc-2071
> Priorize alternative name

- src/onegov/town6/assets/js/homepage_video_or_slider.js
Town6: Slider
Fix bug where sizing of slider only worked after resizing the header.
TYPE: Bugfix
LINK: OGC-2056
> Slider on mobile

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/newsletter.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/macros.pt
Town6: Add missing translation
TYPE: Bugfix
LINK: OGC-2064
> Button translation

- src/onegov/activity/matching/score.py
- tests/onegov/activity/test_matching_memory.py
Feriennet: New weights for admin and organizer children and groups in matching
TYPE: Feature
LINK: PRO-1360
> Pro 1360 group boost

- src/onegov/form/fields.py
- src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/fr_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/it_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/locale/rm_CH/LC_MESSAGES/onegov.form.po
- src/onegov/form/widgets.py
- src/onegov/org/assets/js/reservationlist.jsx
- src/onegov/org/forms/reservation.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/templates/find_your_spot.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/org/utils.py
- src/onegov/org/views/resource.py
- src/onegov/town6/theme/styles/forms.scss
- src/onegov/town6/theme/styles/fullcalendar.scss
- tests/onegov/org/test_forms.py
Org: Improves the ergonomics of find my spot reservations
TYPE: Feature
LINK: OGC-2023
> Org: Improves the ergonomics of find my spot reservations

- src/onegov/agency/templates/macros.pt
> Be slighly more robust with added None check.

- src/onegov/websockets/cli.py
- src/onegov/websockets/client.py
- src/onegov/websockets/integration.py
- src/onegov/websockets/server.py
Websockets: Switches away from the deprecated legacy websockets
TYPE: Feature
LINK: OGC-1735
> Websockets: Switches away from the deprecated legacy websockets

- src/onegov/agency/data_import.py
Agency: Staka LU: Use membership title as export field (instead of person function)
TYPE: Feature
LINK: ogc-2107
> Use membership title as export field (instead of person function)

- src/onegov/people/upgrade.py
- src/onegov/ticket/upgrade.py
Ticket: Make db upgrade for ticket closed_on column more performant
TYPE: Feature
LINK: None
> Fix typo in remove lu external id db upgrade

- tests/onegov/activity/test_models.py
- tests/onegov/event/test_models.py
- tests/onegov/feriennet/test_views.py
- tests/onegov/form/test_model.py
- tests/onegov/org/test_browser.py
- tests/onegov/org/test_export.py
- tests/onegov/translator_directory/test_mail_templates.py
- tests/shared/plugin.py
Fixes tests failing at night times.
TYPE: Bugfix
LINK:  OGC-1099
> Fixes tests failing at night times.

- src/onegov/org/assets/js/redactor.js
Org: Rearrange fields in upload-div
TYPE: Feature
LINK: OGC-2078
> Rearrange fields in upload-div

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/person.scss
Town6: Directory preview
Fix display of preview text
TYPE: Bugfix
LINK: OGC-2114
> Ogc 2114 directory preview view

- src/onegov/org/models/extensions.py
- src/onegov/town6/templates/macros.pt
Town6: Display sidebar contact links like sidebar links
TYPE: Feature
LINK: OGC-2112
> Ogc 2112 sidebar links

- src/onegov/town6/theme/styles/town6.scss
Town6: Fix margin for plus and minus button
TYPE: bugfix
LINK: None
> Fix margin right for plus and minus button

- src/onegov/town6/templates/macros.pt
- src/onegov/town6/templates/people.pt
- src/onegov/town6/templates/person.pt
- src/onegov/town6/theme/styles/person.scss
Town6: Enlarge people images
TYPE: Feature
LINK: OGC-2095
> Ogc 2095 people images larger

- src/onegov/agency/api.py
- src/onegov/api/utils.py
Agency: Fixes N+1 Query in the people endpoint for the API
> Agency: Fixes N+1 Query in the people endpoint for the API

- src/onegov/agency/api.py
- src/onegov/api/models.py
Agency: Fixes N+1 queries in the agency/membership endpoints for the API
> Agency: Fixes N+1 queries in the agency/membership endpoints for the API

- src/onegov/agency/templates/macros.pt
- src/onegov/agency/views/agencies.py
Agency: Fixes N+1 query in the agency view
> Agency: Fixes N+1 query in the agency view

- src/onegov/swissvotes/collections/votes.py
- src/onegov/swissvotes/layouts/page.py
Swissvotes: Avoids N+1 query for page slides
> Swissvotes: Avoids N+1 query for page slides

- src/onegov/api/models.py
Api: Avoid logging `None` when no exception is set
TYPE: Bugfix
> Api: Avoid logging `None` when no exception is set

- .pre-commit-config.yaml
- src/onegov/user/cli.py
User: Extend cli `list` command to run over all instances
TYPE: Feature
LINK: None
> Change selector for user list command

- src/onegov/org/forms/settings.py
Org: Fixes rendering of newsletter categories
TYPE: Bugfix
LINK: OGC-2118
> Org: Fixes rendering of newsletter categories

- src/onegov/form/fields.py
- src/onegov/form/parser/form.py
- src/onegov/org/forms/external_link.py
- src/onegov/org/forms/page.py
- src/onegov/org/forms/settings.py
- tests/onegov/form/test_fields.py
- tests/onegov/form/test_parser.py
Form: Switches from native URL field to a text field with URL validation
TYPE: Feature
LINK: OGC-2055
> Form: Switches from native URL field to a text field with URL validation

- src/onegov/org/forms/event.py
- tests/onegov/org/test_views_event.py
Org: Fix reoccurring dates bug
Fix bug where editing an event with reoccurring dates lost the dates.
TYPE: Bugfix
LINK: OGC-2133
> Dates without time so they can be displayed

- src/onegov/org/models/document_form.py
Org: Add extensions to document form
TYPE: Feature
LINK: OGC-2142
> Ogc 2142 people document form

- src/onegov/core/request.py
- src/onegov/org/homepage_widgets.py
- src/onegov/org/models/__init__.py
- src/onegov/org/models/page.py
- src/onegov/org/path.py
- src/onegov/org/templates/news.pt
- src/onegov/org/views/page.py
- src/onegov/town6/api.py
- src/onegov/town6/templates/news.pt
- src/onegov/town6/views/page.py
- tests/onegov/org/test_cronjobs.py
- tests/onegov/org/test_models.py
- tests/onegov/org/test_views_news.py
Org: Adds pagination for News and refactors logic into `NewsCollection`
LINK: OGC-2146
> Org: Adds pagination for News and refactors logic into `NewsCollection`

- src/onegov/org/app.py
- src/onegov/pay/models/payment_providers/datatrans.py
- src/onegov/pay/models/payment_providers/worldline_saferpay.py
Pay: Avoids crash when generating payment button fails
Decreases the log level for failed payment provider connections.
TYPE: Bugfix
> Pay: Avoids crash when generating payment button fails

- .pre-commit-config.yaml
- pyproject.toml
- src/onegov/agency/upgrade.py
- src/onegov/org/assets/js/reservationcalendar.jsx
Org: Adds a date picker to the reservation calendar
TYPE: Feature
LINK: OGC-2149
> Org: Adds a date picker to the reservation calendar

- src/onegov/feriennet/templates/mail_layout.pt
Feriennet: Remove Logo in Mail Header
TYPE: Bugfix
LINK: PRO-1362
> Add own layout for feriennet so there is no unstyled logo in the header

- src/onegov/agency/theme/styles/agency.scss
- src/onegov/feriennet/theme/styles/feriennet.scss
- src/onegov/org/views/settings.py
Agency: Suppress VAT settings
TYPE: Feature
LINK: None
> Suppress vat settings for agencies

- onegov.yml.example
- src/onegov/org/app.py
- src/onegov/org/boardlets.py
- src/onegov/plausible/plausible_api.py
- tests/onegov/org/test_views_dashboard.py
Org: Improve dashboard configuration
TYPE: Feature
LINK: ogc-1528
> Improve api configuration

- src/onegov/org/cronjobs.py
Org: Fixes potential `request_cached` issues in hourly maintenance tasks
Modifying `app.org` without immediate `flush` means `maybe_merge` can fail. So it is more robust to factor the update to the end of the cronjob after all the other things have been done.
TYPE: Bugfix
> Org: Fixes potential `request_cached` issues in hourly maintenance tasks

- src/onegov/core/cli/core.py
- src/onegov/core/directives.py
- src/onegov/core/framework.py
- src/onegov/intranet/security.py
Intranet: Fixes anonymous user permissions
TYPE: Bugfix
LINK: SEA-1790
> Intranet: Fixes anonymous user permissions

- src/onegov/town6/app.py
- src/onegov/town6/assets/js/iframe_request_parameters.js
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/town6.scss
Town6: Option to display breadcrumbs via parameters in iframe
TYPE: Feature
LINK: OGC-2175
> Show breadcrumbs if there is a breadcumb level in the request parameters

- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/templates/agenda_item.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
- src/onegov/landsgemeinde/views/agenda.py
Landsgemeinde: Navigation between assembly items
Add buttons for navigating between assembly items
TYPE: Feature
LINK: OGC-2198
> Ogc 2198 prev next assembly items

- src/onegov/org/layout.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/allocation.py
- tests/onegov/org/test_views_resources.py
Org: Adds copy/paste functionality for availability periods
TYPE: Feature
LINK: OGC-2202
> Org: Adds copy/paste functionality for availability periods

- src/onegov/translator_directory/collections/translator.py
- src/onegov/translator_directory/layout.py
- src/onegov/translator_directory/templates/translators.pt
- tests/onegov/translator_directory/test_views.py
Translator Directory: Use filter in Excel-Export.
TYPE: Feature
LINK: OGC-2217
> Ogc 2217 filter excel export ubersetzerverzeichnis

- src/onegov/landsgemeinde/templates/macros.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
Landsgemeinde: Spacing between icon and time
TYPE: Bugfix
LINK: OGC-1620
> Spacing between icon and time

- .pre-commit-config.yaml
- src/onegov/org/models/person_move.py
- src/onegov/org/templates/document_form_page.pt
- src/onegov/org/views/document_form.py
- src/onegov/town6/templates/document_form_page.pt
- src/onegov/town6/templates/macros.pt
Org: People and Documents in Sidebar
TYPE: Bugfix
LINK: OGC-2142
> Ogc 2142 document forms

- src/onegov/landsgemeinde/assets/js/agenda_items.js
- src/onegov/landsgemeinde/assets/js/ticker.js
- src/onegov/landsgemeinde/templates/ticker.pt
- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
Landsgemeinde: Fix ticker update
TYPE: Bugfix
LINK: OGC-2240
> Ogc 2240 assembly item update

- src/onegov/translator_directory/collections/translator.py
- src/onegov/translator_directory/forms/translator.py
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- src/onegov/translator_directory/path.py
- tests/onegov/translator_directory/shared.py
- tests/onegov/translator_directory/test_collections.py
Translator Directory: Extend search form with `hidden` filter.
TYPE: Feature
LINK: OGC-2232
> Add new filter

- src/onegov/directory/collections/directory.py
- src/onegov/directory/models/directory.py
- src/onegov/newsletter/collection.py
- src/onegov/newsletter/models.py
- src/onegov/org/cronjobs.py
- tests/onegov/org/test_cronjobs.py
Town6: Reactivate recipient in cron job if no longer on postmark suppression list
TYPE: Feature
LINK: ogc-2212
> Reactivate recipient if no longer on postmark suppression list

- do/apply-translations
- do/changes
- do/translate
- pyproject.toml
- setup.cfg
- src/onegov/search/indexer.py
- src/onegov/search/utils.py
- tests/onegov/search/test_integration.py
Search: Replaces `langdetect` with `lingua-language-detector`
LINK: OGC-1781
> Search: Replaces `langdetect` with `lingua-language-detector`

- src/onegov/org/forms/__init__.py
- src/onegov/org/forms/reservation.py
- src/onegov/org/forms/settings.py
- src/onegov/org/forms/util.py
- src/onegov/org/kaba.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/ticket.py
- src/onegov/org/views/reservation.py
- src/onegov/town6/views/reservation.py
Org: Allows key codes in tickets with future reservations to be edited
TYPE: Feature
LINK: OGC-2205
> Org: Allows key codes in tickets with future reservations to be edited

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/org/cronjobs.py
- src/onegov/org/models/resource.py
- src/onegov/org/views/reservation.py
- src/onegov/reservation/upgrade.py
- src/onegov/user/auth/clients/kerberos.py
Reservation: Switches libres JSON columns from `TEXT` to `JSONB`
LINK: OGC-2035
> Reservation: Switches libres JSON columns from `TEXT` to `JSONB`

- src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss
Landsgemeinde: Lines between assembly items
TYPE: Feature
LINK: OGC-2279
> Full width line for assembly items

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/org/cli.py
- src/onegov/org/cronjobs.py
TYPE: Bugfix
LINK: OGC-2288
Org: Fixes mTAN statistics not being sent for every month
TYPE: Bugfix
LINK: OGC-2288
> Org: Fixes mTAN statistics not being sent for every month

- src/onegov/org/app.py
- src/onegov/org/assets/js/occupancycalendar.jsx
- src/onegov/org/assets/js/occupancycalendar_custom.js
- src/onegov/org/forms/settings.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/ticket.py
- src/onegov/org/templates/resource_occupancy.pt
- src/onegov/org/theme/styles/org.scss
- src/onegov/org/utils.py
- src/onegov/org/views/reservation.py
- src/onegov/org/views/resource.py
- src/onegov/town6/app.py
- src/onegov/town6/templates/resource_occupancy.pt
- src/onegov/town6/theme/styles/fullcalendar.scss
- tests/onegov/org/test_views_resources.py
Org: Replaces the occupancy list with an interactive calendar view
TYPE: Feature
LINK: OGC-2236
> Org: Replaces the occupancy list with an interactive calendar view

- src/onegov/org/views/reservation.py
Org: Fixes broken `accept-reservation-with-message` forwarding
TYPE: Bugfix
LINK: OGC-2301
> Org: Fixes broken `accept-reservation-with-message` forwarding

- src/onegov/org/cli.py
Org: Correct invalid submission definitions for Steinhausen
TYPE: Feature
LINK: ogc-2315
> steinhausen: correct invalid submission definition

- do/changes
- src/onegov/ticket/handler.py
- src/onegov/ticket/model.py
- src/onegov/ticket/upgrade.py
Ticket: Store submitter email directly on the ticket
LINK: OGC-2323
> Ticket: Store submitter email directly on the ticket

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/org/utils.py
- src/onegov/swissvotes/views/page.py
TYPE: Bugfix
LINK: OGC-2336
Org: Once again shows the email address in occupancy view
TYPE: Bugfix
LINK: OGC-2336
> Org: Once again shows the email address in occupancy view

- src/onegov/form/parser/grammar.py
- tests/onegov/form/test_grammar.py
Form: Fixes another small regression in formcode related to pricing
TYPE: Bugfix
LINK: OGC-2349
> Form: Fixes another small regression in formcode related to pricing

- src/onegov/town6/templates/parliamentarian.pt
- src/onegov/town6/templates/parliamentary_group.pt
RIS: Link to membership only for managers
TYPE: Feature
LINK: ogc-2377
> Link to membership only for managers

- src/onegov/org/path.py
- src/onegov/parliament/models/political_business.py
- src/onegov/town6/layout.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/political_business.pt
- src/onegov/town6/templates/political_businesses.pt
- src/onegov/town6/views/meeting.py
- src/onegov/town6/views/political_business.py
- src/onegov/town6/views/ris_settings.py
RIS: Adds Political Business views
TYPE: Feature
LINK: ogc-2245
> Initial commit political businesses

- src/onegov/org/assets/js/reservationcalendar.jsx
Org: Fixes small regression in reservation calendar [skip ci]
TYPE: Bugfix
LINK: OGC-2389
> Org: Fixes small regression in reservation calendar

- src/onegov/form/assets/js/chosen-init.js
- src/onegov/org/forms/reservation.py
Form: Adds an optional reset button to forms
Adds that reset button to reservation forms for admins
TYPE: Feature
LINK: OGC-2390
> Form: Adds an optional reset button to forms

- src/onegov/town6/templates/political_business.pt
- src/onegov/town6/views/political_business.py
RIS: Provide `files` to political business template
TYPE: Bugfix
LINK: ogc-2419
> Provide variable files to business view

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/meeting.pt
RIS: Show date and time of meeting
TYPE: Feature
LINK: ogc-2254
per hotfix applied
> RIS Show meeting date and time

- src/onegov/org/assets/js/videoframe.js
Org: Vimeo unlisted videos
TYPE: Feature
LINK: OGC-2412
> Create correct embedded url for unlisted videos

- src/onegov/town6/templates/parliamentarian.pt
RIS: Parliamentarian roles as more list
TYPE: Feature
LINK: ogc-2245
> parliamentarian roles as more list

- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
Feriennet: Word Change
TYPE: Bugfix
LINK: PRO-1402
> Use correct word

- src/onegov/org/assets/js/reservationcalendar.jsx
- src/onegov/town6/theme/styles/town6.scss
Town6: Fix calendar view
TYPE: Bugfix
LINK: OGC-2432
> Fix calendar view

- src/onegov/org/boardlets.py
- src/onegov/org/custom.py
- src/onegov/org/directives.py
- src/onegov/org/layout.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/__init__.py
- src/onegov/org/models/dashboard.py
- src/onegov/org/path.py
- src/onegov/org/templates/dashboard.pt
- src/onegov/org/views/dashboard.py
- src/onegov/org/views/resource.py
- src/onegov/org/views/ticket.py
- src/onegov/ticket/upgrade.py
- src/onegov/town6/templates/dashboard.pt
- src/onegov/town6/templates/macros.pt
- src/onegov/town6/theme/styles/dashboard.scss
- src/onegov/town6/views/dashboard.py
Org: Adds a dashboard for the customer login
TYPE: Feature
LINK: OGC-2421
> Org: Adds a dashboard for the customer login

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- tests/onegov/org/test_views_event.py
- tests/onegov/org/test_views_ticket.py
- tests/onegov/town6/test_views_event.py
Org: Replace label for submit event
Replace `Veranstaltung vorschlagen` with `Veranstaltung erfassen`
TYPE: Feature
LINK: ogc-2433
> Replace label for submitting an event

- src/onegov/org/forms/meeting.py
- src/onegov/org/models/meeting.py
- src/onegov/org/models/meeting_item.py
- src/onegov/town6/layout.py
- src/onegov/town6/templates/meeting.pt
- src/onegov/town6/views/commission.py
- src/onegov/town6/views/meeting.py
- src/onegov/town6/views/parliamentarian.py
- src/onegov/town6/views/parliamentarian_role.py
- src/onegov/town6/views/parliamentary_group.py
RIS: Menu to add, edit and remove meetings
TYPE: Feature
LINK: ogc-2453
> Menu to add, edit and remove meetings

- src/onegov/org/models/political_business.py
- src/onegov/town6/views/parliamentarian.py
RIS: Fix delete parliamentarian
TYPE: Bugfix
LINK: ogc-2397
> RIS: Delete parliamentarian

- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/political_business.py
- src/onegov/org/path.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/political_businesses.pt
- src/onegov/town6/views/political_business.py
RIS: Adds filters to political businesses
TYPE: Feature
LINK: ogc-2423
> Add filters for business type and status

- src/onegov/org/path.py
Org: Avoids invalid ticket `state` parameter propagating to the view
TYPE: Bugfix
> Org: Avoids invalid ticket `state` parameter propagating to the view

- src/onegov/pay/errors.py
- src/onegov/pay/integration.py
Pay: Properly filters our expected Worldline Saferpay payment errors
TYPE: Bugfix
> Pay: Properly filters our expected Worldline Saferpay payment errors

- src/onegov/org/views/directory.py
Directories: Give access to publication dates to editor role
TYPE: Feature
LINK: ogc-2474
> Directories: Allow editors to edit publication dates

- src/onegov/agency/forms/person.py
- src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
- src/onegov/agency/models/agency.py
- src/onegov/agency/models/person.py
Agency: Add miscField for sync.
TYPE: Feature
LINK: OGC-1894
> Agency: Add miscField for sync.

- src/onegov/town6/layout.py
RIS: Adds hard-coded RIS link for non logged-in users
TYPE: Feature
LINK: ogc-2371
> Add hardcoded url for non users

- src/onegov/town6/layout.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/parliamentarian.pt
- src/onegov/town6/views/parliamentarian.py
RIS: Rename parliamentarian membership to function
TYPE: Feature
LINK: ogc-2511
> Change label

- src/onegov/org/views/reservation.py
Org: Avoids hard failures when revocation of a key code fails
Instead we log and report the error as a warning in the front end
when appropriate.
TYPE: Bugfix
LINK: OGC-2539
> Org: Avoids hard failures when revocation of a key code fails

- src/onegov/org/exports/base.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/views/payment.py
- src/onegov/pay/models/payment.py
- src/onegov/pay/models/payment_providers/datatrans.py
- src/onegov/pay/models/payment_providers/worldline_saferpay.py
- tests/onegov/org/test_export.py
Org: Adds additional payment provider specific references to export
TYPE: Feature
LINK: OGC-2545
> Org: Adds additional payment provider specific references to export

- src/onegov/form/models/submission.py
- src/onegov/org/assets/js/tickets.js
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/ticket.py
- src/onegov/org/templates/message_ticket.pt
- src/onegov/org/templates/ticket.pt
- src/onegov/org/views/ticket.py
- src/onegov/ticket/handler.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/message_ticket.pt
- src/onegov/town6/templates/ticket.pt
- tests/onegov/org/test_views_forms.py
- tests/onegov/org/test_views_resources.py
Org: Allows the submitter email to be changed for some ticket types
TYPE: Feature
LINK: OGC-2504
> Org: Allows the submitter email to be changed for some ticket types

- src/onegov/town6/views/meeting.py
RIS: Meeting: Show political business type in any case
TYPE: Bugfix
LINK: ogc-2245
> Meeting: Show political business type in any case

- src/onegov/org/forms/meeting.py
- src/onegov/org/forms/political_business.py
- src/onegov/org/models/political_business.py
- src/onegov/town6/templates/meeting.pt
- src/onegov/town6/views/meeting.py
RIS: Make meeting form more efficient
TYPE: Bugfix
LINK: ogc-2556
> Make meeting form more efficient

- src/onegov/town6/views/commission.py
- src/onegov/town6/views/meeting.py
- src/onegov/town6/views/memberships.py
- src/onegov/town6/views/parliamentarian.py
- src/onegov/town6/views/parliamentarian_role.py
- src/onegov/town6/views/parliamentary_group.py
- src/onegov/town6/views/political_business.py
RIS: Move menu to the top 
Like elsewhere in town6
TYPE: Feature
LINK: ogc-2558
> RIS: Move menu to the top (ogc-2558)

- src/onegov/org/forms/commission_membership.py
- src/onegov/org/models/parliament.py
- src/onegov/org/path.py
- src/onegov/parliament/collections/parliamentarian.py
- src/onegov/pas/forms/attendence.py
- src/onegov/pas/path.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/parliamentarians.pt
- src/onegov/town6/views/parliamentarian.py
RIS: Filtering for multiple parliamentarian attributes
TYPE: Feature
LINK: ogc-2509
> Multiple filtering possible

- src/onegov/pas/templates/changes.pt
- src/onegov/pas/views/change.py
Pas: Fix N+1 query for parliamentarians in `/changes`
LINK: OGC-2560
> performance: Fix N+1 query for parliamentarians in `/changes`

- .pre-commit-config.yaml
- src/onegov/org/constants.py
- src/onegov/org/pdf/ticket.py
- src/onegov/org/views/payment.py
- src/onegov/pdf/pdf.py
- tests/onegov/org/test_pdf.py
Org: Displays invoice items in ticket PDF
TYPE: Feature
LINK: OGC-2563
> Org: Displays invoice items in ticket PDF

- src/onegov/org/views/resource.py
Org: Includes ticket url in iCal event description for compatibility
TYPE: Bugfix
LINK: OGC-2575
> Org: Includes ticket url in iCal event description for compatibility

- src/onegov/org/cli.py
RIS: Make imported files from type general
TYPE: Feature
LINK: ogc-2550
HINT: onegov-org --select /onegov_town6/wil ris-make-imported-files-general-file
> RIS: Make imported files from type general

- src/onegov/town6/assets/js/common.js
Town6: Menu optimization
Only open accordion when clicking on the chevron.
TYPE: Feature
LINK: OGC-2411
> Ogc 2411 wil menu

- src/onegov/core/utils.py
- src/onegov/user/models/user.py
- tests/onegov/user/test_models.py
User: Fixes crash in `User.get_initials` related to dots in the username
TYPE: Bugfix
> User: Fixes crash in `User.get_initials` related to dots in the username

- src/onegov/pas/custom.py
- src/onegov/pas/forms/attendence.py
Pas: Adds default start date for commission.
TYPE: Feature
LINK: OGC-2591
> Pas: Adds default start date for commission

- src/onegov/landsgemeinde/templates/agenda_item.pt
Landsgemeinde: Videoframes
Videoframes for videos in agenda-items
TYPE: Feature
LINK: OGC-2266
> Videoframes for videos in agenda-items

- src/onegov/town6/views/meeting.py
RIS: Create new meeting using form method
TYPE: Bugfix
LINK: ogc-2245
> Create new meeting using form method

- src/onegov/org/forms/resource_recipient.py
- src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
- src/onegov/org/models/recipient.py
- src/onegov/org/templates/mail_customer_messages_notification.pt
- src/onegov/org/views/resource_recipient.py
- src/onegov/org/views/ticket.py
- src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
- src/onegov/town6/templates/mail_customer_messages_notification.pt
Org: Adds customer message notifications to resource recipients
TYPE: Feature
LINK: OGC-2497
> Org: Adds customer message notifications to resource recipients

- src/onegov/org/views/resource.py
Org: Fixes resource iCal no longer filtering to the resource
TYPE: Bugfix
LINK: OGC-2640
> Org: Fixes resource iCal no longer filtering to the resource

- src/onegov/landsgemeinde/forms/settings.py
- src/onegov/landsgemeinde/layouts/agenda.py
- src/onegov/landsgemeinde/layouts/assembly.py
- src/onegov/landsgemeinde/layouts/default.py
- src/onegov/landsgemeinde/locale/de_CH/LC_MESSAGES/onegov.landsgemeinde.po
- src/onegov/landsgemeinde/views/assembly.py
- src/onegov/landsgemeinde/views/settings.py
- src/onegov/org/models/organisation.py
- tests/onegov/landsgemeinde/test_layouts.py
Landsgemeinde: Multiple Name Options
Add setting for different names for assemblies
TYPE: Feature
LINK: OGC-2265
> Ogc 2265 assembly name

- setup.cfg
- src/onegov/parliament/upgrade.py
- src/onegov/pas/collections/parliamentarian.py
- src/onegov/pas/cronjobs.py
- src/onegov/pas/custom.py
- src/onegov/pas/forms/attendence.py
- src/onegov/pas/forms/user.py
- src/onegov/pas/layouts/__init__.py
- src/onegov/pas/layouts/attendence.py
- src/onegov/pas/layouts/user.py
- src/onegov/pas/locale/de_CH/LC_MESSAGES/onegov.pas.po
- src/onegov/pas/request.py
- src/onegov/pas/templates/commission.pt
- src/onegov/pas/templates/macros.pt
- src/onegov/pas/templates/settlement_runs.pt
- src/onegov/pas/theme/styles/pas.scss
- src/onegov/pas/views/commission.py
- src/onegov/pas/views/usermanagement.py
- tests/onegov/pas/test_forms.py
- tests/onegov/pas/test_views.py
Pas: Custom Usermanagement and minor fixes.
- Fixes AttributeError: 'UserManagementLayout' object has no attribute 'drilldown_back'
TYPE: <Feature|Performance|Bugfix>
LINK: <Ticket-Number>
> Pas: Usermanagement

- src/onegov/landsgemeinde/app.py
- src/onegov/landsgemeinde/path.py
- src/onegov/landsgemeinde/redirects.py
- tests/onegov/landsgemeinde/test_views.py
Landsgemeinde: Add assembly redirect
TYPE: Feature
> Ogc assembly rename

- .pre-commit-config.yaml
- setup.cfg
- src/onegov/translator_directory/forms/mutation.py
- src/onegov/translator_directory/locale/de_CH/LC_MESSAGES/onegov.translator_directory.po
- src/onegov/translator_directory/models/ticket.py
- src/onegov/translator_directory/templates/macros.pt
- src/onegov/translator_directory/theme/styles/translator_directory.scss
- src/onegov/translator_directory/views/translator.py
- tests/onegov/translator_directory/test_forms.py
- tests/onegov/translator_directory/test_views.py
<Module>: <Message>
TYPE: Feature
LINK:  ogc-2676
> Extend mutation form for translators.

- src/onegov/town6/templates/political_businesses.pt
- src/onegov/town6/theme/styles/town6.scss
Landsgemeinde: Political Business Styling
TYPE: Feature
LINK: OGC-2471
> Styling political businesses list
