OneGov/onegov-cloud

src/onegov/agency/cli.py
src/onegov/agency/collections/agencies.py
src/onegov/agency/collections/people.py
src/onegov/agency/models/agency.py
src/onegov/agency/path.py
src/onegov/agency/views/agencies.py
src/onegov/agency/views/people.py
src/onegov/election_day/layouts/default.py

Features more intelligent page breaks as in word. Stores page break settings in Agency.meta class. Adds Form in Settings/Organisation to influence page break.
Fixes link generation for:
- root.pdf. Link will be appended a query param using the timestamp of pdf modification
- same for Excel (is for all persons).
- agency pdfs: Recreates the database entry on every generation

Agency pdf rendering

---

src/onegov/agency/app.py
src/onegov/agency/cli.py
src/onegov/agency/collections/agencies.py
src/onegov/agency/collections/people.py
src/onegov/agency/forms/agency.py
src/onegov/agency/layouts/agency.py
src/onegov/agency/models/agency.py
src/onegov/agency/path.py
src/onegov/agency/pdf.py
src/onegov/agency/upgrade.py
src/onegov/agency/views/agencies.py
tests/onegov/agency/test_cli.py
tests/onegov/agency/test_models.py
tests/onegov/agency/test_views.py

Uses WYSIWYG Editor for portrait field of agencies. Migrates current content to html in the same way it was converted for display. agency.portrait_html was left, but returns agency.portrait now.
Checked the pdf generation with migrated data, all links are still in place.
Bullet points, enumeration are added to PDF, but not images.

Agency js editor

---

src/onegov/ballot/models/election/panachage_result.py
src/onegov/election_day/formats/election/internal_proporz.py
tests/onegov/election_day/formats/election/test_internal_proporz.py

- Fixes adding owner for list panachage results
- Adds `parent_connection_id` prefix to `connection_id` to create unique sublist_id's

Zg parties panachage fix

---

src/onegov/fsi/assets/js/ifs.js
src/onegov/fsi/collections/reservation.py
src/onegov/fsi/forms/course_event.py
src/onegov/fsi/layouts/course.py
src/onegov/fsi/layouts/reservation.py
src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
src/onegov/fsi/models/course_event.py
src/onegov/fsi/templates/course_event.pt
src/onegov/fsi/templates/courses.pt
src/onegov/fsi/templates/macros.pt
src/onegov/fsi/templates/mail_layout.pt
src/onegov/fsi/templates/mail_macros.pt
src/onegov/fsi/templates/reservations.pt
src/onegov/fsi/theme/styles/fsi.scss
src/onegov/fsi/views/course.py
src/onegov/fsi/views/reservation.py
tests/onegov/fsi/test_views_course.py

- auto-resizing of iframe
- Hiding cols in reservation table
- lazy-loading switch for accordions /fsi/courses (not yet working as it should)
- use fa icons when printing "course attended" column
Todo: replace the slider element/checked attribute of input DOM element in /fsi/reservations with the actual response from the view Reservation - toggle-confirm.
To check lazy loading of accordion: uncomment `src/onegov/fsi/layouts/course.py:75`
Is the encoding wrong, or the json response has to be in a different format? Any hint would be appreciated

Fsi ui improvements

---

src/onegov/fsi/collections/reservation.py
src/onegov/fsi/custom.py
src/onegov/fsi/forms/course_event.py
src/onegov/fsi/layout.py
src/onegov/fsi/layouts/course_attendee.py
src/onegov/fsi/layouts/course_event.py
src/onegov/fsi/layouts/reservation.py
src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
src/onegov/fsi/models/course_event.py
src/onegov/fsi/templates/course_event.pt
src/onegov/fsi/templates/macros.pt
src/onegov/fsi/theme/styles/fsi.scss
src/onegov/fsi/upgrade.py
src/onegov/fsi/views/reservation.py
tests/onegov/fsi/test_views_course_event.py
tests/onegov/fsi/test_views_reservation.py

Only admins should be able add subscriptions for locked course events.
Adds property `locked_for_subscriptions` to `CourseEvent` and adapts form.
Introduces checks for reservation adding/editing in views.

Fsi locked events

---

src/onegov/fsi/collections/course.py
src/onegov/fsi/forms/course.py
src/onegov/fsi/forms/course_event.py
src/onegov/fsi/forms/reservation.py
src/onegov/fsi/layouts/course.py
src/onegov/fsi/locale/de_CH/LC_MESSAGES/onegov.fsi.po
src/onegov/fsi/models/course.py
src/onegov/fsi/models/course_event.py
src/onegov/fsi/templates/course_event.pt
src/onegov/fsi/templates/course_events.pt
src/onegov/fsi/templates/macros.pt
src/onegov/fsi/templates/mail_macros.pt
src/onegov/fsi/theme/styles/fsi.scss
src/onegov/fsi/upgrade.py
src/onegov/fsi/views/reservation.py
tests/onegov/fsi/test_collections.py
tests/onegov/fsi/test_models.py
tests/onegov/fsi/test_views_course.py
tests/onegov/fsi/test_views_course_event.py
tests/onegov/fsi/test_views_reservation.py

- Adds hiding a course
- Adapted Email Template texts and translations
- order courses by name
- hides Course "Details" button for non-admins
- disables "Subscribe Button" based on other events of the selected year
- prevents selecting attendees that have already other subscriptions of same course in the same year
- adds icons for locked and hidden_from_public
- sends cancellation email when subscription is deleted
- fixes table wrapping even listing macro

Fsi minor updates

---

docs/api/election_day/README.md
docs/api/election_day/format_election_de.md
docs/api/election_day/format_election_fr.md
src/onegov/election_day/formats/election/wabstic_proporz.py
src/onegov/election_day/forms/upload/wabsti_proporz.py
src/onegov/election_day/views/upload/__init__.py
src/onegov/election_day/views/upload/election_creation.py
tests/onegov/election_day/conftest.py
tests/onegov/election_day/fixtures/wabstic_243/WP_Wahl.csv
tests/onegov/election_day/fixtures/wabstic_243/WP_Wahl_errors.csv
tests/onegov/election_day/views/test_views_upload_wabstic.py

Based on the data in WP_Wahl and an existing `DataSource`, the endpoint `/create-wabsti-proporz` will create all elections,
the election compound, and the all `DataSourceItems`. The same `DataSource` can then be used to upload the results.
Type: Feature

ElectionDay: Adds creation of proporz elections from WP_Wahl

---

src/onegov/ballot/models/election/election.py
src/onegov/ballot/models/election/election_compound.py
src/onegov/election_day/templates/election_compound/lists.pt
src/onegov/election_day/templates/embed.pt
src/onegov/election_day/templates/macros.pt
src/onegov/election_day/utils/election/lists.py
src/onegov/election_day/views/election_compound/lists.py
src/onegov/form/fields.py
src/onegov/org/cli.py
src/onegov/org/forms/allocation.py
src/onegov/org/forms/event.py

If the ElectionCompound is after_pukelsheim, hides by default the votes from the list table on the ElectionCompound. Also if after_pukelheim, the bar chart shows only the mandates not the sum of all ListResult.votes.
Type: Feature

ElectionDay: Modifies ElectionCompound list view

---

src/onegov/org/cli.py
src/onegov/org/forms/settings.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/mail.py
src/onegov/org/models/organisation.py
src/onegov/org/models/ticket.py
src/onegov/org/request.py
src/onegov/org/templates/form.pt
src/onegov/org/templates/macros.pt
src/onegov/org/views/event.py
src/onegov/org/views/reservation.py
src/onegov/org/views/settings.py
src/onegov/org/views/ticket.py

Originates from a branch that included fixes for missing reservation snapshots. Adds Ticket Settings for sending tickets. For example the confirmation email when a ticket has been opened was not considered useful by clients. Emails can also be muted globally for all tickets. As experimental feature, in the ticket creation process for reservations of a resource and events, a global setting can intervene and before the email sending, changing the status of the ticket to closed and accepting the corresponding reservations (all of them) or the event. Then the user can get his confirmation email and directly see the ticket status as closed (same view routine e.g. for a resource). For any other type of ticket than RSV and EVN, the small code snippet to close the ticket and trigger the accept …

Org tickets and emails 2

---

src/onegov/gis/assets/js/leaflet-integration.js
src/onegov/swissvotes/external_sources.py

Updates the leaflet integration for the streets api of mapbox, see https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?/=blog&utm_source=mapbox-blog&utm_campaign=blog%7Cmapbox-blog%7Cdoc-migrate-static%7Cdeprecating-studio-classic-styles-d8892ac38cb4-20-03&utm_term=doc-migrate-static&utm_content=deprecating-studio-classic-styles-d8892ac38cb4#leaflet-implementations

Mapbox leaflet update

---

src/onegov/election_day/collections/archived_results.py
src/onegov/election_day/models/archived_result.py
src/onegov/election_day/utils/summaries.py
tests/onegov/election_day/models/test_archived_result.py
tests/onegov/election_day/models/test_notification.py
tests/onegov/election_day/utils/test_summaries.py
tests/onegov/election_day/views/test_views_election.py
tests/onegov/election_day/views/test_views_vote.py

- Update all items calling url /update-results
- no need for a migration (we would need the request object anyway)

Adds turnout to summaries and archived results

---

src/onegov/form/submissions.py
src/onegov/org/forms/extensions.py
src/onegov/org/models/directory.py
src/onegov/org/views/directory.py
src/onegov/org/views/form_submission.py
tests/onegov/org/test_views.py

Up change requests, users had to submit uploaded files again (required or not by the directory). For new submissions, required files are required, for change requests they are never required. Also fixes a bug in the ChangeRequestFormExtension in `is_different` where empty string and None would have been different not triggering the validation.

Directory change request uploads fix

---

src/onegov/form/core.py
src/onegov/org/templates/macros.pt
src/onegov/org/theme/styles/org.scss
tests/onegov/form/test_parser.py
tests/onegov/org/test_macros.py

Enables markdown rendering in org.macros.form. Checks if the Description has any markdown syntax. If so, render it in a seperate html element already introduced for long descriptions that will not used as a placeholder.

Directory markdown field comments

---

src/onegov/agency/models/ticket.py
src/onegov/agency/templates/macros.pt
src/onegov/feriennet/templates/activities-for-volunteers.pt
src/onegov/feriennet/templates/activities.pt
src/onegov/feriennet/templates/macros.pt
src/onegov/feriennet/templates/mail_activity_accepted.pt
src/onegov/feriennet/templates/mail_activity_archived.pt
src/onegov/org/layout.py
src/onegov/org/templates/directory_entry.pt
src/onegov/org/templates/imageset.pt
src/onegov/org/templates/topic.pt
tests/onegov/agency/test_views.py

Linkifies further elements on differnt applications.
On the views used in ongeov.agency in the ticket handlers.get_summary() and the templates they use.
Changes the `page_content` macro to render the lead as structure.
Changes corresponding lead fields in Feriennet and org app (directory lead) to have consistency.

Linkify elements

---

src/onegov/file/sign/swisscom_ais.py

Minor efficiency improvement. The old implementation would create two separate BytesIO buffers for input and output, but pyHanko can sign the document in-place, so only one temporary buffer is necessary.
Due to SpooledTemporaryFile not fully implementing BaseIO we can't pass the infile and outfile directly without some hacky workarounds. But it might be an option for the future, to get rid of the temporary buffer entirely.

Ais2py v2.1.0

---

README.md

pytest dropped the dot in the name already a couple of years ago.

Drop the dot in py.test

---

src/onegov/town6/templates/macros.pt

TYPE: Feature
LINK: OGC-576
Town6: Display absolute date instead of relative.
TYPE: Feature
LINK: OGC-576

Town6: Display absolute date instead of relative.

---

src/onegov/org/forms/settings.py
src/onegov/org/homepage_widgets.py
src/onegov/org/templates/macros.pt
src/onegov/org/theme/org_theme.py
src/onegov/org/theme/styles/org.scss
src/onegov/town6/theme/styles/homepage-tiles.scss
src/onegov/town6/theme/town_theme.py
src/onegov/town6/views/settings.py
tests/onegov/org/test_views_settings.py

Town6: Remove unused tile image option in settings
TYPE: Bugfix
LINK: OGC-592

Remove tile-images

---

src/onegov/town6/templates/macros.pt

Town6: Fix small typo in html tag of person sidebar
Person sidebar is now displayed correctly, without this empty entry. 
TYPE: Bugfix
LINK: OGC-750

Town6: Listing of people displayed is shown without empty entry

---

src/onegov/town6/templates/macros.pt
src/onegov/town6/theme/styles/custom_mixins.scss
src/onegov/town6/theme/styles/homepage-tiles.scss
src/onegov/town6/theme/styles/org.scss

Town6: Homepage tiles pretty hover effect
TYPE: Feature
LINK: OGC-771

Add arrows as hover-effect for homepage-tiles

---

src/onegov/org/homepage_widgets.py
tests/onegov/town6/test_views_newsletter.py

Town6: No news homepage tile
TYPE: Feature
LINK: OGC-832

Ogc 832 no news homepage tile

---

src/onegov/town6/homepage_widgets.py

Town6: Add time to event widget on homepage
TYPE: Feature
LINK: OGC-836

Add time on event homepage widget

---

src/onegov/form/core.py
src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/fr_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/it_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/rm_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/models/submission.py
src/onegov/form/parser/core.py
src/onegov/form/parser/grammar.py
src/onegov/form/validators.py
src/onegov/org/templates/macros.pt
src/onegov/pay/models/payment_providers/stripe.py
src/onegov/pay/utils.py
src/onegov/town6/templates/macros.pt
tests/onegov/form/test_grammar.py
tests/onegov/form/test_parser.py
tests/onegov/org/test_views_forms.py
tests/onegov/pay/test_utils.py

Form: Extends pricing options with a credit card payment flag
This allows users to define custom forms where the credit card payment is mandatory based on whether or not the person submitting the form has selected a certain option or not.
E.g. a delivery field where they have to pay online right away if they want the item to be delivered, but they can pay later in person if they choose to pick it up themselves instead:
```
Delivery *=
( ) Pickup (0 CHF)
( ) Delivery (5 CHF!)
```
TYPE: Feature
LINK: OGC-910

Form: Extends pricing options with a credit card payment flag.

---

src/onegov/form/core.py
src/onegov/form/parser/core.py
src/onegov/form/parser/form.py
src/onegov/form/parser/grammar.py
tests/onegov/form/test_grammar.py
tests/onegov/form/test_parser.py

Form: Adds optional pricing to integer range fields
Price will be multiplied by the amount entered into the field.
The credit card payment flag works on this field as well. E.g:
```
Number of stamps *= 0..30 (0.85 CHF!)
```
TYPE: Feature
LINK: OGC-942

Form: Adds optional pricing to integer range fields

---

src/onegov/stepsequence/extension.py
src/onegov/town6/layout.py
src/onegov/town6/views/directory.py
tests/onegov/stepsequence/test_steps.py

Town6: Allows steps in layouts to be hidden on a per view basis.
This allows sharing the same layout between e.g. a guest view which has a sequence of steps and an editor view which does not.
Hides the step sequence when adding a new directory entry as admin.
TYPE: Feature
LINK: OGC-956

Town6: Allows steps in layouts to be hidden on a per view basis.

---

src/onegov/org/forms/directory.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/models/directory.py
src/onegov/org/views/directory.py
tests/onegov/org/test_views_directory.py

Org: Allows publication dates on directory entries to be required
This is useful for directories where the publication has to be limited e.g. for planning applications, where a public participation period is mandated, but publishing it beyond that would raise privacy concerns.
TYPE: Feature
LINK: OGC-913

Org: Allows publication dates on directory entries to be required

---

src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po

Town6: Adds Missing commas in the error message
TYPE: Bugfix
LINK: OGC-943

Town6: Adds Missing commas in the error message.

---

src/onegov/election_day/utils/election/lists.py
src/onegov/election_day/utils/election_compound/list_groups.py
src/onegov/election_day/utils/parties/parties.py
tests/onegov/election_day/utils/test_election_compound_utils.py
tests/onegov/election_day/views/test_views_election_compound.py

Election Day: Avoid displaying bar charts with only inactive bars.
Show bar chart bars as active as long as no mandate has been allocated.
TYPE: Feature
LINK: OGC-934

Election Day: Avoid displaying bar charts with only inactive bars.

---

src/onegov/form/collection.py
src/onegov/form/display.py
src/onegov/form/fields.py
src/onegov/form/locale/de_ch/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/fr_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/it_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/locale/rm_CH/LC_MESSAGES/onegov.form.po
src/onegov/form/parser/core.py
src/onegov/form/parser/form.py
src/onegov/form/parser/grammar.py
src/onegov/form/validators.py
src/onegov/form/widgets.py
src/onegov/org/layout.py
src/onegov/org/templates/macros.pt
src/onegov/town6/templates/macros.pt
src/onegov/town6/theme/styles/forms.scss
tests/onegov/form/test_collection.py
tests/onegov/form/test_display.py
tests/onegov/form/test_fields.py
tests/onegov/form/test_grammar.py
tests/onegov/form/test_parser.py

Form: Adds `UploadMultipleField` to forms and a modifier to form code.
This is especially useful for custom forms defined using form code since sometimes you want people to be able to submit multiple files without having to create a bunch of single file fields. Example:
```
Documents = *.pdf (multiple)
```
TYPE: Feature
LINK: OGC-915

Form: Adds `UploadMultipleField` to forms and a modifier to form code.

---

src/onegov/event/collections/occurrences.py
src/onegov/org/assets/js/date-range-selector.js
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/templates/macros.pt
src/onegov/org/views/occurrence.py
src/onegov/town6/templates/macros.pt
tests/onegov/event/test_collections.py

Events: Events from the past can be shown.
In the case of 'No events found' we will display two link buttons. One will point to 'all events' where as the other will show 'past events'. In addition a new time range filter 'past events' was added to achieve the same from filters.
TYPE: Feature
LINK: OGC-947

Ogc 947 show events in the past from link

---

src/onegov/event/collections/occurrences.py
src/onegov/org/assets/js/date-range-selector.js
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/templates/macros.pt
src/onegov/org/views/occurrence.py
src/onegov/town6/templates/macros.pt
tests/onegov/event/test_collections.py

Events: Events from the past can be shown.
In the case of 'No events found' we will display two link buttons. One will point to 'all events' where as the other will show 'past events'. In addition a new time range filter 'past events' was added to achieve the same from filters.
TYPE: Feature
LINK: OGC-947

Events: Events from the past can be shown.

---

src/onegov/file/integration.py
src/onegov/form/models/submission.py
tests/onegov/file/test_integration.py

File: Set X-Robots-Tag to noindex if the file's access is `secret`.
By default attachments to directory entries and form submissions are set to `secret` now. They will still be listed in the rendered form.
TYPE: Feature
LINK: OGC-916

File: Set X-Robots-Tag to noindex if the file's access is `secret`.

---

onegov.yml.example
src/onegov/websockets/assets/js/websockets.js
src/onegov/websockets/integration.py
tests/onegov/websockets/conftest.py
tests/onegov/websockets/test_integration.py

Websockets: Add content security policiy tween.
Allows to optionally add a websocket endpoint to the connect-src content  security policy.
TYPE: Feature
LINK: OGC-935

Websockets: Add content security policiy tween.

---

src/onegov/town6/templates/directory.pt

Town6: Make suggestion panel solely dependant on enable_submissions
TYPE: Bugfix
LINK: OGC-955

Make suggestion panel solely dependant on enable_submissions

---

src/onegov/org/homepage_widgets.py

Org: Replaces the entry count in the DirectoriesWidget with the lead
The entry count was misleading because it did not take the entry's visibility into account. Counting properly would be too slow for a widget, so we show the lead instead.
TYPE: Bugfix
LINK: OGC-1006

Org: Replaces the entry count in the DirectoriesWidget with the lead

---

src/onegov/org/views/ticket.py
src/onegov/town6/layout.py
tests/onegov/town6/test_views_forms.py

Town6: Hide Gever Upload in navbar if it is not set in settings
TYPE: Bugfix
LINK:  OGC-922

Town6: Hide Gever Upload in navbar if it is not set in settings

---

src/onegov/form/parser/form.py
src/onegov/form/validators.py
tests/onegov/form/test_parser.py

Form: Accepts submissions of 0-values in required numeric fields
Previously due to 0-values not being truthy, they would get rejected by the DataRequired validator on required fields in user-defined forms.
TYPE: Bugfix
LINK: OGC-1014

Form: Accepts submissions of 0-values in required numeric fields

---

src/onegov/org/assets/js/redactor.js

Org: Catch exception to prevent unresponsive 'link insert' overlay
Even if the call `selectNodeContents` fails – it still works.
TYPE: Bugfix
LINK:  OGC-1013

Org: Catch exception to prevent unresponsive 'link insert' overlay.

---

src/onegov/core/orm/mixins/timestamp.py

Core: Don't use deferral on timestamp columns.
Timestamps don't add a lot of data to queries but accessing them will  lead to a lot of additional queries. Also, nobody expects these  timestamps to be deferred in the first place.
TYPE: Bugfix

Core: Don't use deferral on timestamp columns.

---

src/onegov/election_day/assets/js/notifications.js
src/onegov/election_day/layouts/detail.py
src/onegov/election_day/models/notification.py
src/onegov/election_day/utils/__init__.py
src/onegov/election_day/utils/common.py
src/onegov/election_day/views/election/main.py
src/onegov/election_day/views/election_compound/main.py
src/onegov/election_day/views/election_compound_part/main.py
src/onegov/election_day/views/manage/election_compounds.py
src/onegov/election_day/views/manage/elections.py
src/onegov/election_day/views/manage/notifications.py
src/onegov/election_day/views/manage/votes.py
src/onegov/election_day/views/vote/main.py
src/onegov/org/assets/js/notifications.js
src/onegov/websockets/assets/js/websockets.js
tests/onegov/election_day/common.py
tests/onegov/election_day/models/test_notification.py
tests/onegov/election_day/utils/test_common_utils.py
tests/onegov/election_day/views/test_views_notifications.py
tests/onegov/websockets/test_browser.py

Election Day: Add websocket notification fallback.
Falls back to short polling using a cached endpoint, in case the  websocket server is unreachable or out of workers.
TYPE: Feature
LINK: OGC-991

Election Day: Add websocket notification fallback.

---

src/onegov/org/homepage_widgets.py

Town6: Fixes news not being displayed if it's the first item
Fix root-level page interpretation bug for news, 
which was mistakenly being treated as falsy (index 0). 
TYPE: Bugfix
LINK: OGC-863

Town6: Fixes news not being displayed if it's the first item.

---

src/onegov/event/collections/occurrences.py
src/onegov/org/views/occurrence.py

winterthur: add hint in doc that xml view was made for Winterthur to consume the events from xml
TYPE: Feature
LINK: ogc-1048

Extends code doc for xml view

---

src/onegov/directory/types/directory_configuration.py
src/onegov/org/forms/directory.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/templates/directory.pt
src/onegov/town6/templates/directory.pt

Org: Adds an optional user definable notice when a directory is empty
Empty in this context means no visible entries
TYPE: Feature
LINK: OGC-1005

Org: Adds an optional user definable notice when a directory is empty

---

src/onegov/election_day/assets/js/notifications.js
src/onegov/landsgemeinde/assets/js/ticker.js
src/onegov/websockets/assets/js/websockets.js

Adds fallback to ticker in case of websocket server shutdown and add  timestamp to HEAD request to avoid being browser-cached.
TYPE: Bugfix

Landsgemeinde: Improve ticker code.

---

src/onegov/org/templates/macros.pt
src/onegov/org/templates/occurrence.pt
src/onegov/town6/templates/macros.pt
src/onegov/town6/templates/occurrence.pt

Events: Organizer phone number not always shown and translated
TYPE: Bugfix
LINK: ogc-1222

Add missing translations and use for organizer email

---

src/onegov/event/collections/occurrences.py

Events: Winterthur fix anthrazit export - missing 'rubrik' elements in case of filter
TYPE: Bugfix
LINK: ogc-1048

Fix missing elements under 'rubrik' keeping 'hauptrubrik'

---

src/onegov/org/forms/event.py

Events: filter keywords are not pupulated when editing event
TYPE: Bugfix
LINK: ogc-1219

Fix wrong identation

---

src/onegov/org/templates/macros.pt
src/onegov/town6/templates/macros.pt

Events: Fix how filters are displayed in ticket summary [part 2]
TYPE: Bugfix
LINK: ogc-1219

Move repeat to ul to prevent showing bullet point without text

---

src/onegov/org/forms/event.py

Events: Validate event filter definition does not use names used in `EventForm`
TYPE: Feature
LINK: ogc-1219

Validate if filter keywords not used in EventForm

---

src/onegov/org/templates/occurrence.pt
src/onegov/winterthur/theme/styles/winterthur.scss

Winterthur: Fix back button visibility
TYPE: Bugfix
LINK: OGC-1047

Display Back-Button only for Winterthur

---

src/onegov/agency/models/agency.py
src/onegov/core/orm/mixins/content.py
src/onegov/org/models/organisation.py
src/onegov/org/models/page.py
src/onegov/swissvotes/models/vote.py
src/onegov/translator_directory/models/translator.py

mypy: Gets rid of runtime check for `dict_property` for now
Instead adds proper overloads and adds annotations for the properties
that could not be inferred based on their arguments.

mypy: Gets rid of runtime check for `dict_property` for now.

---

src/onegov/fsi/models/course_event.py

Fsi: Adds missing file extension for vCalendar.
TYPE: Bugfix
LINK: OGC-1319

Fsi: Adds missing file extension for vCalendar.

---

src/onegov/org/forms/event.py

Events: Add assets for event form independent of tag usage
TYPE: Bugfix
LINK: ogc-1318

Adding missing assets for event form

---

src/onegov/org/templates/macros.pt
src/onegov/town6/templates/macros.pt

Search: Search results for events now also show the event start time
TYPE: Bugfix
LINK: ogc-1331

search result template also shows the event start time

---

src/onegov/town6/templates/layout.pt
src/onegov/town6/theme/styles/header.scss

Town6: Scrollbar on open navigation
Scrollbar in Safari and Chrome now looks nicer when you open the navigation and it gets longer than the page. Also there is no vertical scrollbar anymore if you open the menu.
TYPE: Feature
LINK: OGC-1258

Scrollbar on open navigation

---

src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po

Directories: Fix typo in translation in directory export view
TYPE: Bugfix
LINK: ogc-1348

Fix typo in translation

---

setup.cfg
src/onegov/form/display.py
src/onegov/org/templates/macros.pt
src/onegov/swissvotes/models/file.py
src/onegov/town6/templates/macros.pt
tests/onegov/api/conftest.py
tests/onegov/form/test_display.py

Org: Sorts rendered `UploadMultipleField` in template macros
Previous solution caused labels and links to go out of sync
TYPE: Bugfix
LINK: OGC-1410

Org: Sorts rendered `UploadMultipleField` in template macros

---

src/onegov/event/collections/events.py
src/onegov/event/models/event.py
src/onegov/org/forms/event.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/templates/occurrence.pt
src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/templates/occurrence.pt

Town6: Add field for event registration URL
TYPE: Feature
LINK: OGC-1420

Add field for event registration URL

---

src/onegov/directory/models/directory.py
src/onegov/file/integration.py
src/onegov/org/views/files.py
tests/onegov/directory/test_orm.py

Org: Protect `DirectoryFile` when linked to an entry with mTAN access
Previously we relied on file links being impossible to predict, but since someone still may maliciously share a link, we're better off actually protecting the file in simple cases like this.
TYPE: Feature
LINK: OGC-1428

Org: Protect `DirectoryFile` when linked to an entry with mTAN access

---

src/onegov/feriennet/theme/styles/feriennet.scss

Feriennet: Delete rule that hides last navigation Element
TYPE: Feature
LINK: PRO-1239

Remove rule to hide last element in navigation

---

src/onegov/feriennet/cli.py
src/onegov/feriennet/models/activity.py
src/onegov/feriennet/views/activity.py

Feriennet: Fix day labels
Add CLI for re-calculating occasion durations, filter for current period only
TYPE: Bugfix
LINK: PRO-1237

Pro 1237 day labels

---

src/onegov/org/views/page.py
tests/onegov/org/test_views_news.py

Org: Fixed unpublished news invisible for admins
News with a start date in the future were completely hidden in the news overview. Even admins couldn't see them.
TYPE: Bugfix
LINK: PRO-1246

Fix unpublished news invisible even for admins

---

src/onegov/activity/models/occasion.py
src/onegov/activity/models/occasion_need.py
src/onegov/activity/types.py

Resolves the following messages:
```
src/onegov/activity/models/occasion.py:328: error: Unsupported operand types for >= ("int" and "None")  [operator]
src/onegov/activity/models/occasion.py:328: note: Right operand is of type "float | None"
src/onegov/activity/models/occasion.py:332: error: Unsupported operand types for - ("None" and "int")  [operator]
src/onegov/activity/models/occasion.py:332: note: Left operand is of type "float | None"
src/onegov/activity/models/occasion.py:351: error: Unsupported operand types for - ("None" and "int")  [operator]
src/onegov/activity/models/occasion.py:351: note: Left operand is of type "float | None"
src/onegov/activity/models/occasion.py:351: error: Incompatible return value type (got "float | int", expected "int")  [return-value] …
```

Fix type errors in Occasion

---

src/onegov/feriennet/forms/occasion.py

Feriennet: Occasion: Fix omitting verification of max age must be higher than min age for max age
max age higher than min age check can be omitted by setting max age to 0 (zero)
TYPE: Bugfix
LINK: ogc-1257

Ensure min age higher max age check by allowing age 0 (zero)

---

setup.cfg

Org: Pinning pycurl to 7.45.2
https://github.com/pycurl/pycurl/issues/834
TYPE: hotfix

Pin pycurl

---

src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/models/extensions.py
src/onegov/org/models/page.py
src/onegov/org/templates/macros.pt
src/onegov/town6/templates/macros.pt
tests/onegov/org/test_extensions.py
tests/shared/utils.py

Org: Per page option to switch off showing files in the sidebar
TYPE: Feature
LINK: ogc-1477

Adds option to pages not showing files in side panel

---

src/onegov/org/forms/mtan.py

Org: Makes autofill of honeypot field in mTAN forms less likely
TYPE: Bugfix
LINK: OGC-1484

Org: Makes autofill of honeypot field in mTAN forms less likely

---

src/onegov/town6/theme/styles/town6.scss

Town6: Bug Fix for hidden navigation in safari
TYPE: Bugfix
LINK: OGC-1570

Add rule that somehow makes navigation reappear for safari

---

src/onegov/election_day/app.py
src/onegov/election_day/cli.py
src/onegov/election_day/collections/notifications.py
src/onegov/election_day/collections/subscribers.py
src/onegov/election_day/forms/subscription.py
src/onegov/election_day/locale/de_CH/LC_MESSAGES/onegov.election_day.po
src/onegov/election_day/locale/fr_CH/LC_MESSAGES/onegov.election_day.po
src/onegov/election_day/locale/it_CH/LC_MESSAGES/onegov.election_day.po
src/onegov/election_day/locale/rm_CH/LC_MESSAGES/onegov.election_day.po
src/onegov/election_day/models/notification.py
src/onegov/election_day/models/principal.py
src/onegov/election_day/models/subscriber.py
src/onegov/election_day/templates/macros.pt
src/onegov/election_day/templates/manage/subscribers.pt
src/onegov/election_day/upgrade.py
src/onegov/election_day/utils/__init__.py
src/onegov/election_day/utils/notification.py
src/onegov/election_day/views/subscription.py
tests/onegov/election_day/collections/test_subscriber_collection.py
tests/onegov/election_day/common.py
tests/onegov/election_day/forms/test_subscriber_form.py
tests/onegov/election_day/models/test_notification.py
tests/onegov/election_day/models/test_principal.py
tests/onegov/election_day/utils/test_notification_utils.py
tests/onegov/election_day/views/test_views_subscription.py

Election Day: Add notification segmentation.
If `segmented_notifications` is enabled for a principal, email and SMS subscribers can subscribe either to elections and votes of a specific municipality or everything else. Multiple subscriptions are possible.
TYPE: Feature
LINK: OGC-1150
HINT: onegov-election-day --select /onegov_election_day/* migrate-subscribers

Ogc 1150 segmented notifications

---

src/onegov/landsgemeinde/assets/js/ticker.js
src/onegov/landsgemeinde/templates/macros.pt
src/onegov/landsgemeinde/theme/styles/landsgemeinde.scss

Landsgemeinde: Link agenda items in ticker to their own subpage
Agenda items, that are still "scheduled" so far had no working link. Now they are linkt to their own subpage so users can read the description even if the agenda item isn't ongoing yet.
TYPE: Feature
LINK: OGC-1623

Ogc 1623 scheduled agenda item links ticker

---

.github/workflows/tests.yml

<Module>: <Message>
TYPE: <Feature|Bugfix>
LINK: <Ticket-Number>
HINT: <Optional upgrade hint>

Extend github tests to 8 groups/splits

---

src/onegov/org/models/traitinfo.py

Topic: Adds missing trait to move links
TYPE: Bugfix
LINK: ogc-161

Add missing 'move_page_title' trait for links

---

pyproject.toml
setup.cfg
src/onegov/activity/utils.py

Drops pyquery library in favor of pure lxml
We already use lxml in most places anyways, so no point in having this dependency for a function that's just as easy to write with lxml

Drops pyquery library in favor of pure lxml

---

src/onegov/core/utils.py

Core: Removes potential timing side channel when validating yubikeys
TYPE: Bugfix
LINK: SEA-1051

Core: Removes potential timing side channel when validating yubikeys

---

src/onegov/user/auth/core.py

User: Uses random salt for signup token generation
TYPE: Bugfix
LINK: SEA-1051
HINT: Tokens generated prior to the upgrade will become invalid

User: Uses random salt for signup token generation

---

src/onegov/feriennet/layout.py
src/onegov/feriennet/models/notification_template.py
tests/onegov/feriennet/test_views.py

Feriennet: Remove obsolete storage link expansion (as it is html now)
TYPE: Bugfix
LINK: pro-1289

Remove obsolete storage link expansion (as it is html now)

---

src/onegov/agency/cli.py
src/onegov/agency/data_import.py
src/onegov/fsi/cli.py
src/onegov/translator_directory/cli.py
src/onegov/user/auth/provider.py

Search: Avoids Postgres indexer causing invalid transactions
This problem only manifested itself in large import jobs where a lot of ORM events are being generated and the indexer has to be called in the middle of a transaction, rather than at the end. Since we don't yet use the Postgres index we haven't fully fixed this yet and instead drop the ORM events we can't fit into our queue.
This also fixes `ensure_user` failing if the new `username` is already taken by another user.
TYPE: Bugfix
LINK: OGC-1400

Search: Avoids Postgres indexer causing invalid transactions

---

.pre-commit-config.yaml
src/onegov/core/elements.py
src/onegov/core/request.py
src/onegov/swissvotes/layouts/default.py
src/onegov/swissvotes/models/actor.py
src/onegov/swissvotes/models/page.py
src/onegov/swissvotes/models/policy_area.py
src/onegov/swissvotes/models/region.py
src/onegov/swissvotes/templates/layout.pt
src/onegov/swissvotes/templates/macros.pt
src/onegov/swissvotes/templates/page.pt
src/onegov/swissvotes/templates/strengths.pt
src/onegov/swissvotes/templates/vote.pt
src/onegov/swissvotes/templates/votes.pt

Swissvotes: Removes uses of structure keyword in templates
This also bans further uses of said keyword within swissvotes.
TYPE: Bugfix
LINK: OGC-1709

Swissvotes: Removes uses of structure keyword in templates

---

src/onegov/agency/cli.py
src/onegov/agency/data_import.py
src/onegov/fsi/cli.py
src/onegov/search/indexer.py
src/onegov/search/integration.py
src/onegov/translator_directory/cli.py
tests/onegov/search/test_indexer.py

Search: Allows executing the `PostgresIndexer` mid-transaction
Previously the indexer would've invalidated our transaction and vice versa causing the entire request to semi-silently fail with a 409.
TYPE: Bugfix
LINK: OGC-1707

Search: Allows executing the `PostgresIndexer` mid-transaction

---

.pre-commit-config.yaml
src/onegov/core/orm/types/__init__.py
src/onegov/core/orm/types/lowercase_text_type.py
src/onegov/core/orm/types/markup_text_type.py
src/onegov/gazette/collections/notices.py
src/onegov/gazette/forms/notice.py
src/onegov/gazette/layout.py
src/onegov/gazette/models/notice.py
src/onegov/gazette/templates/layout.pt
src/onegov/gazette/templates/macros.pt
src/onegov/gazette/templates/mail_notice_rejected.pt
src/onegov/gazette/templates/mail_on_accept.pt
src/onegov/gazette/templates/notice.pt
src/onegov/gazette/utils/sogc_converter.py
src/onegov/notice/collections.py
src/onegov/notice/models.py
src/onegov/quill/fields.py
tests/onegov/core/test_orm.py
tests/onegov/gazette/test_utils.py
tests/onegov/notice/test_collections.py
tests/onegov/notice/test_models.py
tests/onegov/quill/test_fields.py

Gazette: Removes uses of structure keyword in templates
This also adds `MarkupText` as a new column type
TYPE: Bugfix
LINK: OGC-1715

Gazette: Removes uses of structure keyword in templates

---

src/onegov/org/custom.py
src/onegov/org/path.py
tests/onegov/agency/test_app.py
tests/onegov/org/test_views_user.py

User Admin: Show 'active' users by default 
Move implementation from path to navigation
TYPE: Feature
LINK: ogc-1710

Moves user default active filter from path to navigation

---

src/onegov/activity/collections/period.py
src/onegov/feriennet/templates/period_form.pt
src/onegov/feriennet/views/period.py

Feriennet: Fix bug when there is no prebooking phase
TYPE: Bugfix
LINK: PRO-1296

Only check validity of prebooking dates, if there is a prebooking phase

---

src/onegov/org/templates/macros.pt
src/onegov/town6/templates/macros.pt
src/onegov/town6/theme/styles/person.scss

Town6: Display people images in sidebar 
TYPE: Feature
LINK: OGC-1600

Display people images in sidebar

---

src/onegov/org/templates/message_ticket.pt
src/onegov/town6/templates/message_ticket.pt
tests/onegov/org/test_views_ticket.py

Ticket: Timeline misses state changes 'archived', 'recovered from archive' and 'assigned'
TYPE: Bugfix
LINK: ogc-1779

Fix typo in timeline state

---

src/onegov/town6/theme/styles/header.scss

Town6: Fixes style for link groups in edit bar
The link group does not appear on the same level as the single links
TYPE: Bugfix
LINK: ogc-1799

Get rid of special top padding for link group

---

src/onegov/town6/app.py
src/onegov/town6/assets/js/file-table-row-toggler.js
src/onegov/town6/templates/macros.pt
src/onegov/town6/theme/styles/files.scss

Town6: Make file details closable
TYPE: Feature
LINK: OGC-1822

Toggle Detail-view of file and hide rest if a new one is opened

---

.github/pull_request_template.md
do/changes
src/onegov/core/framework.py
src/onegov/core/orm/cache.py
tests/onegov/core/test_orm.py

Core: Improves performance of `orm_cached` with an in-memory cache
This avoid deserialization overhead for potentially very large nested structures, such as the pages tree. While still properly invalidating the cache between multiple processes.
LINK: OGC-1827

Core: Improves performance of `orm_cached` with an in-memory cache

---

src/onegov/feriennet/queries/occasions_by_state.sql

Feriennet: Fix definition of "overfull"
Attendees, who are blocked aren't counted for an occasion to be "overfull"
TYPE: Bugfix
LINK: OGC-1312

Fix definition of "overfull"

---

src/onegov/form/models/definition.py
src/onegov/org/views/survey_definition.py

Org: Render markup of survey text correctly
TYPE: Bugfix
LINK: OGC-1844

Fix display of survey text

---

src/onegov/org/views/form_collection.py

Town6: Don't linkify the leads in the form and survey overview
TYPE: Bugfix
LINK: OGC-1818

Don't linkify the leads in the form and survey overview

---

src/onegov/form/validators.py
tests/onegov/form/test_validators.py

Form: Fixes `ExpectedExtensions` not working with `.mp3` file ending.
TYPE: Bugfix
LINK: OGC-1795

Form: Fixes `ExpectedExtensions` not working with `.mp3` file ending.

---

src/onegov/town6/templates/macros.pt
src/onegov/town6/theme/styles/town6.scss

Town6: Redesign the find your spot option
TYPE: Feature
LINK: OGC-1831

Redesign the find your spot icon for better visibility

---

src/onegov/landsgemeinde/assets/js/agenda_items.js
src/onegov/landsgemeinde/templates/agenda_item.pt
src/onegov/landsgemeinde/templates/macros.pt
tests/onegov/landsgemeinde/test_views.py

Landsgemeinde: Update timestamp in iframe via js
We now update the timestamp in the iframe video via js, which enables us to turn on autoplay without muting in certrain browsers.
TYPE: Feature
LINK: OGC-1668

Ogc 1668 timestamp via js

---

src/onegov/winterthur/views/mission_report.py

Winterthur: Fix json and csv mission report views in case of no vehicle symbol
TYPE: Bugfix
LINK: ogc-1819, ogc-1931

Fix json and csv views in case of no vehicle symbol

---

src/onegov/town6/templates/directory.pt
src/onegov/town6/theme/styles/town6.scss

Town6: Submissions for new entries
Rearrange condition so enable_submissions gets checked
TYPE: Bugfix
LINK: OGC-1929

Rearrange condition so enable_submissions gets checked

---

src/onegov/town6/templates/macros.pt

Town6: Add direct phone or mobile number in people overview
TYPE: Feature
LINK: OGC-1938

Add direct phone or mobile number in people overview

---

src/onegov/swissvotes/locale/de_CH/LC_MESSAGES/onegov.swissvotes.po
src/onegov/swissvotes/locale/en_US/LC_MESSAGES/onegov.swissvotes.po
src/onegov/swissvotes/locale/fr_CH/LC_MESSAGES/onegov.swissvotes.po
src/onegov/swissvotes/models/vote.py
tests/onegov/swissvotes/test_models.py

Swissvotes: Adds translations for Basel poster collection, adjusts order of poster sources
TYPE: Feature
LINK: swi-42

Adds translations Basel poster collection

---

src/onegov/feriennet/forms/attendee.py

Feriennet: Make it possible to change attendee info without active period
TYPE: Bugfix
LINK: PRO-1341

Make it possible to change attendee info without current period

---

src/onegov/town6/forms/settings.py
src/onegov/town6/templates/macros.pt

Town6: Main image in news
Enable the option to hide main images on news
TYPE: Bugfix
LINK: OGC-1903

Enable to hide main image on news

---

setup.cfg
src/onegov/form/fields.py
src/onegov/org/upgrade.py
tests/onegov/feriennet/test_views.py
tests/onegov/gazette/test_views_notice_attachments.py
tests/onegov/org/test_extensions.py
tests/onegov/org/test_views_directory.py
tests/onegov/org/test_views_event.py
tests/onegov/org/test_views_files.py
tests/onegov/org/test_views_forms.py
tests/onegov/org/test_views_images.py
tests/onegov/org/test_views_pages.py
tests/onegov/org/test_views_photoalbum.py
tests/onegov/org/test_views_resources.py
tests/onegov/org/test_views_search.py
tests/onegov/org/test_views_signing.py
tests/onegov/swissvotes/test_views_page.py
tests/onegov/town6/test_views_event.py
tests/onegov/town6/test_views_images.py
tests/onegov/translator_directory/test_views.py
tests/onegov/winterthur/test_views.py

Org: Avoid generating redundant file links for linked general files
This also updates WebTest to the newest version, since we need it
in order to test multi-file uploads.
TYPE: Bugfix
LINK: OGC-1967

Org: Avoid generating redundant file links for linked general files

---

src/onegov/org/forms/external_link.py

Town6: Lead is no longer a mandatory field in `ExternalLinkForm`
TYPE: Feature
LINK: ogc-1941

External Link Form: Make lead non-mandatory

---

src/onegov/org/assets/js/upload.js

Org: Submits individual uploads in dropzone sequentially
Submitting them in parallel sometimes results in nginx producing 503 errors and there's no significant speed benefit to starting the uploads in parallel, since we will still be limited by our bandwidth.
TYPE: Bugfix
LINK: OGC-1994

Org: Submits individual uploads in dropzone sequentially

---

src/onegov/form/fields.py
src/onegov/form/widgets.py
src/onegov/org/forms/settings.py
tests/onegov/town6/test_views_settings.py

Settings: Displays the web statistics url
TYPE: Feature
LINK: ogc-1639

Adds string field for web statistics url

---

src/onegov/user/auth/provider.py

Omit not needed default value for get
TYPE: Bugfix

Omit not needed default value for get

---

src/onegov/election_day/views/opendata_swiss.py
tests/onegov/election_day/views/test_views.py

ElectionDay: Allows defining the publisher URI via `open_data` metadata.
This also ensures that the default URI is a URN, rather than a URL
since we can't compute a URL that will always be valid.
We now also include the publisher's email directly and not only via the
contactPoint.
TYPE: Bugfix
LINK: OGC-2002

ElectionDay: Allows defining the publisher URI via `open_data` metadata.

---

src/onegov/org/forms/newsletter.py
src/onegov/org/forms/settings.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/models/organisation.py
src/onegov/org/templates/mail_notify_unsubscribe.pt
src/onegov/org/utils.py
src/onegov/org/views/newsletter.py
src/onegov/org/views/subscription.py
src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/templates/mail_notify_unsubscribe.pt
tests/onegov/org/test_utils.py
tests/onegov/town6/test_views_newsletter.py

Newsletter: Adds option to notify admins if a user unsubscribes from the newsletter subscription list
TYPE: Feature
LINK: ogc-2037

Ensure function in case newsletter categories are not enabled

---

src/onegov/org/models/extensions.py
src/onegov/org/models/page.py
src/onegov/org/templates/news.pt
src/onegov/org/templates/topic.pt
src/onegov/town6/layout.py
tests/onegov/org/test_extensions.py

Org: Moves contact inherit functionality to base `ContactExtension`
This means resources, forms and directories can now inherit their contact information from a topic as well.
TYPE: Feature
LINK: OGC-2049

Org: Moves contact inherit functionality to base `ContactExtension`

---

src/onegov/agency/data_import.py

Agency: Staka LU Skip personal email addresses
TYPE: Feature
LINK: ogc-1952

Staka lu: Skip personal email addresses

---

src/onegov/agency/api.py
src/onegov/agency/data_import.py
src/onegov/agency/forms/mutation.py
src/onegov/agency/forms/person.py
src/onegov/agency/locale/de_CH/LC_MESSAGES/onegov.agency.po
src/onegov/agency/models/person.py
src/onegov/agency/views/people.py
src/onegov/api/models.py
src/onegov/org/forms/person.py
src/onegov/org/forms/settings.py
src/onegov/org/models/organisation.py
src/onegov/people/models/person.py
src/onegov/people/upgrade.py
tests/onegov/agency/test_forms.py
tests/onegov/api/test_views.py

- Uses a meta field for the external_user_id (So we don't have a specific column
in `org` for a specific feature of agency)
- Make sure the api uses it's own mutation form such that it's seperated form
public facing mutations.
- Make sure `hidden_people_fields` is honored everywhere
TYPE: Bugfix
LINK: OGC-2061

Improvements for external id

---

src/onegov/feriennet/boardlets.py
src/onegov/org/boardlets.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
tests/onegov/org/test_views_dashboard.py

Org: Show only topics in 'Edited Topics` boardlet on dashboard
TYPE: Bugfix
LINK: ogc-2121

Dashboard: Show only topics in 'Edited Pages` boardlet

---

src/onegov/org/boardlets.py
src/onegov/plausible/plausible_api.py

Org: Fix dashboard translations get lost
Executing `do/translate onegov.town6` made dashboard translations disappear
TYPE: Bugfix
LINK: None

Move translations to boardlet

---

src/onegov/agency/templates/macros.pt
src/onegov/feriennet/templates/bookings.pt
src/onegov/feriennet/templates/macros.pt
src/onegov/feriennet/templates/occasion_attendees.pt
src/onegov/feriennet/templates/volunteers.pt
src/onegov/org/layout.py
src/onegov/org/templates/macros.pt
src/onegov/org/templates/occurrence.pt
src/onegov/org/utils.py
src/onegov/pas/templates/parliamentarian.pt
src/onegov/town6/templates/macros.pt
src/onegov/town6/templates/occurrence.pt
tests/onegov/feriennet/test_views.py
tests/onegov/org/test_utils.py
tests/onegov/org/test_views_event.py
tests/onegov/town6/test_views_event.py

Org: Display phone numbers in international format
The international format prefixes the country code e.g. +41 for Switzerland
TYPE: Feature
LINK: ogc-2113

Town6 display phone numbers in international format

---

src/onegov/search/indexer.py

Search: Reduce log level for `ObjectDeletedError`
TYPE: Feature
LINK: ogc-1999

Reduce log level

---

tests/onegov/user/test_generic_ldap.py
tests/onegov/user/test_roles_mapping.py

Auth: Extends test coverage for `LDAPProvider`
TYPE: Feature
LINK: ogc-2137

Adds tests for roles mapping

---

src/onegov/agency/data_import.py
src/onegov/core/orm/abstract/adjacency_list.py
src/onegov/core/upgrades.py
src/onegov/org/cronjobs.py
src/onegov/org/request.py
src/onegov/people/models/agency.py
src/onegov/server/cli.py
tests/onegov/core/test_adjacency_list.py
tests/onegov/core/test_adjacency_list_performance.py
tests/onegov/org/test_cronjobs.py

Core: Make AdjacencyList use midpoint for insertion of new items.
It's essentially implementing a sparse ordering system where new 
items can be inserted between existing ones. This means we can
now insert news items without having to reorder everything.
LINK: OGC-2134
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/e05b1c4e-d6fd-4724-b13c-242113c9a26b) | ![image](https://github.com/user-attachments/assets/7a83b8f6-c920-40c6-bbd2-eb5a2d041994) |

Core: Make AdjacencyList use midpoint for insertion of new items.

---

src/onegov/reservation/models/custom_reservation.py
tests/onegov/org/test_views_resources.py

Reservation: Fixes decimal fractions being silently dropped in `price`.
This only occurred when the reservation duration wasn’t a whole hour 
e.g., 1.5 hours was truncated to 1.0 hour.
TYPE: Bugfix
LINK: OGC-2152

Reservation: Fixes decimal fractions being silently dropped in `price`.

---

src/onegov/feriennet/views/notification_template.py

Feriennet: Display quotes in mail subjects correctly
TYPE: Bugfix
LINK: PRO-1297

No need to escape a string that doesn't contain html

---

.pre-commit-config.yaml
src/onegov/org/cronjobs.py
tests/onegov/org/test_cronjobs.py

Org: Add retry mechanism for postmark api calls on email bounce statistics cron job
TYPE: Feature
LINK: None
https://seantis-gmbh.sentry.io/issues/6583043507/

Add retry for postmark bounce api call

---

.pre-commit-config.yaml
src/onegov/agency/pdf.py
src/onegov/org/app.py
src/onegov/org/forms/__init__.py
src/onegov/org/forms/reservation.py
src/onegov/org/kaba.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/models/__init__.py
src/onegov/org/models/message.py
src/onegov/org/models/ticket.py
src/onegov/org/pdf/ticket.py
src/onegov/org/templates/macros.pt
src/onegov/org/templates/message_reservation_adjusted.pt
src/onegov/org/theme/styles/org.scss
src/onegov/org/views/reservation.py
src/onegov/pdf/page_functions.py
src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/templates/macros.pt
src/onegov/town6/templates/message_reservation_adjusted.pt
src/onegov/town6/theme/styles/tickets.scss
src/onegov/town6/theme/styles/timeline.scss
src/onegov/town6/views/reservation.py
src/onegov/user/auth/clients/oidc.py
tests/onegov/org/test_views_resources.py

Org: Allows adjusting individual reservations within a ticket
For now these adjustments are limited to the same allocation on the same day. Eventually we may allow moving reservations to arbitrary free allocations as long as the settings on the target allocation allow it.
TYPE: Feature
LINK: OGC-2155

Org: Allows adjusting individual reservations within a ticket

---

src/onegov/server/collection.py

Server: Avoids caching partially configured application instances
Since `CachedApplication` was setting `self.instance` before the application was configured and the server will continue serving subsequent requests after a failed one, it was possible for a partially initialized application to end up in the cache, which leads to cryptic error messages.
It's better if we fail the same way on every request, so we don't get distracted by red herrings.
TYPE: Bugfix

Server: Avoids caching partially configured application instances

---

src/onegov/org/views/newsletter.py
tests/onegov/town6/test_views_newsletter.py
tests/shared/client.py

Newsletter: List all occurrences in newsletter creation form
Previously only Events without their reoccurrences were listed when creating a newsletter
TYPE: Feature
LINK: ogc-2280

Show all occurrences in newsletter form

---

src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/templates/macros.pt
src/onegov/org/templates/mail_macros.pt
src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/templates/mail_macros.pt

Org: Make it more obvious that pay later means pay by invoice
TYPE: Feature
LINK: OGC-2340

Org: Make it more obvious that pay later means pay by invoice

---

src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/models/meeting.py
src/onegov/org/path.py
src/onegov/town6/locale/de_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/fr_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/locale/it_CH/LC_MESSAGES/onegov.town6.po
src/onegov/town6/templates/meetings.pt
src/onegov/town6/views/meeting.py

RIS: Adds menu for meetings
TYPE: Feature
LINK: ogc-2245
replaces https://github.com/OneGov/onegov-cloud/pull/1911 as rebasing failed

RIS: Adds filter for future/past meetings

---

src/onegov/org/cronjobs.py

Org: Fixes mTAN statistics not being sent for every month
The previous fix actually introduced the problem it claimed to fix
TYPE: Bugfix
LINK: OGC-2288

Org: Fixes mTAN statistics not being sent for every month

---

src/onegov/org/forms/event.py
src/onegov/org/locale/de_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/fr_CH/LC_MESSAGES/onegov.org.po
src/onegov/org/locale/it_CH/LC_MESSAGES/onegov.org.po

Ogc: Add hint for ideal event image size
TYPE: Feature
LINK: OGC-2338

Add hint for ideal event image size

---

src/onegov/org/models/political_business.py
src/onegov/town6/templates/political_businesses.pt

RIS: Handle empty status for political businesses
Older political businesses may have no `status` assigned
TYPE: Bugfix
LINK: ogc-2549

Handle empty status for older political businesses

---

src/onegov/org/forms/political_business.py

RIS: Fixes parliamentary group does not get processed when editing political business
TYPE: Bugfix
LINK: ogc-2245

Fixes wrong ids for parliamentary group in form choices

---

src/onegov/org/forms/political_business.py
src/onegov/town6/views/political_business.py

RIS: Resolve issue when creating political business with files
As files cannot be handled in the collection `add` from `get_useful_data` moving to `populate_obj` approach
TYPE: Bugfix
LINK: ogc-2551

Add political business to collection without files

---

src/onegov/town6/theme/styles/header.scss

Town6: Align padding for menu group
TYPE: Feature
LINK: None
Examples are the `Add` menu items for e.g. events or parliamentarians

Town Align padding for menu group

---

src/onegov/org/kaba.py

Org: Improves robustness of Kaba key revocation
Previously it was possible for a `KeyError` to be emitted, which would have been caught by the views, since they do a `clients[site_id]`, even though it definitely should not have been caught.
TYPE: Bugfix
LINK: OGC-2579

Org: Improves robustness of Kaba key revocation

---

src/onegov/town6/assets/js/common.js

Town6: Content-sidebar
Only show content sidebar if there are more than 2 subtitles
TYPE: Feature

Only show content sidebar if there are more than 2 subtitles

---

src/onegov/org/cronjobs.py
tests/onegov/org/test_cronjobs.py

Org: Fix cronjob deletes unpublished events prior its end date
TYPE: Bugfix
LINK: ogc-2562

Fix unpublished events getting deleted by cron job

---

src/onegov/core/cli/core.py
src/onegov/pay/models/invoice.py

Core: Ensures commands that create a new schema run `morepath.autoscan`
This way the SQLAlchemy table metadata is guaranteed to be complete
and matches what it looks like when we run the server.
TYPE: Bugfix
LINK: OGC-2583

Core: Ensures commands that create a new schema run `morepath.autoscan`

---

src/onegov/org/boardlets.py
src/onegov/org/custom.py
src/onegov/org/views/resource.py
src/onegov/ticket/collection.py

Org: Makes the e-mail address for citizen login case-insensitive
Even though the local part can be treated case-sensitively by SMTP servers, in reality no-one really does that. The host is also case- insensitive. So treating the entire address as case-insensitive is most pragmatic. Otherwise people will end up needing multiple logins if their address has been spelled in multiple different ways.
TYPE: Bugfix
LINK: OGC-2601

Org: Makes the e-mail address for citizen login case-insensitive

---

.pre-commit-config.yaml
src/onegov/core/cli/commands.py
src/onegov/core/cli/core.py
src/onegov/user/cli.py
tests/stubtest/depot_allowlist.txt
tests/stubtest/more.webassets_allowlist.txt
tests/stubtest/morepath_allowlist.txt
tests/stubtest/transaction_allowlist.txt

Core: Fixes making ElasticSearch unavailable in all CLI commands
This adds a new context specific setting `skip_es_client` which allows skipping initializing ElasticSearch for commands that don't need it.
TYPE: Bugfix

Core: Fixes making ElasticSearch unavailable in all CLI commands
